### ISSUE TITLE
After Migration to 365 Exchange: Unexpectedly terminated; Outlook Calendar Unavailable; Window Handle already exists; Destination thread no longer exists 

### ISSUE THREAD

**Issue by asgreenb** [phw198/OutlookGoogleCalendarSync#1023]
**OGCS Version**: Portable_OGCS_v2.8.3
**Installed or Portable**: Portable

**Problem Description**  
After migrating from a locally-hosted exchange to a 365 account, OGCS automatically terminates before I can edit the settings.
The error messages are shown below, but
 - start with Outlook Calendar Unavailable; 
 - Window Handle already exists; 
 - Destination thread no longer exists 
 - Unexpectedly terminated

**Any other information**  
![OGCSError](https://user-images.githubusercontent.com/64911719/85750289-914a2200-b6d7-11ea-8b63-b777d19a8c12.png)

**Comment by phw198** [comment]
Pretty sure that's fixed in the just released [2.8.4 alpha](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.4-alpha)...

As per your screenshot, it looks like it crashes before you can opt to upgrade; in which case download the `Setup.exe` from the above link and install from there.

**Comment by asgreenb** [comment]
You are correct. Thank you!
________________________________
