### ISSUE TITLE
Outlook entries are deleted although deletions are disabled (2.8.1.0)

### ISSUE THREAD

**Issue by dl4711** [phw198/OutlookGoogleCalendarSync#1045]
**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Problem Description**  
Hi, I have noticed on several occasions that meetings (often the same calls, I think it mainly affects meeting series) get deleted from my Outlook calendar even if I have deletions disabled. It's even logged in the on-screen log. (see screenshot, the last message is logging the deletion even though it should not be deleting anything...)

Any idea if there is something I can do to enforce meetings not getting deleted?
Is this a known issue?
Any more input you need for debug?

Thanks in advance for help and thanks for a great piece of SW!

BR/Dan
![ogcs_log_screenshot_200721](https://user-images.githubusercontent.com/11614641/88025343-6ca96480-cb34-11ea-92a3-710da2354c18.jpg)

**Comment by phw198** [comment]
The idea behind disabling deletions is a safety mechanism to stop OGCS from removing entire calendar items in the early stages of someone beginning to use the software and still configuring it to work how they need. Once happy it's working as expected, deletions would normally be enabled.

The deletions you are reporting are not for single  items or entire recurring series, but for a single cancelled occurrence within a recurring series - these changes are considered safe and so still being synced by design.
