### ISSUE TITLE
Colour mapping adds rather than changes

### ISSUE THREAD

**Issue by tnjgb** [phw198/OutlookGoogleCalendarSync#1068]
When changing a colour in Google Calendar on an existing appointment (eg Sage to Basil) the new colour category (mapped) is added to the existing (mapped) colour category in Outlook 2016 rather than changing it.

**Comment by phw198** [comment]
I think this is a "feature" as opposed to a bug :slightly_smiling_face: 

Before mapping, OGCS would create a new category in Outlook with the closest matched colour and call it eg "OGCS Red". It did this to avoid assigning any other red category you might already have configured for something else. OGCS would only allow a single "OGCS" prefixed category to be assigned in Outlook, because Google could only ever have one.

With the advent of mapping in OGCS, these "OGCS" prefixed categories are no longer required as you can specify exactly which Google colour should go to which Outlook category. However, because Outlook supports multiple categories, OGCS has no way of knowing if it added the assigned Outlook category or you did. If you did, OGCS very likely shouldn't be removing it!

The sneakiest workaround is to name the Outlook categories you only ever want one of with "OGCS " at the start. Also use these in your mappings.

**Comment by phw198** [comment]
I've now added an extra option to help with this. It's a little tricky to explain but have tried with a tooltip hover-over...

![image](https://user-images.githubusercontent.com/11843015/97790129-e1714d80-1bbd-11eb-8401-3bdc96bc14f2.png)

:package: Please see how it goes with [development build v2.8.5.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5469814/v2.8.5.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by tnjgb** [comment]
From the brief tests I have done it appears to have solved my issue. Thanks.

**Comment by tnjgb** [comment]
A new issue seems to have been created in that new appointments created in Google and assigned the default Google "calendar colour" of pale blue (as in I have not assigned a specific colour to the new appointment) are now assigned the "OGCS blue" category in Outlook when there should be no category.

**Comment by phw198** [comment]
Thanks for spotting that. Assuming you don't configured a custom mapping to work off the default Google calendar colour, this should now be resolved.

:package: Please try with [development build v2.8.5.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5506862/v2.8.5.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.

**Comment by tnjgb** [comment]
Thanks, it appears OK on first test appointments.
