### ISSUE TITLE
Multiple account support

### ISSUE THREAD

**Issue by znoxwl** [phw198/OutlookGoogleCalendarSync#1070]
**Is your feature request related to a problem? Please describe.**
I need to sync more than one Outlook account but currently it only supports one (or that I'm dumb, if so, please let me know).

**Describe the solution you'd like**
Setup multiple account syncing.

**Describe alternatives you've considered**

**Additional context**

**Comment by as1414** [comment]
+1 for multiple calendar sync.  

Just came across this, looking for alternatives to gSync.  Seems like the google tab could still hold the primary connection information, but the outlook tab could let you add the link of outlook calendar name -> google calendar name.  To start, all other categories, filters, formatting, etc. could span across all calendars rather than doing each setting on a calendar-by-calendar basis.  Without looking at the code, seems like this could be an easier starting point.  

Looks pretty straight forward so far.  Thanks.

**Comment by as1414** [comment]
Seems like this can be combined with #1054

**Comment by znoxwl** [comment]
Oops somehow I didn't find that post in my search.
