### ISSUE TITLE
Will I get automatic upgrades, or alerts about new upgrades?

### ISSUE THREAD

**Issue by johnaweiss** [phw198/OutlookGoogleCalendarSync#1071]
**Are you already using OGCS?**
yes

Provide the version number.
2.8.0.0

**Describe the question you have**
- Will I get automatic upgrades, or alerts about new upgrades? Betas? Non-betas?
- Must i manually click the sync button? Or can i get auto-sync?
- In sync-settings, what does "in the" mean?
![image](https://user-images.githubusercontent.com/53209681/91345947-03e98380-e795-11ea-9d06-adfda7153678.png)
- Why can't i set interval to 10 minutes or 1 hour?

thx

**Comment by as1414** [comment]
@johnaweiss I'm new here... but seems like your answers would be..

1 - About tab has a button to check.
2 - This can be timed as outlined in your screenshot above (every x hours or minutes)
3 - my install says -- top = "days in the past", bottom = "days in the future"
4 - why would you need to set an optional interval??  This is your sync schedule you were asking about.  I'm not sure what triggers the outlook changes one to commit, but as long as the program remains running it will sync again in x hours/minutes depending on your setting here.

**Comment by johnaweiss** [comment]
Thx, hopefully someone from the team can reply.

**Comment by BassTea87** [comment]
the guide says "Interval: The number of hours or minutes between automated syncs. Setting it to zero turns off automated syncs, relying upon on-demand manual synchronisations.
15 minutes is the minimum sync frequency allowed, unless Push Sync is also enabled in which case it is 120 minutes."

This is because all OGCS users share a Calendar API quota which is limited to 1 Mio queries a day and it needs to be managed somehow that no users consumes to much of that quota. You can create an own google API account with an own key. Then you 1 Mio queries a day just for yourself and interval settings are more flexible.

**Comment by phw198** [comment]
No reply from the "team" (just me) required - the user community have answered as well as I would have. 

Thanks @as1414 @BassTea87!
