### ISSUE TITLE
2-way sync: Don't delete excluded items

### ISSUE THREAD

**Issue by ghnogueira** [phw198/OutlookGoogleCalendarSync#1083]
This issue has morphed into that contained in [this comment below](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1083#issuecomment-919205751).

----
Hi. I may be doing this the wrong way (and therefore I need this enhancement that wouldn't be needed if I did it properly, so please just lecture me if such), but I have 2 Google calendars and 1 Outlook calendar to be synced:

- Google: "Personal" calendar, to be synced TO Outlook
- Google: "Outlook" calendar, to be synced FROM Outlook
- Outlook: business calendar, to be synced TO and FROM Google

When I sync data FROM Google TO Outlook, I set it to be a private out of office entry, so people in my company doesn't see what the appointment is and I show as out of office. But when I sync my business calendar TO Google, there's no option **not to sync** private appointments, and therefore an item that was created in my personal Google calendar is now synced back to Google in the "Outlook" Google calendar, making it a "duplicate".

How can I avoid that, or if not, can if be added as an option? (not to sync private/free/etc etc appointments as below)

![000011](https://user-images.githubusercontent.com/66975674/92514798-e4b51200-f1e8-11ea-8dee-208683b836e8.jpg)

**Comment by phw198** [comment]
Er, you do realise you've posted to the OGCS GitHub project but screenshot gSyncit?

**Comment by ghnogueira** [comment]
Erm, yes... I was just trying to use that as an example of what I was talking about :) it has many different sync options, so that's what I tried to show. I'm not using gSyncit anymore and began using OGCS, which I'm quite happy about, but just wondered how to do such a thing.

**Comment by phw198** [comment]
Gotcha :wink:  So the solution with existing configuration options would be to:-

* G->O: For all synced items to target calendar set category to something (eg OGCS)
* O->G: Filter categories to exclude that category (ie OGCS)

Does that fulfil what you need?

**Comment by Imbutien** [comment]
Hi,

This is to say that your workaround is not working.
Once the events have been synced to outlook from google, then OGCS ask to delete them in google because they are filtered out of sync...
In my attached log file, these events are named ""Absent / Off""
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7141782/OGcalsync.log)

Thank you for your support ; your program is great and i've donated but i still face issues like this one 😥

**Comment by phw198** [comment]
Agreed, my proposed workaround would not work for a standard 2-way sync, as I think you are doing, but I understood the OP to have multiple one-way syncs configured between 3 calendars and I think for that the workaround is OK.

I'll continue to leave this enhancement open for future consideration.

**Comment by Imbutien** [comment]
Thank you !

We may have a workaround that would require an update in your code. My need is to set 9am to 6pm event as unavailable/away in Google so that my colleagues know that i'm not available these days. Once sync to outlook that i use for another project, i'd like these event to be set as free not busy so that my colleagues on this project don't think i'm off.
I'm set 2-way sync
- On Google Side, i set my event (a recurring one)
- at first sync, outlook create the event
- i can then set a category in outlook to exclude this event

At the curren time, when the sync is triggered, OGCS want to delete this event as it is excluded from sync. :( 
If OGCS can check that whenever an event has to be deleted BUT is excluded from sync then forget it forever.
You can also add a checkbox on deletion popup "forget it" that will do the same with event that should not be deleted.

What do you think of this workaround ?

**Comment by phw198** [comment]
> If OGCS can check that whenever an event has to be deleted BUT is excluded from sync then forget it forever.

Yep, I think this would have to be the solution :+1:

**Comment by Imbutien** [comment]
Great 👍 if you can set this up in a next alpha release, please let me know

**Comment by phw198** [comment]
@ghnogueira As your request pertains to multiple one-way syncs, I will track your request over on #415. You may also be interested in being an early adopter of #1307.

**Comment by ghnogueira** [comment]
Hi Paul. I think this is solved with your workaround and filters, no?!

**Comment by phw198** [comment]
@ghnogueira Yes, the workaround is good for you. Just you might want to run a single instance of OGCS and use _profiles_ for the multiple one-way syncs.

@Imbutien Just a clarification: why do you need to set a category to exclude the "free" items in Outlook? Are you not setting "for all items synced to Outlook, set as free"? Or do items normally need to be synced as per their Google availability and you're just overriding these 9-5 ones individually?

**Comment by ghnogueira** [comment]
Yep, I am already using profiles :)

**Comment by Imbutien** [comment]
> @ghnogueira Yes, the workaround is good for you. Just you might want to run a single instance of OGCS and use _profiles_ for the multiple one-way syncs.
> 
> @Imbutien Just a clarification: why do you need to set a category to exclude the "free" items in Outlook? Are you not setting "for all items synced to Outlook, set as free"? Or do items normally need to be synced as per their Google availability and you're just overriding these 9-5 ones individually?

By default, i'm set to have events to busy. This is to override as i need these event to be set as free not busy so that my colleagues on this project don't think i'm off.
So this would be an override setting that is usefill when you mix several calendar and have exceptions.

**Comment by phw198** [comment]
Note, #1682 will default the behaviour back to deleting synced Google items where Outlook is excluded by category - this was the behaviour before #1083. You will need to turn off the setting to reinstate _not_ deleting:

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/61f44435-3208-45f4-a788-1540f9033b24)
