### ISSUE TITLE
New Event Failed to Save

### ISSUE THREAD

**Issue by Soulace1970** [phw198/OutlookGoogleCalendarSync#1105]
I had to reinstall pc and OGCS. Wont sync. Log file attached.

Connects to Google account fine starts sync and fails: New Event Failed to Save

Needs write access to Google Calender yet in Google OGCS has access to usual See, Edit, Share etc

Email sent 19/10/20

Regards
Alex

soulace@dodo.com.au

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
