### ISSUE TITLE
Value not allowed to be null

### ISSUE THREAD

**Issue by androt00** [phw198/OutlookGoogleCalendarSync#1110]
When I sync, I get a "Source" value not allowed to be null error. All my settings worked previously, and I have not changed anything knowingly.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5445854/OGcalsync.log)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by androt00** [comment]
I have upgraded to 2.8.5. I now get a different error, "...too many connections...". 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5517415/OGcalsync.log)

**Comment by phw198** [comment]
The full new error was
> The number of items that can be opened at one time has been limited by the server administrator. First, close any open messages, or remove attachments and pictures from unsent messages you are composing.

It looks like you're running in Exchange online mode - try switching to cached online mode in Outlook account settings. Alternatively reduce the date range you have configured for sync.
