### ISSUE TITLE
missing calendar

### ISSUE THREAD

**Issue by udiudiudiudi** [phw198/OutlookGoogleCalendarSync#1113]
so i just downloaded version 2.8, and 1 of my calendars were missing there.

however using pppindia software that calendar was showing,

i will be very happy to help you investigate why this calendar was missing, if you tell me what to send you.

**Comment by SeanKilleen** [comment]
Hi @udiudiudiudi,

You may wish to describe exactly what you are seeing -- you can paste screenshots here to upload them as well.

For example, where is your calendar missing? Is it an outlook calendar that is missing, or a google calendar?

If you are missing an Outlook calendar, is it a calendar under your default mailbox? Or is it a shared / group calendar? If it's a shared or group calendar, you may need to select "Alternative mailbox" on the outlook tab and select the appropriate mailbox in order to show the calendar in the "Select calendar" list below it.

**Comment by udiudiudiudi** [comment]
i dont know which is my default calendar

here are 3 photos
your software
another software
my outlook

![your software](https://user-images.githubusercontent.com/36422655/98018653-7b790600-1e09-11eb-8b63-934e348fab3d.png)

![another software](https://user-images.githubusercontent.com/36422655/98018681-82a01400-1e09-11eb-8dc1-15bb65c793fd.png)

![outlook](https://user-images.githubusercontent.com/36422655/98018717-8895f500-1e09-11eb-8e1b-4d1a46266525.png)

**Comment by phw198** [comment]
Hi @udiudiudiudi 

In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

It might be helpful to also screenshot the Outlook account settings for both udi@saveatrain.com and info@saveatrain.com, see if there's any difference between the two accounts.

**Comment by phw198** [comment]
Any update @udiudiudiudi or can the issue be closed?

**Comment by udiudiudiudi** [comment]
I Ended up using another software for now
happy new year
