### ISSUE TITLE
Subscription contact

### ISSUE THREAD

**Issue by winproof** [phw198/OutlookGoogleCalendarSync#1124]
**Are you already using OGCS?**
2.8.0

**Describe the question you have**
hello
i'm the IT administrator of a company, we actually use ogcs for 3 users. (maybe more in future)
we need a personal API quotas.
for this we want to buy a subscription, but it's complicated to have a "direct contact" with you, there is no email on your github profile and twitter (@ogcs) do not accept message.
can you provide me a link (email, twitter message or other things) to contact you?
Thanks

**Comment by winproof** [comment]
hello?

**Comment by phw198** [comment]
Hi @winproof 

Thanks for contacting. Email is ogcs (at) paulwoolcock.co.uk (removed from main profile due to spam) and the twitter handle should be https://twitter.com/OGcalsync 

Normally subscriptions are made using the link that is available when a user encounters errors related to expired quota. However, if you add the Google accounts that are being used by OGCS to the link below (replace `<enter@youremail.com>`), then you can do this at your convenience:
```
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=E595EQ7SNDBHA&item_name=OGCS+Premium+for+<enter@youremail.com>
```
Make sure the email address matches what OGCS displays in `Settings` > `Google` > `Connected Account`, including case.

Thanks!
