### ISSUE TITLE
Sync error -   Das Objekt unterstützt diese Methode nicht.  

### ISSUE THREAD

**Issue by ClaudiaSe** [phw198/OutlookGoogleCalendarSync#1136]
Dear All
Which Object does not support the method? Which method?
What do I have to do?
Thanks for your help!

![grafik](https://user-images.githubusercontent.com/7332329/101460698-38471100-393a-11eb-9b83-cc0d5de28e5e.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5657979/OGcalsync.log)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
