### ISSUE TITLE
OGCS requests to delete events instead of synchronizing them

### ISSUE THREAD

**Issue by amig500** [phw198/OutlookGoogleCalendarSync#1148]
![image](https://user-images.githubusercontent.com/76042836/103994479-5b621c00-5197-11eb-9dfd-df9dd9784a7b.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5786172/OGcalsync.log)

> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: Version 2.8.5.14
**Edition**: Installed / Portable  
**Sync Direction**: O<->G

**Bug Description**  
This bug was supposed to be solved but is not.
OGCS requests to delete events instead of synchronizing them
I have events in Outlook that are asked to be removed when OGCS syncs. They are not pushed to Google.

**Steps to Reproduce the Issue**  
1. Create any event in a future time.
2. Sync two way
3. You can also reproduce the issue by just changing the time or date of one occurence of a recurrent series of events.

![image](https://user-images.githubusercontent.com/76042836/103994857-e3e0bc80-5197-11eb-95b5-463992254c1b.png)

**Comment by phw198** [comment]
You keep stating you have the same issue as #1123, but you don't. That issue described the new Outlook event being created in Google and then in the same sync immediately being deleted in Outlook. 

You are saying the new Outlook event is never synced, but then deleted - so v2.8.5.14 is unlikely to fix this. I assume your problem was the same under v2.8.5.0 and v2.8.0.0 as reported on #1128?

In #1128 you were specifically reporting a single Outlook appointment that was always deleted, but now you are saying it is _any_ future created Outlook appointment? How are you creating that new item? Are you copying and pasting an existing item? If so, try creating it from scratch instead.

Please could you also change your logging level to `DEBUG`, reproduce the issue and then upload the logfile again.

**Comment by amig500** [comment]
Sorry but your answer is not easy enough for me to understand. We are not all developpers!
This post never says it is related to #1123 or any other. You wrote this.

The problem is:
1- ANY new event created in Outlook
2- sync
3- OGCS requests to delete it in Outlook
4- the event is not on Google
I had the problem, then I upgrated to this strange version, and it is not solved yet. I can not help more except if you explain very clearly, step by step, for dummies, how to test differently.

**Comment by phw198** [comment]
[This comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1123#issuecomment-751508018) says you think you have encountered "exactly the same problem" on #1123, you've then applied the hotfix associated with that and posted here that "This bug was supposed to be solved but is not.". Ergo, you think it's related to #1123.

Once again, the issue you describe above is _not_ related to #1123 - therefore applying hotfix v2.8.5.14 will not somehow resolve your issue. 

You have already changed the logging level of OGCS to `INFO`, I simply requested you to change it back to `DEBUG`, reproduce the issue and re-upload you logfile. I also asked how you were creating the new future Outlook item, whether it was a copy and paste of an existing item. I'm unclear how this constitutes developer speak?

**Comment by amig500** [comment]
Dear @phw198 you really overestimate my skills.
I am not precise as you are. I just reported a problem, saw something that looked like it. Maybe it is not very exactly perflectly totally the same. I dont know and I just wanted to trigger a warning that there was a bug.
About the logging level, I obviously never changed anything. So please explain me how to do it instead of saying I already did it, because I did not.

**Comment by OGCS-User** [comment]
Hi @phw198 
I've got the same problem. OGCS is running fine but when I receive an invite in Outlook the sync cycle creates the entry in Google. Then mysteriously the entry in Outlook disappears and with the next cycle - as there isn't an entry in Outlook anymore - the generated appointment in Google disappears as well.

OGCS version 2.8.5.0
MS Office 18.2008.12711.0

Thanks

**Comment by OGCS-User** [comment]
Hi, it's me again. It seems that this only happens with invites received. Putting a date in outlook directly seems to work fine.

**Comment by OGCS-User** [comment]
And again me: as long as the received invite isn't accepted, everything works fine and the entry is being synchronized and stays. As soon as it is being accepted in Outlook during the next synch cycle OGCS deletes the entry in the Google calendar. And one cycle later is disappears in Outlook as ther isn't an entry in Google anymore.

**Comment by phw198** [comment]
@amig500 
> About the logging level, I obviously never changed anything. 

To change the logging level: Settings > Application Behaviour > Logging > Level > Pick `Debug` from the dropdown.

Please then [carry out the steps in your previous post](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1148#issuecomment-761578962) one again and then upload your `OGcalsync.log` file

**Comment by phw198** [comment]
@OGCS-User It sounds like your issue is different from the OP as they state the Outlook item is self created and _never_ gets to Google. Could you create a new issue, reproduce the problem and upload your `OGcalsync.log` file also?

If you can also answer these questions on your newly created issue:
What account is being used in Outlook? A work Exchange account or something else? Where is the meeting invite coming from, for example, another Exchange user? Are you choosing to "Only sync invites I've responded to"?

**Comment by amig500** [comment]
@phw198 Thanks. Here is the log file:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5873803/OGcalsync.log)

**Comment by phw198** [comment]
There's no evidence in your log file of what you're reporting - nothing is being requested for deletion in Outlook:
```
2021-01-26 15:13:02,148 INFO  6 OutlookGoogleCalendarSync.Console [281] -  Syncing Outlook ← Google
2021-01-26 15:13:02,412 DEBUG  6 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1285] -  Comparing Google events to Outlook items...
2021-01-26 15:13:02,412 DEBUG  6 OutlookGoogleCalendarSync.Console [279] -  Matching calendar items...
2021-01-26 15:13:16,293 INFO  6 OutlookGoogleCalendarSync.Console [281] -  0 Outlook calendar entries to be deleted.
2021-01-26 15:13:16,293 INFO  6 OutlookGoogleCalendarSync.Console [281] -  0 Outlook calendar entries to be created.
2021-01-26 15:13:16,293 INFO  6 OutlookGoogleCalendarSync.Console [281] -  65 calendar entries to be compared.
```
I'm guessing you didn't actually [follow your owns step](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1148#issuecomment-761578962) to reproduce the problem after increasing logging to `DEBUG`?

**Comment by amig500** [comment]
Lets try another one. I had to change the settings to O->C to avoid constant message boxes requesting deletion.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5898774/OGcalsync.log)
Do you see it now?

**Comment by phw198** [comment]
OK, yes I can now see `09/02/2021 16:00 "élève prépa Alexis GUEY sur discord"` is popping up for deletion in Outlook, when it would seem that it should indeed get synced to Google instead.

Then as soon as you switched from O<->G to O->G they correct got created in Google. Will take a deeper look, thanks :+1:

**Comment by phw198** [comment]
No, I'm still not convinced the problem exists within the period of your log file anyway.

When `09/02/2021 16:00 => "élève prépa Alexis GUEY sur discord"` gets processed and created in Google under O->G it shows that the Outlook item was already synced to Google on 14/01/2021 22:32:00. If this was the case and then it was deleted from Google, it would be expected under O<->G for it to then be deleted from Outlook.

Please could you check in your [Google calendar bin](https://calendar.google.com/calendar/u/0/r/trash) (make sure you select the correct calendar on the left `google@san-****.net`) for `09/02/2021 16:00 => "élève prépa Alexis GUEY sur discord"` being deleted at some point after 14/01/2021 22:32:00?

Actually, could you confirm if you have always been syncing to the same Google calendar, or whether you changed to a different one at some point recently?

**Comment by amig500** [comment]
Thanks for closing... except the issue is not solved yet.
