### ISSUE TITLE
Sync is triggered even though I haven't responded to the invitation yet

### ISSUE THREAD

**Issue by 1lomeno3** [phw198/OutlookGoogleCalendarSync#1149]
**OGCS Version**: v2.8.5.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I have following options "Push outlook changes immediately" and "Only sync invites I've responded to" checked on, however the sync is triggered immediately once I received an invitation in outlook and does not reflect that I haven't responded to that.

**Comment by phw198** [comment]
That sounds like expected behaviour. The "Only sync invites I've responded to" means that until you have responded **they won't get created in Google** - it doesn't mean that it won't trigger a sync.

OGCS is just looking for change in your calendar and it doesn't know what that change is until a sync runs, at which point it can determine if the change was the arrival of an invite and whether you have responded yet or not.

**Comment by 1lomeno3** [comment]
Makes sense, thanks, we can close it...
