### ISSUE TITLE
Push Outlook to Google not running

### ISSUE THREAD

**Issue by mattterry13** [phw198/OutlookGoogleCalendarSync#1172]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Push Outlook to Google not syncing. I went in today and the last sync was over a month ago. Settings are set to push, but nothing new has updated since I manually sync'd last time. Not sure if I'm missing something?

**Steps to Reproduce the Issue**  
1. Add new event, not sync
1. 

**Any other information**  
No other info

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) having first reproduced the problem you are reporting.
