### ISSUE TITLE
Application unexpectedly terminated! Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by larrychrzan** [phw198/OutlookGoogleCalendarSync#1185]
Installed beta-stable version on a new computer to sync with Outlook 2007 as I had been doing on old computer.
Had to uninstall Office 2007 and reinstall, the OGCS would not work. Uninstalled OGCS, tried both beta and latest alpha, but OGCS will not install now.
Error box pops up saying:
Application unexpectedly terminated!
Object reference not set to an instance of an object. 
Any help would be appreciated. Thanks!

![OGCS-Error-Capture](https://user-images.githubusercontent.com/80033397/109938129-abdc8e00-7c9d-11eb-8b2b-dd6368c4f13d.jpg)

**Comment by McBluna** [comment]
![Screenshot 2021-03-05 075426](https://user-images.githubusercontent.com/32108408/110078569-38637b00-7d88-11eb-9e1e-02ff09883674.jpg)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6088641/OGcalsync.log)

**Comment by larrychrzan** [comment]
I tried to install and run OGCS again today and got a new message (shown here) that says to repair office. So I uninstalled OGCS and then ran the repair on Office 2007. Rebooted. Then I tried to reinstall OGCS and got this same error message. Any suggestions?
![OGCS-Error-Capture-2021-03-12](https://user-images.githubusercontent.com/80033397/110942871-7290c780-8308-11eb-816b-19920b7b99ea.jpg)

**Comment by phw198** [comment]
@McBluna `0x8002802B` is also investigated on #999 - see [my comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/999#issuecomment-731769324) that might be worth checking.

@larrychrzan The wiki doesn't just say repair office, it says [registry fixes are required](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered) and potentially a reinstall of Office. Reinstalling OGCS won't achieve anything as the issue is with a corrupted install of Office.

**Comment by larrychrzan** [comment]
I deleted one registry entry for the wrong version of Office and it worked after that. Thank you for your help!

**Comment by larrychrzan** [comment]
I deleted one registry entry for the wrong version of Office and it worked after that. Thank you for your help!
