### ISSUE TITLE
Invalid start time. [400=BadRequest]

### ISSUE THREAD

**Issue by coen1111** [phw198/OutlookGoogleCalendarSync#1196]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0.0
**Edition**: Portable  
**Sync Direction**: O->G 

**Bug Description**  
During updating an event, from someone else, an error Invalid start time. [400=BadRequest] pops up.
![image](https://user-images.githubusercontent.com/3091129/112595240-6c234500-8e0a-11eb-893b-59503500c036.png)

**Steps to Reproduce the Issue**  
1. Sync
2. Error

**Any other information**  
Any additional information that may help troubleshoot the issue.  
[Previous issue with the same error](https://github.com/phw198/OutlookGoogleCalendarSync/issues/837)
[Possible cause](https://stackoverflow.com/questions/15926676/google-calendar-api-bad-request-400-event-over-developer-console)

:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
