### ISSUE TITLE
Issue regarding opening the app

### ISSUE THREAD

**Issue by 55p55** [phw198/OutlookGoogleCalendarSync#1197]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0 beta 
**Installed or Portable**: Installed

**Problem Description**  
\<The app was working fine until I faced a problem with outlook and I reset it. Then OGCS stopped working, and I reinstalled it but it's not working. Whenever I open it it opens the chrome website but I can't see the settings of the app. It was just showing the splash screen and not opening the app.>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
