### ISSUE TITLE
Synced calendar entry, is not removed when event is deleted/removed from source calendar

### ISSUE THREAD

**Issue by dcmarimba** [phw198/OutlookGoogleCalendarSync#1200]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0
**Edition**: Installed
**Sync Direction**:  O->G

**Bug Description**  
A synced event to my Google calendar, from Outlook is not removed/moved when the source calendar entry is removed or moved. The log does not state that there is anything to update or remove. The event in question here is "Azure Training (DCo)"

**Steps to Reproduce the Issue**  
1. Synced event is not updated or removed once it has been updated or removed

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6244880/OGcalsync.log)

**Comment by objarni** [comment]
I think I have a variation of this: the event has been manually deleted by me in Google Calendar, then I get popups/errors about it being deleted when OGCS tries to do it too. Basically I think I might have deleted the event in both calendars, but quicker than OGCS had a chance to do it. So:

1. Create event in one calendar (I'm not sure if it matters in which the source event was created)
2. Let it sync with OGCS
3. Delete the event in Google Calendar
4. Let OGCS try to sync
5. Try syncing, watch it fail

**Comment by objarni** [comment]
![image](https://user-images.githubusercontent.com/68198/114404443-fd820d80-9ba5-11eb-9971-6f6c68594316.png)

This is the popup I get in OGCS.

**Comment by objarni** [comment]
And this is how it looks in the OGCS log.

![image](https://user-images.githubusercontent.com/68198/114404522-0d015680-9ba6-11eb-8b57-743834b5bdc4.png)

**Comment by objarni** [comment]
My expectation is to not have to answer "yes" multiple times, I just want the software to do it's best attempt, and the tell me of any errors / operations that failed in the log (and possibly in a 'amalgamated' popup just after sync has been done). Also, I think it is unclear why this is a problem at all, since the event is gone? Maybe just ignore the case of trying to delete an event failing (since it might have been manually deleted anyway... idempotent and all that jazz..)

**Comment by phw198** [comment]
@objarni Duplicate of #1060 and already fixed in v2.8.6.

**Comment by objarni** [comment]
Downloaded  2.8.6 alpha version, worked great! Thanks!

**Comment by phw198** [comment]
@daniluvsuall I think the main issue with your "Azure Training (DCo)" appointment is that the Google event has been modified more recently than Outlook and therefore OGCS isn't bothering to compare it. There is a slight side-issue here though, where the Outlook IDs held in the Google synced item have changed (due to the organiser changing the time), but the IDs as held in Google are not getting saved.

With the below hotfix could you:
1. Apply the hotfix and make sure OGCS is logged at `DEBUG` level at least.
2. Run two manual syncs consecutively.
2. Once they are complete, open the "Azure Training" Outlook item and make a faux edit (eg add and remove a space from the title, then save and close).
3. Perform a final manual sync
4. Upload your logfile

:package: [Hotfix v2.8.6.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6332415/v2.8.6.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by phw198** [comment]
@daniluvsuall Any luck with v2.8.6.10?

**Comment by dcmarimba** [comment]
Never got the notification 😄 but it was fixed thanks
