### ISSUE TITLE
Google appointments not showing in Outlook

### ISSUE THREAD

**Issue by mvaede** [phw198/OutlookGoogleCalendarSync#1206]
Adding appointments in google, doesn't show up in out in Outlook
- adding on the mobile app of google
- Show up on the PC ersion
Go a bidirectional sync in place

??

**Comment by phw198** [comment]
?? indeed....

In order to receive support, as a minimum you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
