### ISSUE TITLE
Cannot stop deleting a birthday

### ISSUE THREAD

**Issue by LungoLeglungo** [phw198/OutlookGoogleCalendarSync#1239]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by LungoLeglungo** [comment]
Hello Paul

i am not the best in (technical) english and hope, to have you understood correctly

1.
2. 

Problem, i can’t resolve. i deletet the entry several times on outlook   and reccreatet it. i receiv the  message constantli. i have other birthday entrys, that dont produce the error.

**Comment by phw198** [comment]
You may need to view my previous post actually on GitHub and follow the links etc to understand them fully.

It may be worth reading though this article about [fixing unwanted deletions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

Without your `OGcalsync.log`, however, I cannot assist further.
