### ISSUE TITLE
Max Reminders? How many?

### ISSUE THREAD

**Issue by SoCalDude** [phw198/OutlookGoogleCalendarSync#1248]
**Are you already using OGCS?**
2.8.7.0

**Describe the question you have**
I have a recurring event, originated in Google Calendar for every two weeks with reminders (multiple reminders for each occurrence). During sync'ing, I get this error (see image).  I originally had it to never end, and then I reduced it to 60 occurrences. The sync was successful. However, the next scheduled sync failed with the same message. I reduced the occurrences to 26, and it sync'ed successfully. Now, on the latest sync, it errored-out again.

What can I do to correct this behavior? 

Error Screenshot:
![ogcs-error-screenshot](https://user-images.githubusercontent.com/7506541/125869592-7d99da43-efdc-4030-b8e2-516a914aa641.png)

OGCS Log:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6826708/OGcalsync.log)

**Comment by phw198** [comment]
It would be helpful if you could increase your logging level to `DEBUG` instead of `FAIL`, so I can see a bit more context.

Also
* What are the OGCS settings for syncing notifications
* What are the notifications set against the Google event
* What are the default notifications set for the entire Google calendar
