### ISSUE TITLE
Change time of recurrence series using "This and following events" leads to deletion

### ISSUE THREAD

**Issue by danji77** [phw198/OutlookGoogleCalendarSync#1269]
**OGCS Version**: v2.9.0.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
When shifting the start/end time of a recurring event series in GCal, changing only "This and following events", OGCS will eventually delete all events in the series after 3 syncs.

**Steps to Reproduce the Issue**  
1. Create "Test" event in GCal Time 20-21, recurrence weekly, no end date.

2. Perform sync. Observed behavior: Event series syncs correctly to Outlook.

3. Modify "This and following events" 20:30 to 21:30 two weeks later in GCal. I.e. first two entries remain at 20-21, third week and after 20:30 to 21:30.

4. Perform sync. Observed behavior: Deleted "Test" from Gcal (first two 20-21 deleted, 20:30 to 21:30 remain from week 3 and forward). Outlook recurrence changed to 2 occurences (i.e. first two remain 20-21, rest is gone).

At this stage I have the first two original events in Outlook. Opposite in Google I have only the modified event from 3rd week and forward.

5. Perform sync. Observed behavior: Updated parameters on "Test" to match Outlook (so only the first two, updated week 3 and forward are gone). Deleted "Test" from Outlook.

6. Perform sync. Observed behavior: Deleted "Test" from GCal.

**Any other information**  
The issue is fullly reproducable. Same behavior every time.

:paperclip: Attached my `OGcalsync.log` file containing the four syncs above.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7055727/OGcalsync.log)

**Comment by phw198** [comment]
This was a tricky one - turns out when changing "this and following events", Google
1. Duplicates the original series, including OGCS metadata (this is the problem)
2. Shortens the original series
3. Starts the new series from the first event of "**this** and following events"

:package: This should now be resolved with [v2.9.0.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7072843/v2.9.0.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) where the duplicated metadata is now removed.

Please let me know how it goes.

**Comment by danji77** [comment]
Resolution confirmed. Steps 1 through 4 performed, and the resulting behavior is as expected. Recurring event correctly synchronized in GCal and Outlook. Performed 2nd sync which performed no additional updates.

Please note step 2, first sync failed due to unknown reason (log attached). 2nd try completed succesfully, however, I observed at one point in the initialization of the sync, the Output windows became completely blank for approx 10 seconds, then the full output reappeared and continued.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7076304/OGcalsync.log)

**Comment by danji77** [comment]
Thank you for the excellent support. Fast and accurate. I am happiliy making an additional donation. Do I close the issue or await further feedback?

**Comment by phw198** [comment]
Thanks @danji77 - that failed sync looks to be due to an Outlook item being deleted (I assume manually) in the middle of the sync, so kind of expected in that situation.

The output window does "glitch" sometimes, though I've not seen it do that for 10 seconds - normally for less than a second and barely noticeable.
