### ISSUE TITLE
Recurring event is not being synced

### ISSUE THREAD

**Issue by artisticcheese** [phw198/OutlookGoogleCalendarSync#1285]
**OGCS Version**: 2.9.0
**Edition**: Installed 
**Sync Direction**: O->G 

**Bug Description**  
Recurring event is not being sent to Google

**Steps to Reproduce the Issue**  
Sync does not sync eent

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7164823/OGcalsync.log)

**Comment by swaldman3** [comment]
I'm seeing the same. Have tried both an all-day event and a timed one. Have tried full sync to no avail.

The problem is not related to the "only syncing invites you responded to" log note - the recurring event in question is one I created, and its name is not mentioned in the log at all.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7168329/OGcalsync.log)

 Happy to help with investigation if there is anything useful I can try.

**Comment by phw198** [comment]
In Settings > Application Behaviour, please turn on CSV exports and then confirm whether the missing appointment is present in `outlook_appointments.csv`.

If not, please turn logging level up to `FINE` and then follow guidance to see if [changing your date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) helps at all.

Please re-upload log files if still no joy and provide details on the recurring series pattern (start date, frequency, number of occurrences etc etc).

**Comment by 8restcoop8** [comment]
This is happening to me as well.  The event appears in the .csv file.

**Comment by phw198** [comment]
@8restcoop8 As per my previous post

> Please re-upload log files if still no joy and provide details on the recurring series pattern (start date, frequency, number of occurrences etc etc).

**Comment by 8restcoop8** [comment]
@phw198 
"Occurs every Thursday effective 2021-10-14 until 2021-10-28 from 1:00 PM to 1:30 PM"

None of the events appeared on my Google Calendar.  No issues with any other events.

Log file (not logged on FINE as the recurring events ended yesterday):  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7442972/OGcalsync.log)

**Comment by phw198** [comment]
@8restcoop8 You have logging turned off, so the logfile is useless (aside from confirming you are running v2.9.1). The log needs to capture at least one sync at `DEBUG` level.

**Comment by 8restcoop8** [comment]
@phw198 I now have a new recurring event and this one is syncing properly, so I will retract my comment.  Maybe it was something odd about the other events in particular.  Thanks for the help.

**Comment by krzasteka** [comment]
I was having a similar issue I kept seeing logs similar to:
`2021-09-14 14:51:15,624 WARN  21 OutlookGoogleCalendarSync.Recurrence [521] -  Failed to find master Google event for: 7/30/2021 8:00 AM (R) => "Avasek Technical Huddle"` 
The sync (O -> G) kept failing with `The given key was not present in the dictionary.`
I think these failures are happening when there is a `Date range` set. Zeroing out the past and future solved the issue for me. 
I have not looked at the code, but I think the issue happens because the parent recurring event was not imported into Google Calendar, zeroing out the date ranges imports everything? I'm not sure why setting future to `>0` (I only tried the default 60) reproduces the issue. Changing the past date to 1 had no effect because I'm speculating the event already exists in google calendar, but if I wiped out the imported events, I'm pretty sure it would cause it to break. 
@phw198 thank you for your hard work and such a great tool! I'll try to contribute.

**Comment by 8restcoop8** [comment]
@phw198 It has happened again.  Fine log is attached.  
The problem appears to be here:
```
2021-11-10 08:48:23,355 DEBUG  7 OutlookGoogleCalendarSync.Recurrence [587] -  2021-11-08 11:00 AM (R) => "daily scrum"
2021-11-10 08:48:23,355 DEBUG  7 OutlookGoogleCalendarSync.Recurrence [588] -  This is a recurring appointment with 1 exceptions that will now be iteratively compared.
2021-11-10 08:48:23,355 WARN  7 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance has become inaccessible, probably due to caching
2021-11-10 08:48:23,370 FAIL  7 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2021-11-10 08:48:23,370 FAIL  7 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xB1704005,-1318043643; Location: get_AppointmentItem() in <Unknown File>
2021-11-10 08:48:23,370 WARN  7 OutlookGoogleCalendarSync.OGCSexception [18] -  This Outlook recurrence instance has become inaccessible, probably due to caching
2021-11-10 08:48:23,370 FAIL  7 OutlookGoogleCalendarSync.OGCSexception [21] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2021-11-10 08:48:23,370 FAIL  7 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xBBC04005,-1145028603; Location: get_AppointmentItem() in <Unknown File>
```

**Comment by phw198** [comment]
@8restcoop8 Does that error still happen after you have completely closed down Outlook and OGCS and restarted them?

@krzasteka Are you able to provide more of your logfile so I can see the context of `The given key was not present in the dictionary.`?

**Comment by 8restcoop8** [comment]
@phw198 it seems good now.  Sorry if my confusion added to the confusion here!

**Comment by 8restcoop8** [comment]
Hello @phw198, having trouble again with a number of recurring events that have exceptions.  It seems to do with whenver a recurring event has some exceptions.  Detailed log attached.
Thank you.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7883186/OGcalsync.log)

**Comment by phw198** [comment]
@8restcoop8 You have a number of errors from Outlook that say `You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.` - can you confirm if these stop appearing if you fully close Outlook, reopen and then try and sync again?

Google seems to indicate the issue is actually with a corrupted timezone field in the recurring series occurrence, however.

There also seems to be a [known bug with Exchange 2013 and using an iOS device](https://support.microsoft.com/en-us/topic/fix-error-message-occurs-in-outlook-after-you-change-a-single-instance-of-a-recurring-meeting-by-using-an-ios-device-5414597f-4877-b089-929b-2dae8f740c9a) - might this match your case?

Ultimately, whenever this happens, OGCS is currently assuming the occurrence is deleted, and then deletes it in Google. This is probably incorrect behaviour and instead it should just leave it and flag a warning the item is not properly syncing (due to Outlook). The workaround seems to be to request the meeting organiser re-invite you!

**Comment by 8restcoop8** [comment]
@phw198 Closing/reopening/resetting computer does not resolve the issue.  I do not use or have any iOS devices so that's not the issue.  I guess your final paragraph is probably correct!

**Comment by phw198** [comment]
My reading of it was more that the organiser of the meeting may have created an exception to the recurring series on their iPhone, which corrupts the timezone information for that exception. Either way, I'll change OGCS to not remove the exception from Google in this situation.

**Comment by phw198** [comment]
:package: [v2.9.3.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8147363/v2.9.3.1.zip) should now not delete occurrences of a series that have been inaccessible ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Note, if they have already been deleted, this will not restore them - the only way of achieving that is to delete the whole series in Google and let OGCS recreate it - but only do this with one-way O->G sync configured!

**Comment by 8restcoop8** [comment]
@phw198 I can't get it to work for me with the hotfix applied - in fact I get an error pop-up every time it tries to sync now.  This seems to be the relevant portion of the log:
[log excerpt.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8154604/log.excerpt.txt)

I have tried deleting the whole series in Google to no avail.  It is also possible I am misunderstanding something!!

**Comment by phw198** [comment]
No, you weren't misunderstanding anything - I underestimated the size of the fix!

:package: Please could you try again with [hotfix v2.9.3.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8240303/v2.9.3.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by 8restcoop8** [comment]
Better (I don't get a popup error non-stop anymore), but I do have some exceptions to recurring events that are not showing up in GCal.  It's actually one event in particular that was initially created by someone else but is often rescheduled on a week-to-week basis by me (if that helps).  I do think other events with exceptions are working now where they weren't on older versions.

[log excerpt.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8253741/log.excerpt.txt)

**Comment by phw198** [comment]
The one event in a particular series - what happens with one-way sync O->G if you delete the whole series in Google and then get OGCS to recreate the entire series? Is the event still missing, or does it disappear at some point later? Would be good if you could send me the log just after it disappears.

Also, if you are not the organiser, what do you mean exactly by "rescheduled...by me"? Are you declining the occurrence in Outlook and suggesting a new time that the organiser then accepts? In this situation I think OGCS will delete that event (as you declined it) and then it can't be automatically reinstated when the reschedule is accepted.

Meanwhile, I think I will take the fix so far into the next release as it's improving the sync behaviour.
