### ISSUE TITLE
Google -> Outlook sync  "Corrupted item(s) with no start/end date exist in your Outlook calendar before a sync can run" - v.2.9.1.0

### ISSUE THREAD

**Issue by FlorianOtel** [phw198/OutlookGoogleCalendarSync#1306]
Hello, 

While it worked fine in the past, Google -> Outlook calendar sync has stopped working. 

The error I get is this (literal entry from the log):

`
2021-10-01 10:43:29,222 DEBUG  21 OutlookGoogleCalendarSync.Console [226] -  Corrupted item(s) with no start/end date exist in your Outlook calendar that need fixing or removing before a sync can run.<br/>Switch the calendar folder to <i>List View</i>, sort by date and look for entries with no start and/or end dat
`

I have looked in my Outlook but could not find any such entries. I have also limited the sync range to one day in the past / future  but to no avail -- error persists. 

I have updated to the latest version - v2.9.1.0 but the issue is the same as in v2.9.0.  As I wrote previously, it worked fine before. 

Please find attached the log file. 

Kind TIA for prompt help, 

/Florian

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7265626/OGcalsync.log)

**Comment by phw198** [comment]
There's not much more advice I can give; Outlook itself is unable to filter your calendar down to a date range because you have items in your calendar with no dates. This isn't OGCS code that's failing, but Outlook itself.

I'm pretty sure another user was able to identify it by looking at the calendar in List View, as suggested. Perhaps you could:
* File > Import/Export > Export to a file > CSV
* Choose the calendar "Folder"
* Save to a file

Then search through that file looking for something with a bad start and/or end date.
