### ISSUE TITLE
Google sends Updated intitation to everyone

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#131]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/653366" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/Automat" target="_blank">Automat</a></strong> wrote at 2016-04-08 09:57:</p><div class="markDownOutput ">I could not find this issue reported. <br>
<br>
For one recurring meeting, that is not created by me, google is sending an updated invitation to everyone 15 mins Before the meeting, same time I get the notification. It started last week. probably after the organizer changed one of the meetings in the series.
<br>
<br>
I upgraded to 2.2 today but the meeting can have been synced with an earlier version.
<br>
Outlook -&gt; google sync only. <br>
<br>
352<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2016-04-08 10:22:</p><div class="markDownOutput ">Sounds similar to previous issues related to a Google bug which randomly spams all recipients for events. Seeing as this is only affecting a single event for you, have you tried deleting the Google event and letting OGCS recreate it?
<br>
<br>
If that fails, unfortunately, you may need to stop syncing meeting attendees....<br>
</div></div>

**Comment by meliwu** [comment]
I have done what you said above and it was still happening every couple of weeks  (always on the day of the meeting). I stopped syncing meeting attendees and I have deleted that event from my calendar. Why is this still happening?

**Comment by phw198** [comment]
Is this only happening on 1 appointment? Is the appointment recurring? Does it recur once every 2 weeks? Are emails sent 15 minutes before each occurrence? Do you have a reminder set on the appointment? Is it set to 15 mins? Are you syncing reminders? You say you deleted the appointment in Google? Has OGCS then recreated it? Without attendees? Have you checked in the web view of Google calendar whether that appointment has email reminders set? The email that people get, what email address does it come from? What does it say? A reminder or that the appointment has been rescheduled? Is the account of the meeting organiser a Google account?

**Comment by meliwu** [comment]
Happens for just one appointment. Appointment is recurring every week. emails sent before the event but not 15 minutes. No reminder set on that appointment. Reminder is set on the outlook event for 10 minutes before. I am not syncing reminders. I deleted the appointment in google completely and OGCS was not able to sync that far back since we had move offices and there was another new event made that would account for the move. The event that keeps sending out the invitation is the old event.. I have checked web and mobile view to see if there are email reminders had been set but there isn't. 
The email comes from my google email and is sent to my work email. There are two emails always sent. 

1. Doc 1 (seen in my work email)
[Updated Invitation FW Cupid Change Review @ Weekly from 11am to 12pm on Wednes.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/1076303/Updated.Invitation.FW.Cupid.Change.Review.Weekly.from.11am.to.12pm.on.Wednes.docx)

2. Doc 2 (seen in my work email)
[Updated Invitation FW Cupid Change Review @ Weekly from 11am to 12pm on Wednesday (CDT) (Cardiology Team).docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/1076311/Updated.Invitation.FW.Cupid.Change.Review.Weekly.from.11am.to.12pm.on.Wednesday.CDT.Cardiology.Team.docx)

3. Image 3 (seen in my google email)- these are declines that are sent from my colleagues 
![2017-06-14 21_17_00-trash - mlissa wu gmail com - gmail](https://user-images.githubusercontent.com/3059189/27161078-e8c14f94-5146-11e7-8957-10e8400bb191.jpg)

**Comment by phw198** [comment]
OK, very strange indeed! 

* I assume if you click on the event link in the email that it says the event doesn't exist for you? https://www.google.com/calendar/event?action=VIEW&eid=ZGhyZTZoc2RrNTF1MWtsNXIyaWQ1dnZmNm8gMmNhcmRpb2xvZ3l0ZWFtQGVwaWMuY29t&tok=MTkjbWxpc3NhLnd1QGdtYWlsLmNvbTZmMzIyNTU5N2YyNmUzZDA3OTk4Y2RiZjg3MjAwYjVmMGI2NWQ5MTY&ctz=America/Chicago&hl=en
* If you go into the _General_ settings of your Google calendar in the web view, what is your setting for "Automatically add invitations to my calendar"?
* In the settings for the _Cardiology Team_ calendar, under "Edit Notifications", do you have any of the boxes checked for "Choose how you'd like to be kept up to date:"
* Under "Calendar Details", what's the setting for "Auto-accept invitations"?
* On the same screen, if you "Export the calendar" can you find any reference to the event in the .ics file?
* On the "Bin" tab, is the event here? Might be worth completely emptying the bin?
* Final option would be to delete the entire calendar and create a new one to sync to?!

I can't really see why any of these settings would cause the attendees of the event to be getting updates though. It really does feel like a bug on Google's end. You could try sending feedback to Google and see if they can investigate deeper...

**Comment by phw198** [comment]
Any feedback on the points I suggested in my previous post?

:link:  _[Linking to #197 which will work around this problem]_

**Comment by AndyZEvans** [comment]
Google Calendar is known to sometimes keep sending reminders to everyone for events that have been deleted long ago.

**Comment by phw198** [comment]
Thanks @AndyZEvans. @meliwu is clearly not interested in investigating further so I'll close the ticket out. Enhancement #197 is now almost ready for release too, which works around Google's problem.
