### ISSUE TITLE
New appointments created in Outlook 2021 not synced

### ISSUE THREAD

**Issue by udiudiudiudi** [phw198/OutlookGoogleCalendarSync#1312]
It stoped syncing my default calendar items to google calendar, since I upgraded to outlook 2021

2021-10-09 10:45:53,891 ERROR  1 OutlookGoogleCalendarSync.OutlookOgcs.Factory [148] -  Could not determine exact Outlook version with codebase v16.

When I do kernel ost view it does show on my ost the entries after I upgraded - https://i.postimg.cc/ydFF8czb/Untitled.png

however when inside the outlook google calendar sync, when I do test, it only find 4 items, which were done prior to the upgrade of outlook

you can test download the outlook 2021 at https://filecr.com/windows/windows-10-with-office-2021/?id=272772774806

my regional settings are gregorian type calendar and I validated it via windows regional settings

**Comment by udiudiudiudi** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7315298/OGcalsync.log)

**Comment by phw198** [comment]
Your log file doesn't evidence this.

```
2021-10-09 11:04:32,722 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [1121] -  Testing the Outlook filter string.
2021-10-09 11:04:32,999 INFO  1 OutlookGoogleCalendarSync.Forms.Main [1128] -  The format 'yyyy-MM-dd hh:mm tt' returns 65 calendar items within the date range 08/10/2021 and 09/12/2021
2021-10-09 11:04:55,520 INFO  1 OutlookGoogleCalendarSync.Settings [817] -  Saving settings.
...
2021-10-09 11:04:55,549 INFO  1 OutlookGoogleCalendarSync.Settings [487] -    Filter String: yyyy-MM-dd hh:mm tt
...
2021-10-09 11:04:59,088 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Sync version: 2.9.1.0
2021-10-09 11:04:59,089 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Sync started at 09/10/2021 11:04:58
2021-10-09 11:04:59,089 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Syncing from 08/10/2021 to 09/12/2021
2021-10-09 11:04:59,090 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Outlook → Google
2021-10-09 11:04:59,427 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Finding Calendar Entries
2021-10-09 11:04:59,568 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Scanning Outlook calendar...
2021-10-09 11:05:00,146 INFO  10 OutlookGoogleCalendarSync.Console [282] -  65 Outlook calendar entries found.
...
2021-10-09 11:05:17,654 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Outlook 65, Google 5
2021-10-09 11:05:17,996 DEBUG  10 OutlookGoogleCalendarSync.Sync.Engine [563] -  Synchronising from Outlook to Google.
2021-10-09 11:05:17,996 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1135] -  Comparing Outlook items to Google events...
2021-10-09 11:05:17,997 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Matching calendar items...
2021-10-09 11:05:19,417 WARN  10 OutlookGoogleCalendarSync.Console [274] -  1 Google items would have been deleted, but you have deletions disabled.
2021-10-09 11:05:19,491 INFO  10 OutlookGoogleCalendarSync.Console [282] -  0 Google calendar entries to be deleted.
2021-10-09 11:05:19,492 INFO  10 OutlookGoogleCalendarSync.Console [282] -  61 Google calendar entries to be created.
2021-10-09 11:05:19,492 INFO  10 OutlookGoogleCalendarSync.Console [282] -  4 calendar entries to be compared.
2021-10-09 11:05:19,754 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Creating 61 Google calendar entries
...
```
Looks to be functioning fine.

**Comment by udiudiudiudi** [comment]
the thing you show relates to when I changed the regional time/date options to generic
and those extra 61 calendar meetings are prior to 16/9 which is when I upgraded, so they are not upcoming

now I have meetings for the upcoming week, which are not recorded and the software doesn't find - although I have shown you that with kernel ost viewer, they are showing, 
if you take a look at the latest log date/time that you received - you will see it shows only 4 which are reoccurring birthdays, its not meetings

what else can I send you to debug this?

did you try to install OUTLOOK 2021 on your end and test?

When I first loaded the software, it showed me an error log and ask to submit it to you, about the software module not supporting my outlook version

**Comment by udiudiudiudi** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7315987/OGcalsync.log)

**Comment by phw198** [comment]
The error about "not determining the exact Outlook version" isn't pertinent to this problem.

I think we can safely confirm that the Outlook date format of `g` isn't correct for you, so let's stick to `yyyy-MM-dd hh:mm tt`.

How many items is OGCS failing to find since the upgrade to 2021? One is being excluded due to only syncing invites you've responded to.

Could you
* increase your logging to `FINE` and turn on CSV file creation
* test the date format (using yyyy-MM-dd hh:mm tt)
* create a new item in Outlook 2021
* test the date format again, with the same format - has the number of items increased by 1?
* perform a sync
* Check if the new item is present in `outlook_appointments.csv`
* upload log file

Thanks!

**Comment by udiudiudiudi** [comment]
I tested all the time options from here
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/az4se3k1(v=vs.90)?redirectedfrom=MSDN
, non brought me more than 4 calendar meetings, which are the same ones I had
+ I have created one already for Wednesday, so it means it still missing

this is my regional settings
![Untitled](https://user-images.githubusercontent.com/36422655/136670339-2340ed7e-284f-4c1b-bdc0-6caf4199d89e.png)
:

in addition, when I hover a meeting, this is what I see
![Untitled1](https://user-images.githubusercontent.com/36422655/136670381-9fa5d70d-bdc1-41b4-bffa-86a44e7a897a.png)

also here I changed to fine the debug, and here is it


[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7316191/OGcalsync.log)


also in the csv I don't see the new meeting I scheduled


[outlook_appointments.csv](https://github.com/phw198/OutlookGoogleCalendarSync/files/7316194/outlook_appointments.csv)

**Comment by phw198** [comment]
Only 2 hours you already tested `yyyy-MM-dd hh:mm tt` and we know that works.
```
2021-10-09 19:16:06,952 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [1121] -  Testing the Outlook filter string.
2021-10-09 19:16:07,131 INFO  1 OutlookGoogleCalendarSync.Forms.Main [1128] -  The format 'yyyy-MM-dd hh:mm tt' returns 65 calendar items within the date range 08/10/2021 and 09/12/2021
```
Have you also tried with `dd-MMM-yyyy HH:mm`? The other formats are only returning the 4 birthday recurring events because they span a very wide date range.

Please repeat the steps again making sure the format `yyyy-MM-dd hh:mm tt` is being used, creating a new Outlook appointment in between tests. 

Thanks.

**Comment by udiudiudiudi** [comment]
yyyy-MM-dd hh:mm tt , brings the 65 past events
and g brings only 4 events

we are missing the date format that outlook 2021 is using,
maybe its best that you install it on your end (I sent you the filecr link)

so you can edit the ost file and see the format that outlook 2021 brought in, because surely its what we are missing here.

by the way when you test this "2021-10-09 19:16:07,131 INFO  1 OutlookGoogleCalendarSync.Forms.Main [1128] -  The format 'yyyy-MM-dd hh:mm tt' returns 65 calendar items within the date range 08/10/2021 and 09/12/2021"

it brings results from july/august up until 16-9-2021 which is when I upgraded.

**Comment by udiudiudiudi** [comment]
i want to add that i use this software (I always used) to sync another calendar which is not the one that is default
http://www.pppindia.com/calendar-sync/

and they kept on working,

its just the default calendar which is related to your software that stoped syncing with google because your software doesn't recognize the new calendar
but as you also saw those calendar meetings do exist, because I saw them via kernel ost viewer

**Comment by phw198** [comment]
I'm still waiting for the [steps in this post](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1312#issuecomment-939338276) to be taken. 

I'm not entirely comfortable installing Windows and Outlook from an unverified iso - who knows what it could contain... :biohazard: 

Also,
* If you create a new Outlook calendar  and create an item, does OGCS see that? Is it only the default calendar it can't see the new items?
* If you point pppindia at the default folder, can that see the new items?

**Comment by udiudiudiudi** [comment]
1. I did the steps, and it was answered - https://github.com/phw198/OutlookGoogleCalendarSync/issues/1312#issuecomment-939343120

2. filecr is very known site to test verified software, eset didn't say anything about it having a virus

3. pppindia works well and shows all the calendar meetings

4. as for creating new calendar, I haven't tried yet

**Comment by udiudiudiudi** [comment]
2 MORE THINGS I NOTICED

1. when you click on shared calendar - it opens addressbook
2. when you click on alternative calendar - it says "unable to find calendar folder in alternative mailboxes" BUT in the dropdown it shows all the calendars
- in pppindia you can find & select all the calendars

**Comment by udiudiudiudi** [comment]
hello, any update please?

**Comment by phw198** [comment]
> 1. I did the steps, and it was answered - [New appointments created in Outlook 2021 not synced #1312 (comment)](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1312#issuecomment-939343120)
> 2. filecr is very known site to test verified software, eset didn't say anything about it having a virus
> 3. pppindia works well and shows all the calendar meetings
> 4. as for creating new calendar, I haven't tried yet

1. No, you did a whole bunch of things I didn't ask for, and none of the things I did. The log provided literally shows you trying every format of date _except_ the one I asked for. The CSV uploaded also only containing 4 items, not 65. 
I also asked you created a calendar item in between tests and you responded "I have created one already for Wednesday, so it means it still missing" - what you did prior to the test steps I requested are irrelevant.
2. Let's agree to disagree on the veracity of a website that hosts illegal software
3. It's closed source, so not much help troubleshooting OGCS
4. Why not? It couldn't be much simpler to create a new calendar folder in your Outlook account.

I'm really not sure why you're so keen to avoid following instructions. Let's try again:

1. increase your logging to FINE and turn on CSV file creation
2. test the date format (using `yyyy-MM-dd hh:mm tt`) Log file will show something like:
```
703 calendar items exist.
Filter string: [End] >= '08/10/2021 0:00' AND [Start] < '09/12/2021 0:00'
Filtered down to 65
```
3. create a new item in November in Outlook 2021 in the Default Mailbox and Default Calendar
4. test the date format again, with the same format - has the number of items increased by 1? Eg:
```
704 calendar items exist.
Filter string: [End] >= '08/10/2021 0:00' AND [Start] < '09/12/2021 0:00'
Filtered down to 65
```

> its just the default calendar which is related to your software that stoped syncing with google because your software doesn't recognize the new calendar.......when you click on alternative calendar - it says "unable to find calendar folder in alternative mailboxes" BUT in the dropdown it shows all the calendars

This is confusing - what do you mean by OGCS not recognising the **new** calendar? It apparently see the 65 items in the default calendar that were there prior to upgrade. Since upgrading, are your new calendar items going into a calendar that isn't the default calendar?

I would assume the calendars shown in the dropdown are related to the "Default mailbox", not the "Alternative mailbox"?

**Comment by udiudiudiudi** [comment]
i think you are going about this wrongly,
calendar sync by pppindia and gsyncit already support outlook 2021
