### ISSUE TITLE
Can't install on my pc on windows 11

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#1345]
I used OGSC by the past, but i got a hardware issue that made me rebuild my pc.

I'm reinstalling my apps, but i can't install OGCS. I have an error that states that oldvalue can't be null.

I don't understand th error.

Thanks for the help

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by ghost** [comment]
The issue doesn't appear anymore. The installation was successful this time.
