### ISSUE TITLE
Recovering deleted events

### ISSUE THREAD

**Issue by upcsfaculty** [phw198/OutlookGoogleCalendarSync#1347]
**Are you already using OGCS?**
Provide the version number. 
Yes, 2.9.0.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
Is it possible to recover events deleted by OGCS? There was some sort of error and then nearly my entire calendar for 2022 was deleted. This is an example of what I see repeated in the logs: 
```
2021-11-22 03:54:50,440 WARN  13 OutlookGoogleCalendarSync.Console [274] -  1/10/2022 1:35 PM (R) "CS 305"
2021-11-22 03:54:50,441 WARN  13 OutlookGoogleCalendarSync.Console [274] -  There is probem with this item - it will not be synced.
2021-11-22 03:54:50,441 WARN  13 OutlookGoogleCalendarSync.Console [274] -  Network problems are preventing connection to Microsoft Exchange.
2021-11-22 03:54:50,484 DEBUG  13 OutlookGoogleCalendarSync.Sync.Engine [353] -  Outlook object removed.
2021-11-22 03:54:50,514 WARN  13 OutlookGoogleCalendarSync.OGCSexception [18] -  Calendar item does not have a proper date range - cannot sync it. ExchangeMode=olCachedConnectedFull
2021-11-22 03:54:50,515 ERROR  13 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Network problems are preventing connection to Microsoft Exchange.
2021-11-22 03:54:50,515 ERROR  13 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xF7940115,-141295339; Location: get_EntryID() in <Unknown File>
```

**Comment by phw198** [comment]
This will be a continuation of #1143. 

Outlook never fails to surprise - it shows that you were running `olCachedConnectedFull` which should mean that you have all your Outlook items cached locally, so why it needs to connect to Exchange to get the start and end date of the appointment, I have no idea!

Nevertheless, we clearly need to stop OGCS deleting items when this happens - I think the best course of action is just to abort the sync and try again a bit later.

**Comment by phw198** [comment]
I'm guessing this will be hard to test as the issue is transient...

:package: However, OGCS should now just abort the sync with [v2.9.2.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7613936/v2.9.2.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

Regarding recovering the items that were deleted, you should be able to find them in your "Deleted Items" folder?

**Comment by oberoiUP** [comment]
I had looked for the events in the Deleted Items folder previously and didn't find them, but I was able to locate them upon a second look. That was a relief! 

I followed the directions for running the hotfix, but I am unable to get it to stay open. The first time I put it in the installation folder, it brings up a Windows security prompt, at which point I tell it to run anyway. I see the application pop up in Task Manager, but it closes immediately. I tried running it from the command line to see if any errors would show up, and there are none. Do I have to edit the settings.xml to get it to run?

**Comment by phw198** [comment]
Strange! Could you provide your `OGcalsync.log` file after OGCS closes/crashes?

**Comment by oberoiUP** [comment]
The log doesn't get updated. I attached my latest log, but it includes the behavior of the original buggy version. I tried running it again just to see if the problem was a one-off. Unfortunately it wasn't. It deleted my calendar entries for next year again. So the latest run of that application was at 17:47. I tried running the hotfix at 17:50 and, as you can see, there are no updates to the log after 17:47.

**Comment by phw198** [comment]
It looks like you said you are running v2.9.0? As [per instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix), the hotfix has to be applied over the latest alpha, so you need to upgrade to v2.9.2 first...

**Comment by oberoiUP** [comment]
Sorry. Thanks for pointing that out.

After a proper install and running it again, it still deleted the outlook entries I had restored. I'm not noticing any error messages in the log this time, but it says the thread was forcefully aborted. I'm going to try to manually create the outlook meetings again, rather than restoring them from my deleted folder, and then see if the sync works properly again.

**Comment by oberoiUP** [comment]
After recreating the deleted items from scratch, the sync has been working fine. Thanks for the patch!

**Comment by phw198** [comment]
Glad you worked around the issue :+1:  I can't be sure without a logfile, but it sounds like you probably had two-way sync configured, which would have caused the repeated deletions? The simpler workaround here is to temporarily set OGCS to one-way sync (O->G in your case) and then set it back to two-way sync - that should stop subsequent deletions.

@upcsfaculty Have you been able to test the hotfix?
