### ISSUE TITLE
Outlook has exhausted all shared resources error message

### ISSUE THREAD

**Issue by mfalkvidd** [phw198/OutlookGoogleCalendarSync#1365]
**OGCS Version**: v2.9.0.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Multiple windows with the following dialog box is shown:
```
---------------------------
Outlook Data File
---------------------------
Outlook has exhausted all shared resources, please close all messaging applications and restart Outlook (example: Skype for Business).
---------------------------
OK   
---------------------------
```
<img width="303" alt="2021-12-30 14_29_41-Outlook Data File" src="https://user-images.githubusercontent.com/893502/147886945-2f1de405-0387-4695-943c-205dc33d847c.png">

**Steps to Reproduce the Issue**  
 - Have OGCalsync autostart
 - Start Outlook
 - Click "Allow"on the "A program is trying to access..." dialog box (not sure if it relevant, but I always get this prompt when OGCS tries to sync)
 
![image](https://user-images.githubusercontent.com/893502/147887275-b805a244-c0d7-431b-bae2-69e5fe2e1793.png)

 - Shut down Outlook
 - Leave the computer running for 1-2 days

The "Outlook has exhausted..." dialog boxes start appearing after about 2 days of uptime. 
One the message has appeared, if I try to start Outlook, the same dialog box is shown.
In the Windows Tray, the "Another program is using Outlook" icon is visible. If I right-click this icon and select "Exit now", the try icon goes away but the same message is shown when I try to (re)start Outlook.
Only solution I've found is to restart the computer, and keep Outlook running at all times.

Skype For Business is installed but not running (no autostart and I don't even have an account so I never start it).

[OGcalsync.log](https://gist.github.com/mfalkvidd/8d29235aaa6086fdb88915710407d34b)

**Comment by szheng09** [comment]
Hi,

is there a fix for this bug. we are getting this error message on OGCS and we can't use as each time it sync it end up stopping due to that error message.

**Comment by phw198** [comment]
Hi @mfalkvidd 

Take a look at the [FAQs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) to see if there's anything you can do to stop the security popup. Do you see this pop-up when you log in after a couple of days? Ie OGCS is trying to sync but is blocked?

Also, when you initially start OGCS and close down Outlook, if you run a sync does the Windows tray icon disappear once the sync has completed?

How many PST files do you have configured in Outlook and how big are they?

**Comment by mfalkvidd** [comment]
Thanks Paul. I am no longer using an Outlook account so I don't have OGCS running anymore. Feel free to close this issue. I still have access to the outlook account, so I can assist in troubleshooting if you want to.

Yes, the outlook tray icon disappears after sync.

I have 1 PST file, 3,08 GB.

**Comment by phw198** [comment]
OK not to worry, thanks for the update @mfalkvidd 

Could have been any number of reasons - the PST file is quite big, but not terrible. Syncing a big date range and not having cached mode enabled might cause the error you found, but sounds like I may as well close this issue if you're no longer using OGCS.

**Comment by PJKuyten** [comment]
Unfortunately I've also run into this issue with the latest Alpha (v2.10.1-alpha) and the newest version of Outlook: "You have Microsoft Outlook Version 1.2023.920.900 (Production). Client Version is 20230922005.11"

Whenever I try to start Outlook Google Calender Sync, I get multiple of the error message pop-up boxes and the application fails to start. This didn't happen with earlier versions of Outlook (the new one seems to update several times per week at the moment, so I can't tell you exactly what the last working version was) or if it happened it was occasionally. But with this version it is always and on start of the application., Even when I don't have Outlook and Teams open, it will produce the error on start of the Sync application.

One thing that I noticed that is different is that I don't get the security pop-up anymore, but this could be caused by the application not even getting far enough for the security question to pop-up!

**Comment by phw198** [comment]
Make sure you are running in cached Exchange mode. If that doesn't help, please open a new issue and upload your log file. Thanks!

**Comment by PJKuyten** [comment]
> Make sure you are running in cached Exchange mode. If that doesn't help, please open a new issue and upload your log file. Thanks!

The new Outlook doesn't have a "Cached Exchange Mode" setting. Or our admins have disabled it.
I also can't switch back to the old client (an option in the new one) as that immediately throws the same resources error.

**Comment by phw198** [comment]
The "new Outlook"? As in #1640 - if so, you can no longer user OGCS, sorry!

**Comment by PJKuyten** [comment]
Thanks for the information. I tried running the old Outlook client i.s.o the new one (since the new client is not replacing the old one), but starting that one gives me the same dialog box. So it seems that new Outlook messed something up that now prevents the old Outlook client from running.

I guess that when it did work, OGCS was actually running the old Client in the background, next to the new one. Somehow this now no longer works, which I assume is an issue caused by Microsoft.

**Comment by PJKuyten** [comment]
Update: Using some registry hacking using option 4 from this page ( https://www.linkedin.com/pulse/how-fix-microsoft-outlook-error-out-memory-system-/ ) I was able to get the old client to run again, which in turn made OGCS work again.
You do need to reboot the system after the registry change though in order to make it work.

**Comment by phw198** [comment]
Good to know and glad you found a solution! Do you actually use PST files, or does that `UseLegacyCacheSize` registry key work for the OST file too?

I'll get this written up into a wiki entry 👍🏻

**Comment by pradeepkatiyar007** [comment]
This might help check it out: [https://www.shoviv.com/blog/fix-outlook-has-exhausted-all-shared-resources-error/](https://www.shoviv.com/blog/fix-outlook-has-exhausted-all-shared-resources-error/)
