### ISSUE TITLE
Portable version - This app has been blocked by your system administrator

### ISSUE THREAD

**Issue by tekkie657** [phw198/OutlookGoogleCalendarSync#1382]
I have used the portable version for years. Now, for 1 week, the app seems to be blocked by our administrator. Has something been changed on your end. Are there others who have the same problem?

Is there anything I can do to get the app working again?
Yes I know, ask the administrator.... ;)

https://images.app.goo.gl/M9S97p6xHpdSZVg76

**Comment by phw198** [comment]
Had you upgraded OGCS recently/just before it got blocked? As you're running in portable, make sure the files are not marked as "blocked" because they have been downloaded (right-click and properties on the executable, for example). There's also also a `ps` PowerShell script in the ZIP to do this for you.

I've heard users with CarbonBlack at work, where OGCS has been blocked, but I think that has a different screen. You could try renaming the OGCS executable file in case they have just blacklisted the file name....?

Nothing has particularly changed with OGCS that would have caused this, however.

**Comment by tekkie657** [comment]
No, I did not update it. 

I was contacted by our IT that this tool is no longer allowed and has therefore been blocked. Very sad that I can no longer use it
