### ISSUE TITLE
Items in Outlook Sync Calendar not being Copied to Google despite two way sync

### ISSUE THREAD

**Issue by galexmay** [phw198/OutlookGoogleCalendarSync#1414]
**OGCS Version**: v2.9.0.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
Some items in my Outlook sync calendar are not being copied to Google. These are items which the beta version seemed to have moved from Google to my other Outlook calendar. I then manually moved them to the Outlook sync calendar after uninstalling the alpha version. I then reinstalled the beta version expecting these items to be synced back to Google but they are not. 

**Steps to Reproduce the Issue**  
See above

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8399428/OGcalsync.log)

**Comment by phw198** [comment]
I would actually expect OGCS to delete those Outlook items you moved between calendars...and I see they're are not because you have deletions disabled "17 Outlook items would have been deleted, but you have deletions disabled."

You should force them to be (rec)synced to Google by temporarily doing a one-way sync O->G.

**Comment by galexmay** [comment]
Sorry, but I couldn't wait 10 days to get a working calendar.
