### ISSUE TITLE
word obfuscation applied wrong: match all regex matches twice

### ISSUE THREAD

**Issue by SVNKoch** [phw198/OutlookGoogleCalendarSync#1425]
**OGCS Version**: v2.9.4.0
**Edition**: Installed 
**Sync Direction**: G->O

**Bug Description**  
Using the word obfuscation rule `.*` -> `Private` results in all appoinments beeing labeld "PrivatePrivate". I would expect it to only be "Private". I fixed it by using the Regex `^.*$` instead. Still wierd behaviour.

**Comment by phw198** [comment]
This does indeed look to be a feature of regex, so not an issue with OGCS. It's due to the "global" modifier, but I don't want to return after the first match because that would almost certainly not be what people want to happen. The minimum find string to stop the repeated return value is `^.*`.

I can't seem to find a good explanation of this on Google, but suffice it to say there's nothing to fix here.
