### ISSUE TITLE
Is portable install of ogcs truly portable?

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#1434]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.2
**Edition**: Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

I am trying to go back to 2.9.2 portable install so I can run three instances separately for three calendars I want to sync. After installing 2.9.4, I am unable to read the settings in each of their respective portable install. I keep getting a splash screen with each portable install. I may have accidentally installed the install version of 2.9.4 (which I uninstalled). Not sure if that causes any issue with the portable install, but my understanding of portable is that a portable folder should be completely independent of any other installed programs.

**Comment by phw198** [comment]
If you have a `settings.xml` file in your roaming profile, `%APPDATA%\Outlook Google Calendar Sync`, then portable version will use this.

Either 
* delete this file (probably the entire directory if you [don't want any remnants](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall#removing-any-remnants) of the installed version) to revert back to using the settings in the same directory as the executable, or
* use the `/s` command line when invoking your portable versions in order to specify where the settings file is located
