### ISSUE TITLE
Appointment Reminders set in Outlook do not replicate to Google

### ISSUE THREAD

**Issue by nicksimonov** [phw198/OutlookGoogleCalendarSync#1445]
it would be great to fix that if possible

**Comment by phw198** [comment]
What evidence do you have that it is broken?

In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by nicksimonov** [comment]
Hello Paul,

Here is what I do step-by-step:
-          Create a new appointment in Outlook 2013 with a reminder set to 1 hour
-          After the sync is done this even is replicated to Google calendar (observed on an Android phone)
-          Opening the appointment on the phone, all the event properties as expected except no reminders are set

The other way around the same issue:

-          Now I add a 15 minutes reminder to the event on Android phone
-          Sync shows nothing is updated and the appointment reminder in Outlook is not changed

Please let me know if you would like me to do some other tests

Thanks,
Nick

**Comment by phw198** [comment]
Try checking the Reminders option under Settings > Sync Options > What and then doing a full sync?

**Comment by nicksimonov** [comment]
It worked, thank you very much!
