### ISSUE TITLE
Chronic colour mapping errors, much confusion!

### ISSUE THREAD

**Issue by BrianBEgan** [phw198/OutlookGoogleCalendarSync#1466]
Enhancements:
- [x] Add a "Delete mapping" button
- [x] Update User Guide to cover colour maps
----

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release] (https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)  I AM ON 2.9.4!!! 
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [-] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
CANNOT!  Logging set to all, but there's no file from today's syncs despite repeated tries!

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
A.  Chronic appearance of error message "There is a problem with your colour mapping configuration. Colors may not get synced as intended. Review maps now for missing Outlook colors?"
B.  UI/UX on the Colour Mapping dialog box is exceptionally frustrating.

**Steps to Reproduce the Issue**  
1. Run a sync.  Colour mapping error msg with offer to fix pops up most times (twice, requiring two clicks to clear).
2. Accepting the offer to fix the map results in an exceptionally confusing process (e.g., if you accidentally create a second instance of the outlook color in the list -- easy to do -- there's no obvious way to get rid of it, and it generates an error if you try to proceed).
3. Upon struggling through the mapping process to a successful new list, the results aren't saved, and the whole cycle happens again.  

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
No log file is generated.  (I have generated log files previously for another bug, so I don't think it's user error.)

This could be a user misunderstanding, but given that the User Guide says nothing about colour mapping, I hope I would be forgiven.  Issues:
- There doesn't seem to be an obvious navigation to the colour map other than by accepting the post-error invitation.  How about something in Settings (or if it's there, make it obvious).
- What on earth is the Test Map?  It doesn't seem to do anything, and no explanation is offered anywhere.
- I would expect the left column (Outlook) to contain all existing categories with the colours assigned by the user in Outlook.  I would then expect the mapping process to be simply changing the colour in the corresponding Google column using the dropdown.  I would then expect Save to lock in that mapping and I'm done.
- Given the previous point, there should be no need to add new Outlook Categories/colours in the right column, because they wouldn't logically find their way back into Outlook's settings to appear as new categories.  The whole process should be a simple correspondence-setting effort taking seconds and immune from cockups.  If it worked that way, I would not have spurious creation of duplicate Outlook column entries and the resulting frustration of having to stumble around to get rid of them.
- Documentation of how the whole things works belongs in the User Guide.
- (There also seems to be no easy way to get at log files other than clicking the link in Help.  Why not put a button in next to the logging level selector?)

I really like this product and appreciate the hard work, but this error is driving me over the edge.

**Comment by phw198** [comment]
I don't think it's possible to run OGCS without it generating logs.
> (There also seems to be no easy way to get at log files other than clicking the link in Help. Why not put a button in next to the logging level selector?)

I'm not sure if you're trolling :thinking: 
![image](https://user-images.githubusercontent.com/11843015/167744675-d5f58642-2d70-41ea-9fb5-cafd4834f9c5.png)
The button will open Windows Explorer with the folder containing your logs.

> There doesn't seem to be an obvious navigation to the colour map other than by accepting the post-error invitation. How about something in Settings (or if it's there, make it obvious).

![image](https://user-images.githubusercontent.com/11843015/167744892-f58c1c4a-b2f2-46ec-a5d6-d82423b52a1c.png)
Feels pretty obvious to me?

>What on earth is the Test Map? It doesn't seem to do anything, and no explanation is offered anywhere.

It....tests the maps your have configured in the table below. Change one of the dropdowns and the other will change to the configured mapped value, or if there is none, the closest colour match.

> there's no obvious way to get rid of it

Another user also mentioned this - see [my response](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1389#issuecomment-1066104619) - I'll add a `Delete Row` button to make it more obvious.

> the results aren't saved

How so? I make some mapping changes, click OK, clicking the "Mapping" button again and my changes reappear. If you want the changes to persist beyond a restart of OGCS, then you need to click "Save" - same as with all the other configuration options.

> I would expect the left column (Outlook) to contain all existing categories with the colours assigned by the user in Outlook. I would then expect the mapping process to be simply changing the colour in the corresponding Google column using the dropdown. I would then expect Save to lock in that mapping and I'm done.

Yes, that's exactly correct and how it works for me!

> Given the previous point, there should be no need to add new Outlook Categories/colours in the right column, because they wouldn't logically find their way back into Outlook's settings to appear as new categories. The whole process should be a simple correspondence-setting effort taking seconds and immune from cockups. If it worked that way, I would not have spurious creation of duplicate Outlook column entries and the resulting frustration of having to stumble around to get rid of them.

Now _I'm_ confused - there are no Outlook Categories/colour in the right hand column, only Google colours! "because they wouldn't logically find their way back into Outlook's settings to appear as new categories" - I don't know what this means. Unless you mean when you sync from Google to Outlook and there is no defined Outlook category for that colour, so it creates an "OGCS \<colour\>" category for you? I'm guessing you really want a mapping to avoid this situation...!

Your overall point about the User Guide being out of date is valid - I'll have to try and carve some time out to update it.

**Comment by BrianBEgan** [comment]
Paul, I'm not trolling, really!  In the fog of frustration and fatigue, yes, and so made some stupid errors.  I missed the Application Behaviour tab, and so didn't see the logging area.  Now I can find the log file location.  Same for not being able to find the Mappings button.  Definitely my error, and I apologise.  
Ditto for "there are no Outlook Categories/colour in the right hand column" -- True, I meant to say left hand column.

I need to mention that I am running Windows under Parallels Desktop on a 2021 MacBook Pro M1.  Not sure if that makes a difference.  

I also uninstalled and reinstalled OGCS, and that may have helped some of the mapping issues.  I was surprised that it remembered my settings, so the uninstall must have left a config file behind somewhere.  After the reinstall, I started experiencing 15-20 second hangs when trying to set the color mappings, so I restarted Windows.

I trod very carefully through the mapping, and managed to get it to "stick".  Again I suspect it was my error, but I'm not sure how I erred.  My colour mapping popups are now a thing of the past (but I am still getting  "Event update failed. Object reference not set to an instance of an object" regularly, and haven't a clue what to do about it).

So my whinging now boils down to a few very minor points:
- The test map still doesn't seem to add value, because it replicates the effect of the dropdown in the row with focus below.
- The far left column with its > and * symbols still mystifies me.  I would expect clicking on a box in the Outlook or Google column to set focus to that row and column, with Tab or clicking switching columns.  
- Since you're putting in a delete row "-" button, why not complement it with a "+" add row column?.  But, that said, why not simply auto-populate the Outlook column with the categories/colors gleaned from Outlook, and simply use the colour dropdown in the right column to create pairs?

OK, I'm done.  I apologise for the consternation and wasted time I caused, and reiterate that you have a very useful product.

Best,
Brian  

N.B. Pls disregard any unintentionally uploaded screenshots of the above.

**Comment by phw198** [comment]
For the error you're getting, it sounds like #1422, which has a hotfix posted.

Glad you've got it all sorted now!
* The test map I feel still has value - as you select a value from the drop down on the or right, the other one will shop the equivalent matched colour. If you have defined a mapping in the table below, it will show that the default mapping is being overridden.
* The whole table is a default Microsoft table control, so the oddity about row selection etc is just how it works! I'll see if I can add extra functionality to improve it though.
* Because you shouldn't be creating colour pairs for _everything_, just the ones you want to work differently than they do by default (eg map Outlook "red" to Google "cobalt" instead of Google "tangerine")
