### ISSUE TITLE
not all google calendar events get synced to outlook cal

### ISSUE THREAD

**Issue by michalj86** [phw198/OutlookGoogleCalendarSync#1486]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v  2.9.5.0
**Edition**: Installed / Portable  
**Sync Direction**: O<->G

**Bug Description**  

Sync version: 2.9.5.0

Profile: Default

Sync started at 23.05.2022 20:17:25

Syncing from 22.05.2022 to 23.07.2022

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

40 Outlook calendar entries found.

Scanning Google calendar...
47 Google calendar entries found.

10 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 40, Google 47
**hoe vomr not sll events from the google calendar get synced to outlook cal? two way sync is set**
**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8757249/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8757254/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Logs show that 2 Google items are excluded as you have declined them or they have been cancelled. Are these the ones not being synced?

OGCS also wants to delete 7 Google items, but you have that disabled. If this is because you first did a one-way sync before turning on two-way, then you can resolve that [following these instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).
