### ISSUE TITLE
The Given Keyword Was Not Present in the Dictionary

### ISSUE THREAD

**Issue by pearsond1** [phw198/OutlookGoogleCalendarSync#1504]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

SYNC continues to result in the following error message:
"The given keyword was not present in the dictionary"
"Sync aborted after 1 failed attempts"_**

**Steps to Reproduce the Issue**  
1. Go to... Sync button
1. Click on...Sync now button
![Screenshot 2022-07-06 144142](https://user-images.githubusercontent.com/78118540/177630201-41f000d9-ac99-40a4-8e52-0e7501046791.png)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
