### ISSUE TITLE
OGCS hangs during sync with Outlook in online (non-cached) mode

### ISSUE THREAD

**Issue by sansnil** [phw198/OutlookGoogleCalendarSync#1527]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0
[OGcalsync.log]: Attached

**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
OGCS runs very slowly when running Outlook (Exchange) in non-cached mode. If Outlook is in cached mode it syncs very quickly but when in online mode it seems to hang.

**Steps to Reproduce the Issue**  
1. Put Outlook in non-cached mode
1. Attempt to sync OGCS

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
If you have a lot of calendar items and/or a large sync date range, I'm not surprised at all - it's having to drag all your calendar items across over the network from the Exchange server every time it syncs. Cached mode is the only sensible option really...

**Comment by sansnil** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9456013/OGcalsync.log)

Attaching logs with Fine enabled per request.

**Comment by phw198** [comment]
My reading of your logs is that you have a lot of recurring meetings that go back several years, starting in 2019 for example. These often have lots of "exceptions" where an occurrence has been changed and due to the way the Outlook model works, these all have to be retrieved to work out if they should be synced and/or have changed.

As you are not in cached mode, these have to be downloaded each time and it's taking ages. Can you not just turn on cached Exchange mode?

**Comment by phw198** [comment]
[Wiki entry added](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-is-outlook-freezingbecoming-unresponsive-when-ogcs-syncs) to cover this.
