### ISSUE TITLE
Unable to Update Existing Entries in Google Calendar Error

### ISSUE THREAD

**Issue by kamwatang** [phw198/OutlookGoogleCalendarSync#1542]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0  
**Edition**: Installed   
**Sync Direction**: O<->G

**Bug Description**  
Sync is failing due to some error related to updating existing entries in Google Calendar.  This behavior started today, and I haven't made any changes to OGCS.  I am attaching a screenshot of the sync tab and logs from today and yesterday.  

**Steps to Reproduce the Issue**  
1. Start Sync

**Any other information**  
[OGcalsync.log.2022-10-04.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9719039/OGcalsync.log.2022-10-04.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9719041/OGcalsync.log)
![image](https://user-images.githubusercontent.com/33560886/194166283-a0e23b7d-46f0-4c9b-b85e-7f39290e9d0e.png)

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
It looks like the issue lies with a specific item in your calendar: The recurring series `5/3/2022 1:30 PM (R) => "Bi-Weekly Marketing ops and IT Go To Market review call"` and the series exception on 04-Oct-2022.

Is there anything strange about this item? Perhaps you do not have ownership or permissions to change the item?

Please let me know if this is still a problem - if it is, I can try and get out a version for you with extra logging that will hopefully cast some light on what is going wrong...

**Comment by kamwatang** [comment]
Hi Paul,

This isn't an issue anymore.  I think because the calendar entry now falls outside my sync period.

For your reference, I don't see anything strange about the series entry on 04-Oct-2022.

Thanks,

Kam
________________________________
