### ISSUE TITLE
sync from outlook (android) not appearing on desktop outlook calendar.  only synching 1 direction (yes have selected dual direction) :-)

### ISSUE THREAD

**Issue by GHET1** [phw198/OutlookGoogleCalendarSync#1545]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2950
**Edition**: Portable  installed
**Sync Direction**: G->O

**Bug Description**  
see above

**Steps to Reproduce the Issue**  
1above - only synching 1 direction
1. have tried creating the cal entry on phone using google calndar, have tried samsung calendar but nothing works to fix it

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
The title of your issue is somewhat mysterious - Syncing from Android Outlook to desktop Outlook? That's not what OGCS does, it syncs to/from Google calendar and Outlook desktop.

Remove Android from the equation, go to calendar.google.com and create an event there. Configure OGCS to sync from the calendar you created the event in.

Hope that helps, but I'll need a logfile to assist any further with your configuration.
