### ISSUE TITLE
OGCS Deleted 2 months of calendar entry

### ISSUE THREAD

**Issue by hadrien972** [phw198/OutlookGoogleCalendarSync#1555]
**OGCS Version**: v2.9.5
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
It is the second time that OGCS deletes without my permission, various calendar invites. The first time was a few months ago and it was a few invites here and there. It was quite subtle. This time it has nonetheless deleted everything in my calendar for the past two months, which is an issue.
I would therefore like to know:
1. How to recover everything that was deleted.
2. How to prevent it to happen again.
Thank you

**Steps to Reproduce the Issue**  
I don't know. It seems to do it on its own, independent of my will.

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10003642/OGcalsync.log)

**Comment by phw198** [comment]
I'm sorry to hear that. However, in the log file you have provided, the most items that have been deleted in a sync is 7 from Outlook.

You also say it's removed items that occurred only in the last two months? Your OGCS settings are to sync 365 days in the past and future, so I don't see how OGCS would only delete items in the last 60 days.

Is there any way something else could be doing this? Your logfile covers 14-Nov-2022 - is this the day that the deletions occurred?

**Comment by hadrien972** [comment]
Hi,

Sorry, i have only just seen now your answer.
Now the application has just deleted all my calendar entries.
Last night it seemed that it had deleted all my entries from Google. Today (the 15th Jan) they were still on Outlook, but instead of putting them back on Google, it deleted all of them from Outlook. So I am left with nothing.
Is there a way to undo the syncing?

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10420426/OGcalsync.log)

**Comment by phw198** [comment]
Hi @hadrien972 

The log file provided for 15-Jan shows the first sync at 14:22 - this already shows that there are only 3 items in Google and there's no indication that OGCS removed them from Google on the same day at least:
`2023-01-15 14:22:25,410 INFO  7 OutlookGoogleCalendarSync.Console [287] -  Outlook 363, Google 3`

Because you have two-way sync turned on, if the items are removed from Google, then OGCS will replicate that back to Outlook. To recover the items:
* make sure you switch OGCS to one-way sync from Outlook to Google
* switch to the "Folders" view in Outlook and then go to the "deleted items" folder
* restore the deleted items and then run a sync to repopulate Google

If you have the logs for the day(s) preceeding 15-Jan it would be helpful to review those to see if the Google deletions are logged in those or not.
