### ISSUE TITLE
Cannot suppress mass deletion confirmation

### ISSUE THREAD

**Issue by mukkino** [phw198/OutlookGoogleCalendarSync#1565]
Hello,

I am unable to supress the mass deletion confirmation. I am synching a calendar in Oulook under the "Other Calendars" folder. This calendar has as location \\\Internet Calendars. This is basically a locally shared calendar from Pagico (an .ics file)

This local calendar is read only and at each sync the app should delete everything in the corresponding Google Calendar and replace with the local one. It actually works. The problem is that I unchecked "Confirm deletions" in the Sync Options tab and still get the mass deletion confirmation dialog

Please find the app configuration enclosed in the PDF file

Any suggestion/help is appreciated

Thanks

[MassDeletionConfirmation.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/10201917/MassDeletionConfirmation.pdf)

**Comment by phw198** [comment]
Hi @fabiolichinchi Yes, this is by design - it's to try and stop people mis-configuring their sync and then shouting blue murder at me when they've wiped their calendar :slightly_smiling_face: 

As a workaround, could you try manually adding a new item to the Google calendar and then setting OGCS to "Merge with existing entries"? Hopefully this will mean it is not deleting _all_ Google items and it won't trigger the bulk delete alert...

**Comment by mukkino** [comment]
Hey @phw198 , I see why you have that message there :)

Your suggestion works!

Thanks!
