### ISSUE TITLE
Outlook 2021

### ISSUE THREAD

**Issue by eglee57** [phw198/OutlookGoogleCalendarSync#1585]
**Are you already using OGCS?**
2.9.0 Beta
 I upgraded from Outlook 2019 to 2021. OGCS can't find the Outlook file.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
