### ISSUE TITLE
O<->G: Configuration issues

### ISSUE THREAD

**Issue by workjoeea** [phw198/OutlookGoogleCalendarSync#1587]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0 
**Edition**: Installed / Portable  
**Sync Direction**:  O<->G

**Bug Description**  
There's a few things.  I'm currently running the beta.  Please be gentle, I'm not a programmer, I'll do what I can.  I don't know if I can reproduce the issue.  I uninstalled and reinstalled, to no avail.  I'm trying to do both-way sync.  I'm hesitant to install the Alpha.  I'm guessing whatever log file I produce may now be of limited use.

I've now had Outlook meetings removed from my Outlook calendar a couple times (it's getting embarrassing to ask to be re-invited) never mind there's no reason (nothing was deleted).  I've also recreated events in Google that then won't sync back into Outlook.  And I can't seem to figure out how to recover the deleted items from my outlook.

I also try to block out OOO times on my Outlook, to only have them turn to "Busy" for no apparent reason.  I left that box unchecked, I think.

I think the log file attached.  I can't tell.  Again, please be gentle.  Thank you.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10449441/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Apologies for the delay in responding.

Your logs show you have always had `Confirm on delete` checked, so you should have been prompted before anything was deleted? You can always look in the `Deleted Items` folder (use the `Folders` view) in Outlook to restore items you need back.

You also are only syncing Outlook items that have no category or the red category - seems a bit odd, is that intentional?

For the OoO vs Busy, seems you have setting all synced items to Google as busy - I guess because you have two-way sync on, if you then change Google item, it will overwrite OoO back to Busy in Outlook. That's not quite the intended behaviour, and I suspect that doesn't happen with the later alpha releases... Don't be too scared about alphas :slightly_smiling_face:
