### ISSUE TITLE
G->O: Reminder Sync?

### ISSUE THREAD

**Issue by iasktank** [phw198/OutlookGoogleCalendarSync#1595]
**Are you already using OGCS?**
2.9.0.0

**Describe the question you have**
When syncing my Google calendar events to my Outlook calendar events, it does not seem that the alerts are coming over with them.  I checked a recently synced appointment (Synced from Google to Outlook) and Outlook had NONE for Reminder.

**Comment by phw198** [comment]
Make sure you have set the reminders to be synced under Settings > Sync Options > What > Reminders - see [more details in the User Guide](http://www.outlookgooglecalendarsync.com/guide/syncoptions#what).

In order to receive further support, you'll need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
