### ISSUE TITLE
G->O: Google Meet links are not synced

### ISSUE THREAD

**Issue by giuseppe-r2m** [phw198/OutlookGoogleCalendarSync#1605]
**OGCS Version**: v2.9.6.0 latest alpha  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
1) create a meeting in google calendar and set a Meet meeting.
2) do a bidirectional sync
3) the meeting appears in Outlook, but the Meet link is lost

**Steps to Reproduce the Issue**  
See bug description

**Any other information**  
I have been using OGCS for some months, didn't notice this problem from the beginning, but I can't say when it appeared.
[OGcalsync.log](https://github.com/phw198/Outlook
<img width="475" alt="Immagine 2023-02-27 120752" src="https://user-images.githubusercontent.com/126456821/221548348-16ca6aaf-70b7-441f-abd3-18685cafcb86.png">
<img width="592" alt="Immagine 2023-02-27 120828" src="https://user-images.githubusercontent.com/126456821/221548357-6c9435de-2e75-4996-ba3a-3655f0fa2422.png">
GoogleCalendarSync/files/10838962/OGcalsync.log)

**Comment by phw198** [comment]
Duplicate of #1076.

Where would you expect the Meet link to appear in Outlook? I see you have a plugin for Outlook with a `Add a meeting` button - what does this actually do?

**Comment by kalbun** [comment]
I understand that I didn't explain very clearly the issue, I'll try to add more details.
The first image is a meeting I created in google calendar, with a google meet attached.
The second is the entry in outlook after sync. I would expect the link to google meet in the comments box, and I'm almost sure that this was working well since a few months ago.
The button you mention is an outlook plug in that allows to add a meet link. In that case, Sync to google calendar works fine.

**Comment by phw198** [comment]
Thanks for the further detail - I had understood the screenshots, just that Outlook does not have anywhere to natively store a Google Meet link and adding it to the description/body is non-trivial if a "real" body exists and you have two-way sync configured!

OGCS has never synced this attribute - it's "new" and I've never got round to checking the API to work out what's involved, which is why it's still on the enhancement backlog :disappointed:  It's near the top of the pile to triage though!

Can you provide screenshot(s) of what the Outlook add-in button does?

**Comment by giuseppe-r2m** [comment]
Here is an image. Pressing that button has the effect to fill place field with goggle meet, and add that block of information in the comments fields.

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by giuseppe-r2m** [comment]
![immagine](https://user-images.githubusercontent.com/126456821/227860297-5a6c73a6-6029-49b7-a64a-555396873a1d.png)

**Comment by stremshs** [comment]
Hi there ! 
I'm VERY interested by this feature : 
I'm using Calendly which generates events with a Google Meeting attached.
But when incoming to our Outlook Calendars, no link is displayed.
We need to open Google Calendar to connect to the meeting, which is quite a hassle.

That would be SO GREAT to have a body (such as exposed above) in the event !

**Comment by phw198** [comment]
Thanks all, please track progress on this feature on #1076
