### ISSUE TITLE
Cannot reclaim specific Outlook item [0x80004004]

### ISSUE THREAD

**Issue by hazelsmasher** [phw198/OutlookGoogleCalendarSync#1636]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.7.0  
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  

Sync produces the following errors/readout in the sync tab:

- Failure processing Outlook item:-
4/26/2023 1:00 PM "LTM BNI Training"
- Unable to reclaim orphan calendar entries in Outlook calendar.
- Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
- Sync aborted after 1 failed attempts!

**Steps to Reproduce the Issue**  
1. Click Sync
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11279611/OGcalsync.log)

As seen in the log, I tried syncing with debug mode on, as well as ultra-fine.

**Comment by phw198** [comment]
Usually that error means that you don't have permission to save changes to the item in Outlook. Have you tried opening `4/26/2023 1:00 PM "LTM BNI Training"` manually in Outlook and seeing if you can make a small change before saving it?

I also note there are some custom properties held against the item which have not been created by OGCS - so some other tool must be also managing them in Outlook, or created it perhaps? I wonder if this might be the root cause...
```
DoNotForward=False
HideAttendeeList=False
CalendarEventClassificationInternal=System.String[]
```
