### ISSUE TITLE
Retrieve Google Calendar leads to error "Something went wrong. Sorry, something went wrong there. Try again."

### ISSUE THREAD

**Issue by ciaranconsidine** [phw198/OutlookGoogleCalendarSync#1664]
**OGCS Version**: v2.9.7.0
[OGcalsync_Something went wrong.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/11782437/OGcalsync_Something.went.wrong.txt)
 
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
I've had success with OGCS for years. Setting it up on a new computer (Dell XPS running Windows 11). When I attempt to Retrieve Google Calendar, the browser opens, I sign in and confirm permission, then Google reports an error message "Something went wrong. Sorry, something went wrong there. Try again." (associated url: https://accounts.google.com/info/unknownerror), when I click Next, I am forwarded to my myaccount.google.com homepage. 

**Steps to Reproduce the Issue**  
1. I've uninstalled, reinstalled, tried beta and alpha, changed network, logged out of Google prior to launching the retrieve. 
2. Each time, same thing happens.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

See attached file.

**Comment by phw198** [comment]
Previously when this happened on #808, it was down to Google having problems. I've had a scan through their outage history - [this one looks vaguely applicable](https://status.cloud.google.com/incidents/X3683kovx3cNYjorkosn).....but anyway, can I assume you have been able to authorise OGCS successfully since?

**Comment by newtonrs** [comment]
The information on the "Try Again." error message mentioned above -- including the uninstall and a re-install of 2.10.2 (Alpha & Beta of most recent releases) and deletion of previous "projects" created in Google's Cloud Console -- is still appearing. I uninstalled because the sync was failing and I couldn't resolve it (OGCS indicated a corrupt config); and I removed the "project" because after the reinstall the "Try Again" error persisted. 

But all efforts have failed! The project name is correct when the "connect" page from Google appears in the browser, but the error persists.

Eventually I did find the problem: Disable *ALL* extensions/add-ins that are presently installed in the browser--doesn't seem to matter which browser you use as your default, the extensions/add-ins need to be disabled.

After doing so, the only remaining "error" that appeared *AFTER* the last step was successfully completed to "register" OCGS for access to the calendar was a web page that said there was an error loading/accessing: 127.0.0.1:<port_number>. However, this issue doesn't appear to have affected the ability to sync calendars that I've seen as yet.

**Comment by phw198** [comment]
@newtonrs I think your issue (#1786) is much more around the configuration of your personal project for API keys and/or browser extensions etc. The OP here was reporting authorizing with the OGCS default API keys, which I believe was temporarily not working due to Google service problems.

**Comment by newtonrs** [comment]
Hi Paul,

 

I’ll try to reply to both your messages here together…

 

Regarding the switch to Chrome; that made no difference. The port must be blocked, but how when the AV software has been suspended, I do not know—I’m not uninstalling it to test that the AV software is the issue here.

 

The “project” is configured per the instructions you made available through GitHub—and seems to closely parallel the information at the link you provided—so, I’m fairly certain that the process was completed correctly. In addition OGCS was functioning and then stopped—perhaps the issue you indicate that Google was experiencing?—and so I tried using the credentials that already existed to reconnect, after disconnecting, the calendar. Again, this failed several times, so I decided to create a new “project” following the same steps as have been outlined. The original project and the new project appeared the same in setup and each had associated with it its own client ID and secret.

 

The new client/secret worked for approximately one month and then OGCS stopped working and then the message about the project “expiry” and no longer being valid. I then attempted to disconnect and reconnect with the previous project—the original project—and the message was the same: expired.

 

I deleted these two projects and started from scratch… This time around the project would not properly complete the configuration with OGCS, as per the posting and our “conversation” here about this issue. Finally, I disable all extensions to Firefox and the process completed to “register” OGCS with the only remaining “project” with an id/secret available. This is when the access error for “https: // 127.0.0.1:55661” first appeared. I then attempted the disconnect and reconnect with Chrome—per your message—as the default browser; result the same failure to connect to 127.0.0.1:55661.

 

So, my question: is the failure to make the connection to 127.0.0.1:55661 going to affect my usage, or my continued usage of OGCS? I ask since the last time this happened; failure to connect to 127.0.0.1:55661;I got one month of OGCS synching before getting the project expired notice and OGCS could not longer sync?

 

Hope this makes sense out of the question and the steps that I’ve already taken. And as you probably can tell, at this stage OGCS, using the latest id/secret is currently functional; I just want to keep it that way beyond 30-days.

 

 

Thanks,

__________

Rick Newton.

E-Mail:                   ***@***.***> ***@***.***

Phone:                 905.319.1928

Mobile:                905.802.9962
