### ISSUE TITLE
Entry at google is added to another calender by the second and following runs

### ISSUE THREAD

**Issue by robyy72** [phw198/OutlookGoogleCalendarSync#1687]
Hey guys,
screenshot added, it should show the problem.
Anyway, good job, go ahead!
Best and thanx in advance
Robert
![screenshot_sync](https://github.com/phw198/OutlookGoogleCalendarSync/assets/12403067/32023e7b-2ec9-4a73-90e1-78c0aa855634)

**Comment by phw198** [comment]
A single screenshot is not enough to troubleshoot.

In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg).
    1. In your situation, I think this would be after OGCS created an item in the wrong Google calendar: "Robert priv"?
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Thanks!
