### ISSUE TITLE
Prompt for Profile to use on Startup

### ISSUE THREAD

**Issue by TroyB9** [phw198/OutlookGoogleCalendarSync#1695]
I did a search and did not see this specific option.

It would be nice if there was an option to prompt for profile on startup, just like outlook.   Then I could choose the appropriate OGCS profile that matches the outlook profile I'm using without getting a getting a mismatch error until I change back to the correct profile.

**Comment by phw198** [comment]
Does this mean you don't schedule the OGCS Profile to sync automatically? Because if it did sync automatically, then wouldn't you get the errors anyway regardless of picking a specific Profile to show in the GUI when OGCS loads?

Sounds maybe better for you to configure and run an instance of OGCS for each Outlook profile you have - https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS

**Comment by TroyB9** [comment]
Hi, thanks for the reply.  Correct, I do MANUAL syncs only and do not automatically run at windows startup.

**Comment by phw198** [comment]
Given you're manually loading OGCS and triggering syncs I don't really see much benefit prompting for the OGCS profile to use - just select the correct one once it's loaded. Or have a batch file which loads the appropriate OGCS `settings.xml` configuration file  for each of your Outlook profiles, as linked to in my previous post.

**Comment by TroyB9** [comment]
ok thanks for the feedback.
