### ISSUE TITLE
Check for updates - Failed to check for ZIP release

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#1711]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.1.0
**Edition**: Portable  
**Sync Direction**:  O->G / O<->G

**Bug Description**  
When I click on check for updates, an error message pops up saying Failed to check for ZIP release

**Steps to Reproduce the Issue**  
1. Go to About tab
1. Click on Check for Updates
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12785571/OGcalsync.log)  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12785586/OGcalsync.log)

**Comment by phw198** [comment]
Thanks for raising this - it's started because GitHub have recently made changes to their wiki formatting :slightly_frowning_face: 

:package: This should now be resolved with [hotfix v2.10.1.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12838020/v2.10.1.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by JP3251** [comment]
I have the portable version though and cannot install exe

**Comment by phw198** [comment]
The instructions for applying a hotfix don't mention anything about it requiring OGCS to be installed... 
You just replace your existing executable with the hotfix executable.
