### ISSUE TITLE
Deleted item in Outlook (one-way sync to Google) no longer gets removed from Google calendar

### ISSUE THREAD

**Issue by CC-70300** [phw198/OutlookGoogleCalendarSync#1727]
OGCS Version: v2.10.1.0
Sync Direction: O->G (one way)

Bug Description
If an outlook meeting item from someone else is deleted, it is no longer deleted/removed from the Google calendar.

Own meeting item will be deleted/removed from the Google calendar without issue. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13234793/OGcalsync.log)

**Comment by phw198** [comment]
What is the time and subject of the item not being deleted? Is it a single event, an occurrence of a series, or an entire series that has been deleted in Outlook?

**Comment by CC-70300** [comment]
Currently, I observed a single event deleted/cancelled in Outlook but not deleted in Google. 

there is an item recently cancelled in Outlook but not updated in Google : 2 Nov 2023 1030am

**Comment by phw198** [comment]
Please can you
* turn on CSV exports in the Application Behaviour settings section
* extend the sync window to go back to 1-Nov
* run a sync
* check the folder with the OGcalsync.log file for `outlook_appointments.csv` and `google_events.csv`
* Is the 2-Nov-2023 10:30 item listed in either file?

**Comment by ayalozer** [comment]
I have a related question that is probably not a bug. hope it's OK to post it here:
I'm using OGCS to sync my workplace Outlook with my mobile so I can follow meetings when away from laptop, etc. 
I noticed that when I deleted/decline a meeting in google calendar it would do the same on Outlook at next sync. 

I don't want this behavior - when I cancel something on my phone it's because I don't want to see it there, and I would like to control my work schedule on outlook directly. 

would this be possible if I check "disable deletions" on Sync options? the user manual didn't really tell what this switch does.

Again, not sure if it's a bug or a feature, but would like to know how to get the behavior I want.

Thanks!

**Comment by phw198** [comment]
@ayalozer As you say, not a bug as that is how a two-way sync is designed to work.

Disabling deletions would not replicate any deletions at all, in either direction, so this is probably not what you want either. Your options, in order of simplicity, are:

* Only sync one-way from O->G
* Turn on deletion confirmation, so you can pick which ones get replicated
   * However, the latest alphas will sync back the original item to "undo" the deleted item when deletion is declined (ie reinstate your deleted Google item)
* Assign a colour to the item instead of deleting it in Google. Then set OGCS to exclude that colour, but uncheck the "delete when synced item is excluded" option. This requires v2.10.2.

**Comment by CC-70300** [comment]
> Please can you
> 
>     * turn on CSV exports in the Application Behaviour settings section
> 
>     * extend the sync window to go back to 1-Nov
> 
>     * run a sync
> 
>     * check the folder with the OGcalsync.log file for `outlook_appointments.csv` and `google_events.csv`
> 
>     * Is the 2-Nov-2023 10:30 item listed in either file?

Subject of deleted item is " Llamasoft ...."

I did as suggested and I checked both csv files ( outlook_appointments.csv and google_events.csv ), the deleted item is not in both csv file. But it stays on my Google Calendar (see attached screenshot from Google Calendar)
![llama](https://github.com/phw198/OutlookGoogleCalendarSync/assets/110214600/b743f206-fd87-4e0a-a6c0-bbd3e82005e9)

In this case, this is a recurring appointment which 2nd Nov item is deleted but not entire series.

I have encountered previously one off appointment cancellation also behave same way.

thanks

**Comment by CC-70300** [comment]
Today (just after I posted previous reply), I had another meeting series cancelled, whole series is cancelled and deleted in Outlook. This item is completely deleted in Google Calendar.

**Comment by phw198** [comment]
> Today (just after I posted previous reply), I had another meeting series cancelled, whole series is cancelled and deleted in Outlook. This item is completely deleted in Google Calendar.

So to summarise, working correctly?

> Currently, I observed a single event deleted/cancelled in Outlook but not deleted in Google. there is an item recently cancelled in Outlook but not updated in Google : 2 Nov 2023 1030am

The "LLamasoft" item on the 2-Nov isn't a single event, its an occurrence of a recurring series. And even worse, that occurrence apparently was originally on 11-Jan-23 - I'm not even sure how that is possible, as the recurring series appears to start on the 12-Oct-23:
```
2023-11-02 11:10:19,705 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [666] -  10/12/2023 10:30 AM (R) => "Llamasoft (Understanding from basics)"
2023-11-02 11:10:19,706 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [667] -  This is a recurring appointment with 2 exceptions that will now be iteratively compared.
2023-11-02 11:10:19,728 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [443] -  Finding Google instance for deleted Outlook exception:-
2023-11-02 11:10:19,729 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [444] -    Original date: 01/11/2023
2023-11-02 11:10:19,729 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [472] -  Google exception event is not cached. Retrieving all recurring instances...
2023-11-02 11:10:19,729 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [166] -  Retrieving all recurring event instances from Google for mifl6m9srnn4q129laaq8pfvso
2023-11-02 11:10:20,352 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [175] -  Page 1 received.
2023-11-02 11:10:20,356 WARN  17 OutlookGoogleCalendarSync.Recurrence [764] -  No matching Google Event recurrence found.
2023-11-02 11:10:20,357 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [764] -  The Outlook appointment is deleted, so not a problem.
```
I'd cut your losses and delete and recreate the series in Outlook...

**Comment by CC-70300** [comment]
Yes, you are right. It working properly now.

Thanks for looking into this :)

**Comment by CC-70300** [comment]
Yes, you are right. It working properly now. I will closed this topic

Thanks for looking into this :)
