### ISSUE TITLE
2.10.2.0 - Partial text in settings (see atached)

### ISSUE THREAD

**Issue by rafi-d** [phw198/OutlookGoogleCalendarSync#1730]
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/2458280/b39b3ab4-80b4-46ee-9cec-9bd7d5c0c1f2)

**Comment by phw198** [comment]
Thanks @rafi-d 

:package: Please check if this is fixed with [hotfix v2.10.2.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13257254/v2.10.2.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.

**Comment by rafi-d** [comment]
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/2458280/b2f6a0ca-ff51-4c68-9e45-396203b6ac0f)

Better now, but bottom line is still partial not visible ...

**Comment by phw198** [comment]
:package: Thanks! Hopefully now fully fixed with [hotfix v2.10.2.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13380782/v2.10.2.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes?

**Comment by rafi-d** [comment]
Looking good now!
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/2458280/b9c71418-2588-443d-a056-d9528e3d8d19)

**Comment by phw198** [comment]
Perfect - thanks for the quick test!
