### ISSUE TITLE
OGCS Aborting "Unable to update existing entries in the Outlook calendar"     

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#1736]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4     

**2.10.2.0**

**Edition**: Installed / Portable   

Installed

**Sync Direction**: G->O / O->G / O<->G      

 O<->G

**Bug Description**  

Hard abort,  not much information provided into Log as to which entry was the cause.   "Unable to update existing entries in the Outlook Calendar"   "something went wrong"

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

Just rerun the sync.   It has failed for me 3 times, including after the latest OGCS update
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13419034/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Unfortunately, not much information in the logs because all Outlook is saying to OGCS is "Sorry, something went wrong. You may want to try again.". Very helpful.

The issue appears to be with `11/18/2023 3:30 PM => "Jen Zoom"` however, so if you can see anything different with this appointment or can delete and recreate it, give that a try.

Might be worth a PST/OST file scan to check it for errors too...

**Comment by mjlipton** [comment]
Thank you Paul.

I deleted the entry and reran OGCS,  and it worked.

The Jen Zoom event that you identified as the culprit had a Zoom link that was created by the Zoom Outlook add-in.   So perhaps there is some kind of interaction with that.

To test my theory I added a new appointment on the Outlook side,  with a Zoom link from the Add-in,  and then reran OGCS,  and it worked fine.

But then I  cancelled the test appointment that I had just created,  and Outlook crashed.   When I restarted it, it said that the Zoom addin caused the crash, and it disabled the addin.

So,  there is something going on with the Zoom addin…

Michael

**Comment by mjlipton** [comment]
Second OGCS crash similar to first, except that Zoom add-in was disabled,

Last time it failed,  the event was created by the Zoom add-in.   this time, the add-in was disabled,  but I used the browser-based Zoom.com  to schedule an appointment, and then it created the outlook event.    See the event screenshot attached.

![Outlook Event Screenshot](https://github.com/phw198/OutlookGoogleCalendarSync/assets/49817668/7b082040-b16a-4537-b374-368beb5a9b35)

The error was the same as before:  "Unable to update existing entries in the Outlook calendar.  
Sorry, something went wrong. You may want to try again"

**Steps to Reproduce the Issue**  

Just rerun the sync .      Note:  if I delete the offending Zoom event,  the sync runs to completion.

**Any other information**  
Any additional information that may help troubleshoot the issue.  

Check out this link, which may have nothing to do with this error,  but it sounds like it could be related:
https://devforum.zoom.us/t/major-zoom-gcal-sync-problems-recent-behavior-change/80912

:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13468049/OGcalsync.log)

**Comment by phw198** [comment]
Looks like a bonafide Zoom bug that is corrupted the Outlook appointment - can you even open the item manually, make a minor edit to the location or something and then save it? Does that also error?

Because OGCS is seeing the Outlook item newer than Google, it is trying to compare it - if you manually edit (eg to the location) and save the Google item, then reopen and revert the change, this should make OGCS stop trying to check the Outlook version...it might be a temporary workaround instead of deleting the Outlook item.

You could also assign an excluded category to the Outlook item with the "Delete synced items if excluded" unchecked.

But as you've identified, the root cause is Zoom being dumb...
