### ISSUE TITLE
Application unexpectedly terminated [0x8002802b]

### ISSUE THREAD

**Issue by nebucadneza** [phw198/OutlookGoogleCalendarSync#1821]
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/59419063/c7caa9d0-5d07-493e-8003-1d1b7ce040bf)
I get this Error msg on startup from the application.
I tried to rename the settings.xml.bak thing suggested in another issue but with no success.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Recent alpha releases should [take you to the wiki for your issue](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002802b---type_e_elementnotfound), however.
