### ISSUE TITLE
Automatically detect New Outlook client

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1826]
**Is your feature request related to a problem? Please describe.**
If users try and use OGCS against the New Outlook, it will not work.

**Describe the solution you'd like**
Proactively detect the issue and direct the user to guidance/documentation on what to do if they wish to use OGCS (revert back to "old" Outlook).

**Comment by ninloot** [comment]
I had to install the new Outlook client, but I found as long as the old client is still present, OGCS will connect to it and use it for syncing. This is working fine for me, but I am glad that you had the notice that the new client doesn't work because I was about to uninstall the old client.
The only issue I'm having is that when my calendar reminders pop up, I get on from the old and new client. I haven't yet looked into trying to see if I can configure the old client to not pop-up reminders.

**Comment by phw198** [comment]
Thanks for posting, very useful information 👍🏻

**Comment by TheJacksonian** [comment]
Not sure where to add this comment, but it looks like my work's policy has me switched over to the 'new' Outlook client, if/when you have a portable version for it, I'd be happy to help out with testing if it'd be useful.

**Comment by phw198** [comment]
@TheJacksonian Does that mean the old Outlook client has been uninstalled and/or they've removed the toggle to switch back? 
Either way, having some people up for bleeding edge development builds would be very helpful 🙂 I have something that connects to the cloud Microsoft account and retrieves the calendars - no actual syncing yet, but I could get a build out of just that soon...

**Comment by TheJacksonian** [comment]
@phw198 - I can still switch between the 2, but I am trying to get used to the new one. I find I have to switch to the old one, fire up OGCS then switch back to the new one. As the user above states, it's then a slight issue with the reminders popping up from both.
I'd be happy to try any builds for you, like I say, needs to be portable as my CorpIT team are pretty strict, but happy to try and help if I can.

**Comment by phw198** [comment]
@TheJacksonian #1881 now has the first development build available, if you would like to give it a try? Finger crossed your company hasn't blocked authentication from third party applications...

**Comment by phw198** [comment]
Basically superseded by #1888
