### ISSUE TITLE
 Outlook items would have been deleted, but you have deletions disabled. These are new meetings and should not be delted?

### ISSUE THREAD

**Issue by Billbarasch** [phw198/OutlookGoogleCalendarSync#1849]
**Are you already using OGCS?**
Provide the version number. 2.10.0.0

**Describe the question you have**
I am doing 2 way sync from my outlook local calander and my free gmail calander. 
When I sync I get messages that outlook items would have been deleted, but you have deltions disabled. 

thess items are new and created in outlook and should not be deleted. I did not want them to be deleted.
Why is this occuring 
I have attached my configuration of OGCS

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/168209736/7f9f87f2-014f-4e15-876c-24c0e254fad1)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/168209736/ebd8499b-d205-4fb5-a5dd-19476a8ff2c4)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/168209736/757bbcd5-7583-49c3-bff0-76b52f1bc0b3)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/168209736/9c758bcf-413d-407b-8c53-f5845abdf82c)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/168209736/d4727aa2-a482-4709-9a6d-d6762ca0c6de)

Thanks in advance for help.

**Comment by phw198** [comment]
Items are normally only identified for deletion if they were at some point synced to Google and subsequently deleted from there. There are however, situations where it can happen eg due to declining a meeting invite (which deletes it from Outlook) after it has already synced to Google, the organiser revises the time and it appears in Outlook again.

Simplest option is to upgrade to at least 2.10.2 where when you decline the deletion, it will then sync it to the other calendar instead.
