### ISSUE TITLE
2 requests - visibility and availability setting enhancements

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#186]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/660832" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/fors6630" target="_blank">fors6630</a></strong> wrote at 2017-01-20 15:37:</p><div class="markDownOutput ">I have a request, as follows: <br>
<br>
I am syncing from my Gmail into Exchange so that I have &quot;reminders&quot; of existing commitments in my personal life, before I schedule something for work.<br>
<br>
There are 2 options I need: <br>
1) Always sync all items as private.<br>
2) Always sync all items as free/available.<br>
<br>
Of course for 1 and 2 above, instead of &quot;always&quot; you could have an option for users that is &quot;use the source appointment setting&quot;, but &quot;always&quot; is what I need to both hide and not block my calendar (since work is my top priority,
 at least according to my work exchange calendar).<br>
<br>
Both of these are important, as by default I like to share my calendar at work (and promote transparency).<br>
<br>
If there is any way we could get these options, that would be fantastic. I'm a 20 year IT guy so would be happy to help test or whatever needed.<br>
<br>
Thanks in advance! <br>
Rob<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/fors6630" target="_blank">fors6630</a></strong> wrote at 2017-01-29 17:59:</p><div class="markDownOutput ">Hey @phw198 - I came to see if by chance there was a response here that I missed, but I get it. Life is busy. So I took a chance and downloaded the source code...looks like it will compile on my VS2015 community instance.<br>
<br>
I found the createCalendarEntry() function, and looks like these lines might be the trick if I/we add some config flags / dropdown to the form:<br>
<ul>
<li>ai.Sensitivity = (ev.Visibility == &quot;private&quot;) ? OlSensitivity.olPrivate : OlSensitivity.olNormal;
</li><li>ai.BusyStatus = (ev.Transparency == &quot;transparent&quot;) ? OlBusyStatus.olFree : OlBusyStatus.olBusy;<br>
</li></ul>
I'd be happy to help with this mod, and bring back my old coder days. It's been a while but I think can do this fairly easy. Would you want to email me with some instructions on how best to do this, if you're willing to try to merge this into the main release
 at some point?<br>
<br>
Thanks in advance for all your efforts! <br>
--Rob<br>
</div></div>

**Comment by fors6630** [comment]
So I just upgraded to your latest release and hotfix (2.4.0.2), in order to overcome a issue with repeating events.  Not sure if that was your code or due to the 2 lines I added in my prior comment above.  

I am bummed to see that you have just recently closed this request without discussion.  

The challenge is that: 

1. I need sync from google calendar to work outlook calendar
2. Work outlook calendar defaults to public visibility.
3. I can't have my private life publicly visible at work. 
4. Google calendar doesn't have a default setting for Sensitivity and BusyStatus.  
5. I can't always have my private appointments clogging up my business calendar.  e.g., maybe I want to block out my wife's birthday, so have a reoccuring appointment on GCal.  That is sync'd to outlook/work calendar.  Then, when work must be scheduled on her birthday, I see a reminder (private event showing available, not busy).  After seeing the birthday item on outlook calendar, I either push the work event out, or I override and accept it knowing that I can't take off wife's birthday.  

The only way to accomplish this that I'm aware of, is to have options within the OGCS program to make everything sync'd to default to a given Sensitivity and or BusyStatus.

Is there anyway to get this in, so I don't have to modify code every time?  I was hoping it was a easy option to add in...would be very valuable!

Thanks,
--Rob

**Comment by phw198** [comment]
The ticket's not closed, I think you're getting confused with the "cp-closed" label that signifies that the CodePlex ticket has been updated with the link to the GitHub ticket....which I assume is how you found your way here.

Yes, I will look to get this feature in - you're not the only one asking for it. However, the last couple of months have been consumed with the migration to GitHub (which still isn't complete :disappointed:).

The bit that needs some thought is how to make this work for 2-way sync, or whether to only allow this feature for 1-way...

**Comment by phw198** [comment]
So the first half of your request is now available under a pre-alpha release on issue #2. Let me know how it goes for you!

**Comment by phw198** [comment]
:package: Development build [v2.6.2.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1347292/v2.6.2.5.zip) now available for the Availability feature request ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) and it must be applied over at least v2.6.1).

Note, this is a breaking release for any configuration already set for the Private feature - you may need to reconfigure this. Please let me know how it goes.

**Comment by fors6630** [comment]
This is great news Paul.  I have installed v2.6.2.5, and multiple initial tests I've done looks very good and no issues I can see thus far.  

Thank you very much!
