### ISSUE TITLE
Problem with 2 Accounts Syncing

### ISSUE THREAD

**Issue by calgia** [phw198/OutlookGoogleCalendarSync#1868]
> Checklist:-
> * [ x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x ] Reproduce the issue
> * [ x] Complete the information below
> * [ x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v20.10.4.0  ALPHA
**Edition**: Installed   
**Sync Direction**: O<->G

**Bug Description**  
GMAIL Account "mailadress@gmail.com" and "mailadress2@gmail.com" needed to be synchronised with 1 Outlook Profile.
Only one is working, even https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS is followed.

**Steps to Reproduce the Issue** 
1. Download ALPHA Version
2. Click on the OGCS_Setup.exe
3. open programm
4. rename default profile to mailadressgmailcom
5. Click on "Outlook"
6. Click on the right calendar to be synced to (mailadress@gmail.com is the name)
7. Click on the left at Google
8. Connect and Authorize Google Account mailadress@gmail.com
9. Click "Save" and save it to "C:\ogcs\Calendar1 as settings.xml
10. Click "create profile"
11. rename it to "mailadress2gmailcom"
12. Click on "Outlook"
13. Click in the right calender to be synced to (mailadress2@gmail.com is the name)
14. Click on the left at Google
15. Click and Autorize Google Account mailadress2@gmail.com
16. Click "Safe" and save it to C:\ogcs\Calendar2 as settings.xml
18. Create ogcs_start.bat at folder C:\ogcs
19. Open and Edit file
20. Insert line 1: start "" C:\Users\PLAKA\AppData\Local\OutlookGoogleCalendarSync\app-2.10.4-alpha\OutlookGoogleCalendarSync.exe /s:C:\OGCS\Calendar1\settings.xml /l:C:\OGCS\Calendar1\Calendar1.log
21. Insert line 2: start "" C:\Users\PLAKA\AppData\Local\OutlookGoogleCalendarSync\app-2.10.4-alpha\OutlookGoogleCalendarSync.exe /s:C:\OGCS\Calendar2\settings.xml /l:C:\OGCS\Calendar2\Calendar2.log
22. run bat.
23. Open Systray
24. Click Sync now
25. Click on "mailadressgmailcom"
26. Re-Authorize with "mailadress@gmailcom"
27. Google-Token file is generated at C:\ogcs\Calendar1
28. Open Systray
29. Click Sync now
30. Click on "mailadress2gmailcom"
31. Re-Authorize with "mailadress2@gmail.com"
32. Google-Token file is generated at C:\ogcs\Calendar2
33. at start working, after some time getting issues as shown hopefully in log "calendar2.log" and or "calendar1.log".
34. clicking "Start Full Sync" and or "Start Sync" and getting some problems, not further declared by the software

Google Account Name is at one "Company Name llc" and "Company Name

**Any other information**  
If you wanna connect to the specific computer to check the setup please contact me at any time. we can conneect together over phone, discord, microsoft teams and other similar calling solutions.

We really need assistance because i think we done everything we can do to get it work but it just still not will work.

:paperclip: Attach your `OGcalsync.log` file.
[ogcs_setup_package.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/15418298/ogcs_setup_package.zip)

**Comment by phw198** [comment]
I'm not entirely sure, but I think the problem lies in step 10 and 11 - it sounds like you've created a second profile and then renamed it?

Certainly the two `settings.xml` files you have provided in the ZIP are the same except for the timestamps of when they last synced, plus the Google account connected in both files are the same, which seems wrong. To me it sounds like you should have a single profile defined for each OGCS instance settings.xml file, and each instance should be connected to a different Google account.

* `Calendar1\settings.xml` should have 1 profile with the Google calendar from mailadress@gmail.com that syncing to Outlook calendar A
* `Calendar2\settings.xml` should have 1 profile with the Google calendar from mailadress2@gmail.com that syncing to Outlook calendar B

A thought though - why not just shared Google calendar from mailadress2@gmail.com to mailadress@gmail.com and then just have a single OGCS instance with 2 profiles?
