### ISSUE TITLE
Recurring Outlook series with 100s of exceptions

### ISSUE THREAD

**Issue by HenrikJanPersson** [phw198/OutlookGoogleCalendarSync#1983]
**OGCS Version**: v2.11.0.0
**Edition**: Portable  
**Sync Direction**:  O<->G

**Bug Description**  
I suspect that my OGCS is creating new events in the future for a certain recurrent event, despite exceeding the 180 days into future that is set in the "When" setting. After being away 3w, I realized the synchronization did not finish  within a minute or so as it used to (running OGCS 2.10.x). I tested upgrading, and with 2.11.0.0 alpha it was still not working so I started to look into the log files, which keeps extending with exceptions into the future for a recurrent event, e.g. 
2024-10-01 16:22:49,254 DEBUG 3  OutlookGoogleCalendarSync.Recurrence [931] -  Found Outlook exception for original date 2/14/2029 2:00:00 PM

It seems it has created these exceptions until 2046, that is 22 years into the future. 
**Steps to Reproduce the Issue**  
Not sure why this happens, I would need help debugging this and interpreting the log file for the next steps.

**Any other information**  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/user-attachments/files/17211306/OGcalsync.log)

**Comment by phw198** [comment]
Yes, I've seen this happen for someone else too - or at least, a recurring series in Outlook where apparently _every_ occurrence is an exception to the series, so it ends up with 100s of exceptions. You have the same:-
```
2024-10-01 16:03:51,838 DEBUG 3  OutlookGoogleCalendarSync.Outlook.Calendar [429] -  10/19/2022 2:00 PM (R) => "Division Seminar + Fika Combined "
2024-10-01 16:03:51,839 DEBUG 3  OutlookGoogleCalendarSync.Recurrence [411] -  This is a recurring Google event with 740 exceptions in the sync date range.
```
I don't know the cause of this and I'm not even sure it's anything to do with OGCS, but the end result is that OGCS has to iterate through all 740 items to work out if they are within in the date range for syncing - which the 99% won't be!

Do you own this meeting, or did someone else organise it? If the latter, then I don't believe it could be OGCS that's the cause of this. Otherwise, if possible, I'd suggest you delete and recreate the series and see when/if the problem starts again.

**Comment by HenrikJanPersson** [comment]
The event was owned by another person. Nevertheless, I have now declined the invitation for the entire series and removed all the entries in both Outlook and Google Calendar, which solved the slow synchronization issue. I will request the other person to invite me again and see if it works better next time. I will update here as soon as I know more about the outcome.

**Comment by phw198** [comment]
Before you get them to invite you again, it might be best to ask the organiser if in their calendar they can see the occurrences are all exceptions or not (Outlook calendar shows a circular arrow with a line through it if it is). 

If they are already exceptions in the organiser's calendar, if they then invite you to the main series again, I think it might send invites to all attendees for every exception 😨   See [this post](https://answers.microsoft.com/en-us/msteams/forum/all/removing-exceptions-to-recurring-teams-meetings/0e03e36d-54b9-496b-9c54-8c7f8e5d3588) (yes, it's about Teams, but that's just a layer on top of Outlook really).
