### ISSUE TITLE
Application terminated! The operation failed

### ISSUE THREAD

**Issue by KhrystynaFaryna** [phw198/OutlookGoogleCalendarSync#1993]
**Are you already using OGCS?**
Provide the version number.
 v2.11.0-beta 
**Describe the question you have**

A clear and concise description of your question and what you would like clarifying.
After download, I run the .exe, it opens the ogcs webpage and sometimes tries to start outlook but then crashes with the error message: Application terminated! The operation failed.

I tried reinstalling outlook and ogcs, same error.

**Comment by phw198** [comment]
You've raised a "question" issue and not asked any question. 

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) if you would like the root cause investigated further. Thanks!
