### ISSUE TITLE
Multiple Calendars

### ISSUE THREAD

**Issue by jidewitt** [phw198/OutlookGoogleCalendarSync#245]
I am syncing 3 google calendars to one outlook account with 3 outlook calendars which are not the default calendars, running one instance of the program. I'm having various issues, inconsistently:
1. Calendars are not syncing in the way in which I saved it - one google calendar to one outlook calendar. Only one relationship continued to sync automatically, manual sync is needed for the others. 
2. A google calendar will sync to the 'default' outlook calendar, instead of the way I saved it. 

I have noticed account disconnection in the following ways when self troubleshooting. 
1. my list of google calendars disappears and only the calendar which last sync'd is left. I have to retrieve calendars again and save settings for each relationship. 
2, my list of outlook calendars disappears and only "default"  outlook calendar is left.

This began before the last 2 hotfixes. 

![ogc google settings](https://user-images.githubusercontent.com/29575579/27345858-bcff0856-55b0-11e7-8014-fc7926e2bbab.png)
![ogc outlook settings](https://user-images.githubusercontent.com/29575579/27345859-bcffeb72-55b0-11e7-9c41-751d5c6c61d0.png)

**Comment by phw198** [comment]
Hi @jidewitt,

I think your issue is with "running one instance of the program" and probably misunderstanding how to get OGCS to sync multiple calendars. Currently, although this should be possible, it's not built into the tool - you have to run multiple instances of OGCS in portable mode, one for each calendar you want to sync. Otherwise there is only one `settings.xml` file and it will only remember the last configuration you set.

Take a look at #165 for some users that have been doing this already...
