### ISSUE TITLE
deleting meetings created using a different time zone in Outlook 2016

### ISSUE THREAD

**Issue by mwv333** [phw198/OutlookGoogleCalendarSync#254]
1. OGCS version 2.5.0.0
2. Creating a meeting or meeting request in Outlook 2016 on Office365. Change different time zone. Save or send meeting.  During next Sync, meeting is deleted from my calendar, it's in the deleted folder, but people can still accept it into their calendar.  
3. I've reproduced it a few times.  Meeting or meeting requests sent/saved without the time zone changed aren't being deleted. 

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1116209/OGcalsync.txt)

Love the solution! I've been wanting this type of syncing ever since Google disabled the capability to sync with Outlook - but your solution is so much better.  It would be nice to see this issue fixed since I'm constantly creating meetings in other time zones - if in fact that's the issue.  Thx!

**Comment by phw198** [comment]
It would certainly be strange if this was related to timezone. How are you creating the appointment? Are you copying and pasting an existing one and changing the details?

Also, is it affecting recurring meetings? There are lots of the following errors in your log: `You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.`

I wonder if that error is because you've got Push sync set, and are making changes during a sync. Could you try turning off Push sync and seeing if that helps?

**Comment by phw198** [comment]
@mwv333 Any feedback whether it was Push sync causing the problem?
