### ISSUE TITLE
No syncing, error message upon opening

### ISSUE THREAD

**Issue by natfguest** [phw198/OutlookGoogleCalendarSync#286]
New error message upon opening programme: "COM exception encountered." Happens on every open. Calendars have stopped syncing. 

No OGcalsync.log appears to have been created since 2017-07-24 - I have attached the latest but don't imagine it will be relevant to the new error. 

[OGcalsync.log.2017-07-24.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1196905/OGcalsync.log.2017-07-24.txt)

**Comment by phw198** [comment]
Please could you upgrade to the latest alpha release and then apply the nightly build [v2.5.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1195569/v2.5.2.12.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

**Comment by rjh18** [comment]
I am having the same issue.  Applied the hotfix but now am getting OGCS is unable to communicate with Outlook, possibly due to anti-virus or corporate policies.

**Comment by phw198** [comment]
@rjh18 Are you getting any Outlook security pop-ups and if so are you clicking Approve or Deny?

**Comment by rjh18** [comment]
No just that error message

**Comment by rjh18** [comment]
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1198258/OGcalsync.zip)

**Comment by phw198** [comment]
So are you on a corporate computer? Unfortunately for you, I think OGCS is now reporting the problem properly and there may not be much we can do.

Worth checking what your [security settings](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) are.

**Comment by rjh18** [comment]
Was working prior to today

**Comment by phw198** [comment]
Ok, but you didn't answer my question or say what your security settings are.

What changed today? If you upgraded OGCS, what version worked and at which version did it break? If you didn't upgrade, has your version of Outlook changed, Windows patches been applied, group policies altered...?

**Comment by rjh18** [comment]
I didn't change anything but its possible changes were downloaded.  How do I check the security settings?

**Comment by phw198** [comment]
Sorry, link now updated in previous post. Though I don't think this is where the problem lies as you're not getting a pop-up.

[This post](https://www.codeproject.com/Questions/1150423/Problem-sending-email-through-outlook) has the same issue, which they then also suspect a group policy. This basically means your IT administrators have locked down Outlook more tightly and rendered OGCS unusable for you.

**Comment by phw198** [comment]
@rjh18 I'm thinking it may be possible to make a version of OGCS that works without needing to access the Outlook address book (which is what corporations are likely to block). If you're interested in this and would be happy to test, please follow issue #287.

**Comment by proudot** [comment]
Hi there, Same type of error for me. It stopped working roughly a month ago. I don't think it correlate with an update, but I can try out previous versions.

**Comment by phw198** [comment]
This ticket has become rather confused. @rjh18 and @proudot, I believe your issue is the message:
> OGCS is unable to communicate with Outlook, possibly due to anti-virus or corporate policies.
>Please register your interest on GitHub if you would like to see a workaround provided.

This is covered by issue #287...which unfortunately has reached a dead-end. @proudot if trying previous versions of OGCS still doesn't work (you'll probably get a less pretty error message), then it would seem your IT have also implemented an Exchange policy that prevents OGCS operating properly.

The OP, @natfguest, was having a problem that was not being logged - logging was fixed in an alpha release after v2.5.0. If you are still having the issue after upgrade to v2.6.0, please raise a new issue ticket.

**Comment by proudot** [comment]
Sorry about the confusion, I started a ticket dedicated to my issue.
