### ISSUE TITLE
Errors with permissions

### ISSUE THREAD

**Issue by eoin24** [phw198/OutlookGoogleCalendarSync#312]
Hi

I am using ver. 2.6.1.0. When I go to try and sync, I get this issue. 

"You don't have permission to create an entry in this folder. Right-click the folder, and then click Properties to check your permissions for the folder. See the folder owner or your administrator to change your permissions."

I don't know which folder it is referring to to try and change the permissions for or whether there is a separate issue with how it is set-up.

Cheers
Ian

**Comment by phw198** [comment]
At a guess, the "folder" is the Outlook calendar you're syncing to/from.

**Comment by eoin24** [comment]
I looked at the folder and gave permissions to it but it didn't seem to make a difference. Is there somewhere else I should look re:permissions.

Cheers
Ian

**Comment by eoin24** [comment]
Another question: If I wanted to go back to a previous version of the program that worked, where would I get it if it is available.

Cheers
Ian

**Comment by phw198** [comment]
GitHub releases from v.2.5.1 and above are [available here](https://github.com/phw198/OutlookGoogleCalendarSync/releases).
Earlier versions would be back [on CodePlex](https://outlookgooglecalendarsync.codeplex.com/releases/view/631390).

Though I'm not convinced downgrading will fix this particular issue for you. For example, if you're trying to 2-way sync a shared calendar, I'd likely expect this "error".

:spiral_notepad: As always, [your logfile](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file) is ever helpful in diagnosing the root cause.
