### ISSUE TITLE
Update notification suggests a downgrade and/or misses beta upgrade

### ISSUE THREAD

**Issue by JorisDebonnet** [phw198/OutlookGoogleCalendarSync#313]
I am running 2.6.1 alpha. On startup, it offers an "upgrade" to 2.6.0 beta. 

So I figured, perhaps it's suggesting the highest beta because I'm not on the alpha channel - so I went into settings and told it to 'Check for Alpha releases'. But it makes no difference (after multiple restarts). 

Of course not a show stopper, just a bit weird :) 
![image](https://user-images.githubusercontent.com/3286264/29818071-ec52a0e0-8cba-11e7-8db1-1d39a2babbe7.png)

**Comment by phw198** [comment]
Yes, I noticed this as well, and was kind of hoping it was due to messing around on a VM snapping backwards and forwards.

I think it's a feature of the Squirrel installer. How did you install v2.6.1? If you weren't on the Alpha releases, I'm guessing you went and downloaded the `Setup.exe` for it manually? In which case under `%LOCALAPPDATA%\OutlookGoogleCalendarSync` how many install directories do you have? Just one for the 2.6.1?

Squirrel always expects the current and previous versions (maintained by doing an upgrade within OGCS), so I think it's getting confused. Not sure if this is fixed in subsequent releases of Squirrel...

**Comment by phw198** [comment]
I've also noticed Squirrel can miss available upgrades. Eg running v2.5.0 will only see v2.6.1 (the latest alpha at the time) which will be ignore if the user doesn't want alphas - so no notification about v2.6.0.

**Comment by JorisDebonnet** [comment]
Right now I'm on 2.6.2.0, and I get a notification about the availability of 2.6.3.0 on each startup. That's fine (because I turned on alpha updates), but when I click on "Yes" to download it, nothing happens. So I try to Update via the About tab, but I get the same result. 

So anyway, I just downloaded 2.6.3.0 'manually' and installed it. Of course I can't check now whether that one fixed the issue :) I see the release notice about _"Give user feedback when manually checking for update"_, perhaps that was a related issue.

**Comment by phw198** [comment]
Hi @JorisDebonnet

:spiral_notepad: Could you provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)) for the v2.6.2 upgrade prompts?

**Comment by JorisDebonnet** [comment]
Sent it to your Google Drive.

**Comment by phw198** [comment]
This issue appears to be related, at least in part, to Squirrel/Squirrel.Windows#774

**Comment by phw198** [comment]
Upgrading from Squirrel v1.6.0 to v1.7.8 appears to resolve the downgrade problem.

:thought_balloon: But now possibly hitting Squirrel/Squirrel.Windows#1068 - v1.7.6 seems to be a breaking change for any differential files created prior to that release. May need to only provide full `.nupkg` and not the delta. Will see...
