### ISSUE TITLE
 Google.Apis.Requests.RequestError  Not Found 404

### ISSUE THREAD

**Issue by sclewis23** [phw198/OutlookGoogleCalendarSync#318]
I'm not sure if it is my firewall but i just started getting:
```
Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]
```
Then I get  API rate limit reached. Backing off 2sec before retry. 
This was the first sync of the day.....Haven't tried in a couple days so I would have thought i'm not near my api limit.

**Comment by phw198** [comment]
:spiral_notepad: I'd need your logfile to see in more detail what's happening [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]...but the API **rate** limit means that too many changes are happening in too short a period of time. OGCS _should_ automatically back off and retry, so if that isn't happening, sounds like a bug...

**Comment by sclewis23** [comment]
Paul,
here is the log file uploaded:https://gist.github.com/sclewis23/c2924fa1a56e9d2f714a66334cd0d6b5

Thanks,
Shannon

**Comment by phw198** [comment]
Thanks @sclewis23 

So looks like we've got multiple things going on here! Some questions:
1. Are you a long time user of OGCS? Did these problems start with v2.6.1?
1. Did you at some point have two-way sync going, or synced from Google to Outlook?
1. Have you always synced Descriptions
1. Have you always used the proxy currently configured?

I think the HTTP404 errors when retrieving Google event `sio6eh8n8gfaui6gmj0c0st95o` can be ignored - this likely comes from a 2-way sync, but has since been deleted in Google after reverting to O->G. It will likely fix itself once we can fix the next issue.

More concerning, is 
```
WARNING: Event creation failed.
Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Body()
```
It seems you no longer have rights to see the Outlook appointment body/description. This policy might have been changed by your IT. Could you try unchecking the `Description` option in OGCS, at least temporarily to stop this error?

Last, it seems communication to update Google events is then failing:
```
Doing a dummy update in order to update the last modified date of single instance
WARNING: Updated event failed to save.
Error while copying content to a stream.
```
These feels like a proxy/firewall issue maybe - have you always used the current one configured? Are you able to try OGCS with a direct internet connection?

**Comment by sclewis23** [comment]
I have been using it for a while, but our firewall/proxy was recently updated.
I went ahead and removed my google calendar and let it sync again with description off.
I did create all entries, but it seems to have to created 4 calendar entries for each.
I also get a pop window indicating a popup error saving, I just click OK to continue.

**Comment by sclewis23** [comment]
I updated the issue and here is a link the new log.https://gist.github.com/sclewis23/27080a62d1812a253e387a76c46d2fe0

Thanks

**Comment by phw198** [comment]
Unfortunately for you, it seems your firewall is [wreaking havoc](https://gist.github.com/sclewis23/27080a62d1812a253e387a76c46d2fe0#file-ogcalsync-log-L291-L332) - when OGCS tries to talk to Google to create the events, you're getting back from ForcePoint `Access to this site is blocked`. 

Your log file's full of this error...I'm kinda surprised it managed to create any events at all in Google, let alone 4 duplicates. But if the firewall is randomly blocking certain activities (the delete worked and the retrieval of events works...mostly), then I think you're dead in the water. :skull:

I'm guessing ForcePoint is also blocking your ability to retrieve the description of the Outlook items too. Seems either like a horrific product, or not properly configured.
