### ISSUE TITLE
Outlook uses Kolkata, Google still uses Calcutta - leads to constant entry update

### ISSUE THREAD

**Issue by b0ssman** [phw198/OutlookGoogleCalendarSync#349]
Hi

I do one way sync outlook -> Google.
It seems OutlookGoogleCalendarSync compares the entries between outlook and google and then before updating google changes the events based of timezone or rules.
This way the same entries are always found to be different.

Example:
20.09.2017 08:00 => "Sprint 15 - Internal review - Pending stories"
Start Timezone: Asia/Calcutta => Asia/Kolkata
End Timezone: Asia/Calcutta => Asia/Kolkata
2 attributes updated.

25.09.2017 => "workplace"
Reminder: 10 => removed
1 attributes updated.

These and others appear with the same difference on every sync.

**Comment by phw198** [comment]
No, it doesn't work like that - it only compares events that are more recently modified in Outlook than Google. So the question is, why are the updates not being saved to Google? 

Do you have the OGcalsync.log file to upload?

**Comment by b0ssman** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1339565/OGcalsync.log)

**Comment by phw198** [comment]
The Calcutta vs Kolkata timezone appears to be a bug with Google - [I've logged this with them](https://issuetracker.google.com/67170002). 

Because Google is stubbornly continuing to use Calcutta, when OGCS asks it to update _only this attribute_ to Kolkata, it ignores the request which means the `Updated` timestamp doesn't change - which is what is required to stop it being compared again on subsequent syncs.

:package: Meanwhile, I've coded a workaround - please try [hotfix v2.6.2.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1346791/v2.6.2.4.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Let me know how it goes and if you're still seeing problems with the reminders keep syncing.

**Comment by b0ssman** [comment]
[OGcalsync2.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1348047/OGcalsync2.log)

the Kolkata difference is gone.

the dnd reminder removal is still there. These are still updated on every sync.
```
27.09.2017 => "[myPlace] workplace M-3-4-02/4 Munich"
Reminder: 10 => removed
1 attributes updated.
02.10.2017 => "[myPlace] workplace M-1-4-07/2 Munich"
Reminder: 10 => removed
1 attributes updated.
25.09.2017 => "[myPlace] workplace M-1-4-07/2 Munich"
Reminder: 10 => removed
```

**Comment by phw198** [comment]
Hi @b0ssman 

Could you check if you have a default 10 minute reminder set on your Google calendar (check in the web app)? I suspect this needs removing in order to stop OGCS keep resyncing. If you don't have a default, could you raise a new request to cover it please?

**Comment by b0ssman** [comment]
removing the default reminder worked. maybe a notification in the app about it would be useful.
