### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by erasure** [phw198/OutlookGoogleCalendarSync#361]
Not sure when this issue started; it has been happening for a few weeks I think. I am actually running two instances of the portable version, 2.6.2.0. One instance works fine; however, the other instance has begun throwing 403 errors. Specifically: 

A dialog pops up saying "Deleted Google event failed to remove. Continue with synchronisation?"
If I say yes, all of the remaining deletions and additions also fail, with the same message (for additions it says "New Google event failed to save. Continue with synchronisation?"). 
If I say no, it simply aborts the sync process (as it should). 
In the Sync tab, it says this for every failed deletion/addition: 
```
WARNING: Deleted event failed to remove.
_{OR: WARNING: New event failed to save.}_
Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
	Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]
```
I've confirmed that all the settings in the app are the same, other than the specific calendars that are syncing. Given this, I'm guessing the issue lies in the specific calendar that's being synced? Not sure where to look for the problem that I need to fix though...

**Comment by phw198** [comment]
Are you running the portable version with the `Make application portable` option checked? If so, for the OGCS application that has the problems, try disconnecting your Google account and re-authorising it again.

:spiral_notepad: If that still doesn't work, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by erasure** [comment]
Hmm. I disabled the Make application portable option. I just realized though, that when I change the settings in one instance, they also change in the other instance... are the settings being saved in the same place?

I tried disconnecting the Google account and re-authorising, and the localhost page didn't ever finish loading; it just kept spinning forever. I told OGCS to retrieve the calendars anyway and it appeared to do so. 

No matter which instance I run, when the settings say to sync my default (outlook) with my google personal calendar, it works fine. When I change the settings to sync to the Sudbury-Hudson (outlook) calendar with the S-H google calendar, I get the 403 error in both instances. Here's the log. 

https://gist.github.com/erasure/241ef3b44786c96052f0f430db439faa

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1379626/OGcalsync.txt)

**Comment by phw198** [comment]
Yes, if you disable the `Make application portable` option, then the instances will share the same settings. I think you had it right to checked.

Very odd that only G > O errors - pretty sure it's the same code to retrieve Google events syncing either way, but I'll take a look.

**Comment by erasure** [comment]
Oh, I think I misread your original message and thought you were saying the Make application portable setting could be part of the problem. I've re-enabled it, and then reconnected the Google account, and tried to sync again. Interestingly, I have made additional deletions since then and one of them did sync! Maybe there is something wrong with the particular events I am trying to delete? Here is a new log. 

Edit: Actually, nevermind, I misread the log. Maybe the new log is useful anyway.

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1382866/OGcalsync.txt)

**Comment by phw198** [comment]
So, I think when you set the app as not portable, the two instances of OGCS were fighting. The log file you uploaded on 12 Oct shows the number of items it's seeing in your calendar flicking back and forth on each sync - all rather confusing.

With your last log file there isn't much history, but I'm wondering...is the calendar you're syncing to owned by you or shared with you from another account? If the latter, has the owner reduced your rights to just "See all event details"??

**Comment by erasure** [comment]
I think you're right about the two instances fighting. I've changed that back now. Excellent question about ownership of the calendar.... It is a shared calendar that I created in Outlook. I haven't changed the permissions settings recently, but perhaps our IT department quietly distributed some blanket settings? I will check the settings when I am back in the office Monday.

**Comment by phw198** [comment]
I meant the Google calendar permission settings, but worth checking Outlook as well.

**Comment by erasure** [comment]
Sorry for the radio silence! Had an insane deadline at work last week and finally out of the woods now. Took another look at the Google settings and I think you were right! Somehow the share settings were locked down and it is now syncing fine. Thanks for helping me work that out!

**Comment by leaskovski** [comment]
@phw198 I seem to be having this same issue on my account.  I have been using the tool to sync my google calendar to outlook, but now I am trying to use the two way sync and sync outlook back to google.

I am running  a modified version (very basic, 2 lines of code change) of the utility to write a category to outlook entries (I can then filter these out on the sync to google), and to write a colorID to the google calendar entries.  I don't believe these mods break the sync.

Anyway, this is the error I am seeing in the logging:
```
2018-04-05 20:51:09,635 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Saving timestamp when OGCS updated event.
2018-04-05 20:51:09,840 WARN  8 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
	Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]

2018-04-05 20:51:09,840 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  This error seems to be a new transient issue, so treating it with exponential backoff...

```

Let me know if you want a clean log file, and what logging level you want.

This is against my account calendar, which is shared with the wife, but its mine.

I managed to get it to work once, but now its not working again.

**Comment by leaskovski** [comment]
Some more details on this.  I used the Google API "Tester" at https://developers.google.com/calendar/v3/reference/events/delete to try and delete one of the events that looks to have a problem during the sync:
```
2018-04-05 20:46:07,118 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Found a master Outlook recurring item outside sync date range: 14/08/2014 16:00 (R) => "Communications Portal and CTI Connect NPI meetiing"
2018-04-05 20:46:07,246 DEBUG  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving specific Event with ID vdqehb0g85o4i0lkpfiojebpt0
2018-04-05 20:46:07,465 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Found single hard-matched Event.
2018-04-05 20:46:07,477 WARN  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Found Google item missing Outlook IDs (outlook_GlobalApptID|outlook_CalendarID|outlook_EntryID). 01/01/2000 (R) => ""
2018-04-05 20:46:07,477 INFO  6 OutlookGoogleCalendarSync.Recurrence [0] -  Adding Outlook IDs to Master Google Event...
2018-04-05 20:46:07,493 DEBUG  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Saving timestamp when OGCS updated event.
2018-04-05 20:46:07,808 WARN  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
	Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]

```
I got the eventID and used my calendarID (email address) and tried to delete it (my sync isn't trying to delete, but update it as I have deletions disabled), and it gave me the following error:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}
```
So I think that is what I am seeing and why the sync fails to add entries to google.  The utility is finding existing entries for the items it is trying to sync.  Interestingly enough, I looked for that event title, and the search doesn't find it.  I have also emptied my bin in google calendar, so its not there.  If I use the API Tester to find that event, it comes up with:
```
{
 "kind": "calendar#event",
 "etag": "\"3045697968635000\"",
 "id": "vdqehb0g85o4i0lkpfiojebpt0",
 "status": "cancelled",
 "updated": "2018-04-04T14:59:15.894Z",
 "start": {
  "date": "2000-01-01"
 },
 "end": {
  "date": "2000-01-01"
 },
 "recurrence": [
  "RRULE:FREQ=DAILY;COUNT=1"
 ],
 "transparency": "transparent",
 "iCalUID": "vdqehb0g85o4i0lkpfiojebpt0@google.com"
}

```
So the entry exists, just cannot be seen by google.  What I expect has happened, is that I did a test sync, and manually deleted the entries it created, and this hasn't actually deleted those entries as now they are floating.

Any ideas?  I can't delete them, nor can they be updated.

Edit:
Looks like this is related to:
https://stackoverflow.com/questions/23418429/google-calendar-api-returns-events-that-no-longer-exist

> You can .setShowDeleted 'false' in the request. Example Java:
> 
> Events events = calendarService.events().list(PRIMARY_CALENDAR_ID)
>                 .setShowDeleted(false)
>                 .setPageToken(nextPageToken).execute();
> But note also that:
> 
> Cancelled instances of recurring events (but not the underlying recurring event) will still be included if showDeleted and singleEvents are both False.
> 
> For further reading see https://developers.google.com/google-apps/calendar/v3/reference/events/list

Edit2:
What looks to be happening is that it finds the master google event for the re-occurrence and that turns out to be cancelled, but also see's that it is missing an outlookID on it, so trys to add the ID, which fails.

What looks to be happening is that previously sync'd items to google that I cleared out to "start again" are getting found because google events don't actually ever get deleted.  As my bin is empty, they can't be restored, so its almost like it needs to ignore a cancelled event when it tries to find a previous sync'd item.

**Comment by phw198** [comment]
Hi @leaskovski 

Apologies for missing your posts - I hadn't spotted them as the Issue was closed. 

> What looks to be happening is that it finds the master google event for the re-occurrence and that turns out to be cancelled, but also see's that it is missing an outlookID on it, so trys to add the ID, which fails.

This certainly sounds more than plausible, though I'm struggling to recreate the situation that surfaces the problem. I've tried:
1. Create a recurring series in Outlook that starts before the date-range window that OGCS is configured to sync
1. Sync one-way G->O
1. Delete the first occurrence of the series in Google - have tried deleting this instance only; this and following instances; whole series but doesn't make a difference
1. Sync one-way G->O

I would expect this to cause the 403 Forbidden, but it doesn't. Are you able to reproduce the problem?
