### ISSUE TITLE
Sync from Outlook to Google is not working for meeting where I'm the inviter

### ISSUE THREAD

**Issue by IngolfE** [phw198/OutlookGoogleCalendarSync#363]
all meetings are sync'd fine but the ones where I invited others (issue is still in v2.6.2)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1375210/OGcalsync.log)

**Comment by phw198** [comment]
You have 2-way sync configured and delete disabled. Is it not possible that 2 Outlook items that are not syncing to Google, did sync initially but you then manually deleted them from Google?

If so, then it would be expected behaviour for them not to sync to Google again - in fact they should be deleted from Outlook, but that won't happen with deletes disabled.

If you want them to sync again to Google, you'd need to temporarily turn on 1-way sync from Outlook to Google.

**Comment by IngolfE** [comment]
Hi Paul
No, nothing deleted manually before.
Ich did try now with single direction Outlook 2 Google, nothing. All
meetings that I created and I'm the inviter are mit sync'd
It's reproduceable too.
Regards
Ingolf

**Comment by phw198** [comment]
Similarity with #400, though this is reporting the meeting is created but not subsequently updated.
