### ISSUE TITLE
Unable to authenticate with Google.

### ISSUE THREAD

**Issue by jmathis0517** [phw198/OutlookGoogleCalendarSync#376]
|Question|Answer|
|:---|:---|
|OGCS version | v2.6.3.0 |
|Portable|

**Expected Behaviour**  
See [New Text Document.txt]

**Actual Behaviour**  
Object reference not set to an instance of an object.

**Steps to Reproduce the Issue**  
1. Step 1 Start Sync
1. Step 2 Re Start Sync

**Any other information**  
Went to Settings, Google, Disconnect Account, Retrieve Calendars and would not retrieve. Had to go back to v2.6.0.0 to get Retrieve Calendars to work. Could go to v2.6.2.0 and syncing worked.
as seen in:
 [New Text Document.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1427828/New.Text.Document.txt)

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1427781/OGcalsync.log)

**Comment by phw198** [comment]
Looks like we might have a regression of bug #305. I'll take a deeper look in a bit.

**Comment by phw198** [comment]
> Looks like we might have a regression of bug #305. I'll take a deeper look in a bit.

Yup, please try the [new ZIP file](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.3-alpha/Portable_OGCS_v2.6.3.zip) (specifically the `OutlookGoogleCalendarSync.exe.config` file within it).

**Comment by jmathis0517** [comment]
This seems to have fix the problem. 

Thanks

**Comment by Nikers** [comment]
Hello.
I've the same problem since Monday 21 of august 2019.
Use OGCS 2.8.1.0 Alpha

I've disconnected and reconnect my account and, at every sync attempt, a web browser open to ask google to athorize OGCS to access my account and a warning page "This application is not yet validated by Google". I autorize my calendar access but sync fails !

Join my OGCalsyn.log file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3524076/OGcalsync.log)
