### ISSUE TITLE
ZHPCleaner detects Adware Pirrit

### ISSUE THREAD

**Issue by Billthebutcher** [phw198/OutlookGoogleCalendarSync#426]
**OGCS Version**: v2.6.0.0  
**Installed or Portable**: Installed

**Problem Description**  
My issue is not related with any bug in the program itself, which I use thanks to you the developers, but it "worries" me the fact that the maybe overzealous ZHPCleaner reports "Adware Pirrit" in the program.
![zhpcleaner](https://user-images.githubusercontent.com/35198839/34652734-1100498e-f3da-11e7-84d4-38157adfeb89.jpg)
Can you please check and clarify the issue?
**Steps to Reproduce the Issue**  
[https://www.nicolascoolman.com/download/zhpcleaner](url)

Thanks a lot.

**Comment by phw198** [comment]
Thanks for reporting, though I have little time for these dumbass cleaners and AV tools. :angry: [Apparently](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Adware:Win32/Pirrit) Pirrit "shows you ads as you browse the web." - what, like Google does?!

I've stuck to my guns about no advertising and no premium features in OGCS and it's really not making ads magically pop up anywhere. OGCS does pick up your system/IE proxy settings in order to connect to the internet, but it never changes them.

Hmm....on closer inspection of your screenshot, I notice the files it's reporting in your screenshot are ones generated by the GitHub Squirrel installer. The actual OGCS program file is at `C:\Users\<username>\AppData\Local\OutlookGoogleCalendarSync\app-2.6.0-beta\OutlookGoogleCalendarSync.exe`. 

The fact it's not complaining about this one tells me it doesn't like the Squirrel files for some reason. I'm not really bothered why; Squirrel is Open Source and was recommended by GitHub and CodePlex ([Microsoft](https://codeplex.codeplex.com/wikipage?title=Migrating%20to%20GitHub) - see "What's Next" section at the bottom). Ask Nicolas Coolman :stuck_out_tongue_closed_eyes:

**Comment by Billthebutcher** [comment]
Thanks for clarifying the issue. Time to ask Coolman. ;D
