### ISSUE TITLE
Repetitive syncing

### ISSUE THREAD

**Issue by LHuisingh** [phw198/OutlookGoogleCalendarSync#429]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.5
**Installed or Portable**:Portable

**Problem Description**  
Noticed sync had not run for a while. Started a manual sync and it finished with success. However, it started syncing again and again.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
Sync set for hourly update plus push. Log file posted to CloudWok.

**Comment by phw198** [comment]
So the first issue I can see in your logs is that you have more than one instance of OGCS running at the same time.
`The process cannot access the file 'C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user' because it is being used by another process.`

This certainly won't help, and your logfile shows two different processes updating, so it's very confusing to read through. Try a clean restart of your computer and make sure you only get one instance of OGCS running - also check in your Task Manager there's only one OutlookGoogleCalendarSync.exe process.

If more than one OCGS opens on startup, it might be that you have multiple installs - check the Control Panel.

**Comment by LHuisingh** [comment]
I've been just copying new versions of the portable app into a new folder
each time and then launching the latest version of the app after exiting
the app.  I just checked after a reboot and it seems to only be doing one
sync now.  i'll keep an eye on it.

Thanks.

Larry

*Larry Huisingh*

**Comment by LHuisingh** [comment]
I have seen some instances where there are multiple instances of the
application running but only one icon in the system tray.  It seems like
sometimes an instance can be running but not have an icon in the system
tray.  Is there a way to have the application not run if there is an
instance already running for the current user?  i know I have done
applications that implement this.

*Larry Huisingh*

**Comment by phw198** [comment]
Preventing more than one running instance of OGCS - a possible enhancement to enforce after #165.

**Comment by phw198** [comment]
I think this issue was likely the same as #425, which is now resolved.

**Comment by LHuisingh** [comment]
How do I tell which version has that fix in it?

**Comment by phw198** [comment]
The latest alpha - v2.7.1

**Comment by LHuisingh** [comment]
I am running 2.7.1.0

I am able to run 2 instances of OGCS at the same time. Perhaps this version
doesn't address this issue?

Larry Huisingh

**Comment by phw198** [comment]
You'll see the fix I was referring to in #425 was about repeated syncing, not multiple instances of OGCS (which I do not want to prevent yet at least).
