### ISSUE TITLE
Deleting in Outlook while it should sync to Google

### ISSUE THREAD

**Issue by bjornpijnacker** [phw198/OutlookGoogleCalendarSync#433]
**OGCS Version**: v2.6.0.0 
**Installed or Portable**: Installed

**Problem Description**  
I added three events in Outlook. Upon looking in my calendar later the events were gone. I checked OGCS and it said it deleted the events. These events should have been synced to my Google but instead they were deleted from my Outlook

**Steps to Reproduce the Issue**  
1. Create event
2. Sync
3. It deletes the events in question

**Any other information**  
[OGcalsync - 2018-01-16.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1637012/OGcalsync.-.2018-01-16.log)

**Solution**
I figured it out by testing a little and reading the "all" debug setting. Apparently it doesn't like when you copy and paste appointments. It said "Organiser changed time of appointment." for every appointment that wad deleted during the sync. Please fix?

**Comment by phw198** [comment]
Should already be fixed, just not in the Beta which is pretty old now - planning on releasing the next Beta this weekend.

:arrow_double_up: Otherwise, upgrade to the latest alpha release by [downloading its `Setup.exe` file](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.5-alpha/Setup.exe) and running it.
