### ISSUE TITLE
Corporate Policy? causing HRESULT: 0x80004004 on recurring entry comparison

### ISSUE THREAD

**Issue by Pedler7** [phw198/OutlookGoogleCalendarSync#436]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1640032/OGcalsync.log)

----

**OGCS Version**: v2.6.6.0  
**Installed or Portable**: Portable

**Problem Description**  
\Sync in any direction works and seems to complete successfully, but generates an error, I believe when it is comparing recurring entries. Description Sync is unchecked.  Log Attached, this is almost certainly related to Issue #287 because I am operating in a similar environment.

**Steps to Reproduce the Issue**  
1. Auto or Manual Sync (Other than first sync)

**Any other information**  
\

**Comment by phw198** [comment]
Yes, almost certainly an issue due to corporate policy, with an access denied when OGCS tries to access the body of your Outlook appointment.

Given you say that `Description` is not selected for sync, this is a bug.

:package: Please check if this is resolved with [hotfix v2.6.6.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1640847/v2.6.6.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by Pedler7** [comment]
Thanks Paul, after a few runs, it looks like this fix works smoothly. I appreciate the quick turnaround and your continued efforts on this project.

**Comment by phw198** [comment]
Ah, you got in there rather too quick! Some further tweaks in [v2.6.6.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1640889/v2.6.6.2.zip) if you'd be kind enough to test that too...

**Comment by Pedler7** [comment]
Thanks Paul, I did have a sync error overnight with 2.6.6.1, I'm now running 2.6.6.2 which seems to be running smoothly. I'll let you know if any other errors pop-up.
