### ISSUE TITLE
Problem with event deleted after sync - Apple iCloud changes immutable ID

### ISSUE THREAD

**Issue by Lorenzo-81** [phw198/OutlookGoogleCalendarSync#447]
Hi, 
I have this problem. I'm using my phone (Samsung) to put in google calendar the event. The OGCS sync  on Microsoft Outlook ( version 2010 - 32bit ) the event without problem, but at the second sync OGCS delete first of all from GOOGLE and after that from Outlook. I using the setting in the picture below
![image](https://user-images.githubusercontent.com/35970375/35582183-54a92630-05ee-11e8-8285-bca46bc4053c.png)

Please help me, thanks.

My OGCS version is 2.7.0.0, but this problem is present also in the previous version.

Thanks a lot

**Comment by phw198** [comment]
And can you replicate this issue by creating the Google event in https://calendar.google.com instead of your Samsung phone?

**Comment by Lorenzo-81** [comment]
Yes the problem is same. I discovered today the problem. Is the settings of "show me as". If you create the event on google calendar app or web or via samsung calendar, of default setting it on busy. But when the OGCS sync with outlook set it on available. There is the problem, infact when OGCS re-sync, first of all, delete the event from Google after that from Outlook. I tried to create an event from google and set to available, and all sync is ok

**Comment by Lorenzo-81** [comment]
I've an update. The problem is already appear ... I tried with busy and available, but it's same problem. Look the picture below.
![image](https://user-images.githubusercontent.com/35970375/35677586-7e2f355e-0750-11e8-90c6-8f1414bdab9e.png)

I changed the direction setting from outlook to google and the result is that OGCS create another two events with same entries.

**Comment by phw198** [comment]
Yes, I don't think the busy/available setting has relevance here.

Are you manually creating the new entries in Google from scratch, or duplicating an already existing Google event that's previously been synced by OGCS?

**Comment by Lorenzo-81** [comment]
I tried both mode. And the problem is same. OGCS sync at first and the second sync delete the event, first of all from Google and after from Outlook. Below the settings of Outlook
![image](https://user-images.githubusercontent.com/35970375/35694484-cf7ab68c-0781-11e8-8fa4-3d1d14ec26c4.png)

**Comment by phw198** [comment]
Please could you apply the below build and then turn on `Create CSV exports` in OGCS application behaviour settings. This will create various CSVs (in the same directory as your `OGcalsync.log` file) of the items being synced.

I'm suspecting that the ID of the synced iCloud item in Outlook is changing between when it is saved there by OGCS and when the next sync occurs, which causes the match to fail and because you have two-way sync on, resulting in the deletions.

You'll need to capture the CSVs after the first successful sync (eg ZIP them up) and again after the next sync where it wants to delete the Google item. Please could you then upload those two sets of CSVs - no problem to delete all the other lines and just leave your test case).

:package: [v2.7.0.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1691879/v2.7.0.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by Lorenzo-81** [comment]
Hi Paul


on the attached the zip file, with inside the csv file. Below the legenda of extension:


_1 input on Outlook the event created on Google

_2 ok sync

_3 delete from Google the event

_4 delete from Outlook the event


Please let me know


Thanks


Lorenzo

**Comment by phw198** [comment]
:paperclips: Sorry, files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by Lorenzo-81** [comment]
ok 
[google_create.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1706675/google_create.zip)

**Comment by Lorenzo-81** [comment]
Hello, 
I looked the link, but which is the operation ? Save files ? And if is yes, where is the position of file on the pc?

**Comment by phw198** [comment]
Hi, what link are you referring to? The code commit I made yesterday doesn't require any action on you, it's just me changing the code behind OGCS as related to this issue.

However, once I've released the next beta release (v2.7.1) I'll need you to upgrade and produce the CSVs again - including the Outlook CSV files as these are likely more important than the Google CSVs you zipped up before.

**Comment by Lorenzo-81** [comment]
ok, perfect. When will the beta version be available? ? I needed to solve this problem. Thanks a lot

**Comment by phw198** [comment]
Sorry I meant alpha (not beta) and it's available now. 

:arrow_double_up: Upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`.

**Comment by Lorenzo-81** [comment]
Hi, I've upgrade this morning, the version, but the problem is same. 
Attached all the file create, from Google and Oultook
[event.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1727906/event.zip)

**Comment by phw198** [comment]
Thanks for that. So I've followed through the various files and confirmed that unfortunately, the "Global ID" of the Outlook items changes _after_ it's been saved.

On creation in Outlook (having been synced from Google), it's value is (I've added the asterisks):  
`040000008200E00074C5B7101A82E00800000000**700DCFC06CA6D301**0000000000000000100000007B50203616522240BE1758D033C69C7A`
Where `700DCFC06CA6D301` is the time it was created and the end of the code is the unique code.

However, on the next sync, the Outlook ID for the same item has now changed:
`040000008200E00074C5B7101A82E00800000000**0000000000000000**00000000000000002F0000007643616C2D55696401000000343434372D30374532303230462D303231372D304433352D464632322D303037334100`
You can see the timestamp code has been zeroed out(!) and the unique code after it is completely different and much longer.

The problem is, as per the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/ee157690%28v=exchg.80%29.aspx), "After it [the ID] is set for a Calendar object, the value of this property MUST NOT change." So given it appears Apple aren't following this, there's nothing I can do to prevent subsequent deletions - OGCS is built on the assumption other calendar providers will follow the rules as specified by Microsoft.

One way sync with iCloud is going to be the only supported method using OGCS, I'm afraid.

**Comment by Lorenzo-81** [comment]
ok, thanks for the information.

**Comment by Lorenzo-81** [comment]
Ok, only one doubt, relatively of your information about the sync. 
The question is, but if you deleted the same event from google and outlook, you can match the same value. If the code is different, the OGCS, should be create a duplicate event both google and/or Outlook, but don't delete it. I don't understand why OGCS deletes the event both google and Outlook.

**Comment by phw198** [comment]
Because you have two way sync configured.

When OGCS creates the Outlook item or syncs it to Google, it stores the outlook ID. When the Outlook ID changes (which it never should) Google can no longer find the Outlook ID in Outlook so interprets that as you deleting it in Outlook...and it replicates that in Google. Now Outlook, which also knows about the Google item (whose ID never changed) sees the delete and replicates that also in Outlook.

There is an outside chance I can improve this to also check the Google IDs during two way sync (which isn't changing) and rely on that instead/as well - but I don't have time to investigate further for a few days at least...

**Comment by phw198** [comment]
:package: OK, could you try [v2.7.1.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1756679/v2.7.1.2.zip) and see if that copes better ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix))?

Let me know how it goes...

**Comment by Lorenzo-81** [comment]
Hi, for the tests that I made, the problem is solves !!! Thank you so much.
