### ISSUE TITLE
OGCS Crash - cannot disconnect account

### ISSUE THREAD

**Issue by dartstryker** [phw198/OutlookGoogleCalendarSync#457]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  YES V. 2.7.0.0
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1695949/OGcalsync.txt)

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
Hello, I cannot disconnect my google account. when I try, I get the following error:
![image](https://user-images.githubusercontent.com/36165846/35816581-5b9869a4-0a9b-11e8-8f48-8d0e7697b2a7.png)

after this, OGCS crashes and closes. I cannot check for updates either by the way.
I am behind a script-based proxy, it worked fine right up to the latest Windows 10 update then stopped (I also use CNTLM for other programs which also stopped working, so I cannot direct the proxy configuration ).
I use IE settings in OGCS, and IE successfully connects to the internet.

Any ideas on how to fix the issue, or any further information I can send to help investigate?
thanks and regards

David

**Steps to Reproduce the Issue**  
1.Open OGCS
2. Disconnect Google Account
---> Crash

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:package: @dartstryker Whilst this [v2.7.0.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1701316/v2.7.0.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) should stop the crash but, as you suspect, the real issue is your proxy - you're getting 407 blocked for everything.

I've not any first hand experience of CNTLM, so you're ahead of me here - but if you have other applications that have also broken as a result, then this doesn't look good :slightly_frowning_face: 

I don't know if it helps, but you can see the proxy authentication challenge HTML in the OGCS log file...and Googling "McAfee Web Gateway cntlm" brings up a fair amount of stuff (I'm sure you've done that already).

If you're able to confirm the lack of crash on the `Reset` button, I can at least get this rolled into the next release...

**Comment by dartstryker** [comment]
Hello,
thanks for your reply and quick fix
Actually, your fix solved the whole issue!

I used the IE proxy settings, as before, and it successfully un-synced my Google account. after re-syncing it, I was able to perform a full calendar update and, for now, everything appears to be working fine.

many thanks, and please include this fix in your next release!

cheers
david

**Comment by dartstryker** [comment]
(sorry, closed by mistake)

**Comment by phw198** [comment]
That's great news!
