### ISSUE TITLE
Recurring series exception not syncing when deleted

### ISSUE THREAD

**Issue by thegiraffeprincess** [phw198/OutlookGoogleCalendarSync#459]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
When declining an invitation in Outlook (after it has been accepted previously) it does not delete from the Google calendar. Is there a fix for this please?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Uncheck `Disable Deletions`?

**Comment by thegiraffeprincess** [comment]
@phw198 thank you for the suggestion. this has already been unchecked but I checked it to run a sync and then unchecked it an ran a sync but it does not remove the deleted / declined events.

**Comment by phw198** [comment]
You didn't provide any of the information requested in the Issue template. What version of OGCS are you running? 

:spiral_notepad: Once you have made sure it is v2.7.0, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)) and mention the subject of the item you are expecting to be deleted so I can investigate further...

**Comment by thegiraffeprincess** [comment]
Hi @phw198 
I am running 2.7.0.0 and here is the log file - https://gist.github.com/thegiraffeprincess/5eb40f61f5fa78643491b9e6eefb7679 
One of the items I am trying to delete is called "FW: Nandos" dated 09-02-2018 and it is a reoccuring weekly event, however some of them have been declined. 
Thank you :)

**Comment by phw198** [comment]
It looks like you have two recurring events both starting on 9/01/2015 - one called "Nandos" and the other called "FW: Nandos". The former one has correctly deleted the event in Google on 9/02/2018, and the latter one is getting confused with the former.

So I'm wondering if you can confirm if you've got two of the same series in Outlook and whether you can delete the forwarded one?

**Comment by thegiraffeprincess** [comment]
Hi @phw198 i have deleted the forwarded instance from the google calendar but it is not syncing the normal "Nandos" event. I also have a reocurring "Lunch Walk" event on 12 Feb 2018 which has been rescheduled to 26 Feb which is not syncing across. 

Latest log file is here - https://gist.github.com/thegiraffeprincess/14480926b491ff40889507184c890668

**Comment by phw198** [comment]
I actually meant to delete the forwarded Nando's event in Outlook (and let OGCS delete the series in Google). However, as your sync date range is from 11/02/2018 to 14/04/2018, the exception we were originally looking at is now outside of that, so it doesn't sync:
`Exception is deleted and outside date range being synced: 09/02/2018`

For the Lunch Walk, OGCS [has seen the change](https://gist.github.com/thegiraffeprincess/14480926b491ff40889507184c890668#file-ogcalsync-log-L2047-L2056) but I think it's hasn't synced it because the modified date of Google's version is newer than Outlook. I actually put a patch around this problem in v2.7.1 which with any luck will solve this for you.

:arrow_double_up: Please upgrade to v2.7.1 by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`.

**Comment by thegiraffeprincess** [comment]
hi @phw198 
the aplpha release appears to be working and fixed the issue. 
Thank you so much!

**Comment by phw198** [comment]
Thanks for confirming it's fixed @thegiraffeprincess
