### ISSUE TITLE
Outlook Shared Calendar Picker Issue & Date Format Issue

### ISSUE THREAD

**Issue by dumbwithdata** [phw198/OutlookGoogleCalendarSync#465]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1717943/OGcalsync.txt)

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I have had (2) issues setting the program up;
(1)  If I choose a shared calendar under the Outlook portion, I get a pop-up from Outlook for selecting a contact.  I assume that this pop-up should show me my public folder structure but it does not.
(2) Though I need to resolve (1) so I can access the proper calendar, I have tried to move forward with my default calendar.  I get  zero results when I test the Regional Date Format.  I have tested all of the standard varieties and have also reviewed exactly what Outlook is showing and replicated this but to no avail.  Not sure where I am screwing up.

**Steps to Reproduce the Issue**  
1. No steps needed because happens every time I try to set-up the program.
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Hi @dumbwithdata 

The 1st issue won't show a public folder structure, it will show your Outlook address book in order to pick the contact of the person who shared a calendar with you. Having done that, you would pick their calendar you want to sync from the calendar dropdown box.

The 2nd issue is always related to [Outlook's date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items), but your logfile only shows you starting OGCS up, not performing any tests with different formats...
