### ISSUE TITLE
Multiple Entries created/delete partially working

### ISSUE THREAD

**Issue by tljwy** [phw198/OutlookGoogleCalendarSync#469]
:bulb: Multiple events created in Outlook despite settings

I am using the alpha that was available on 14/Feb
----

**OGCS Version**: v2.7.7.0

Running From | C:\Users\tamaraj\AppData\Local\OutlookGoogleCalendarSync\app-2.7.0-beta\OutlookGoogleCalendarSync.exe
-- | --
Config In | C:\Users\tamaraj\AppData\Roaming\Outlook Google Calendar Sync\settings.xml
Subscription | N/A
Timezone DB | 2017b
--
**Installed or Portable**: Installed

**Problem Description**  
\Last month I installed the app; I had this issue (multiple event entries created every sync) regardless of how I set the preferences. I believe I set the two-way option, but can't recall.

I uninstalled it. I thought to try again and reinstalled yesterday. This time I definitely set it to the 2-way option. However, every sync gives me 'delete' messages BUT multiple entries are still being created on both calendars. 

Only one instance of the program is showing in my install/uninstall program. I am going to uninstall it again, so any advice on what to do next should start with that understanding (for instance - if there are remnants needing to be removed that cause this problem, then I will need to know how to target & remove them).

**Steps to Reproduce the Issue**  
1. \Just let it sync as usual, so the log includes this. (attached log)
1. 

**Any other information**  
\attached images, settings, outlook & google calendars

![settings](https://user-images.githubusercontent.com/36493460/36236292-f3c51644-1227-11e8-835c-9824e72e37e6.JPG)

![outlookcal](https://user-images.githubusercontent.com/36493460/36236261-d31a7182-1227-11e8-8aab-ca7ff7f86758.JPG)
![googlecal](https://user-images.githubusercontent.com/36493460/36236263-d7058c14-1227-11e8-8058-853def77f3d2.JPG)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1726123/OGcalsync.log)

[OGcalsync.log.2018-02-14.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1726119/OGcalsync.log.2018-02-14.txt)

**Comment by phw198** [comment]
The logfile only shows you using the beta v2.7.0, not the alpha v2.7.1 - not that it will solve this particular problem. It also shows you upgrading from v2.5.2, and there have been lots of changes since then.

I think the problem was introduced in that earlier version of v2.5.2 and so you will need to manually resolve it before v2.7 will start working properly. Assuming Outlook is your master calendar:
1. Set OGCS to one-way sync from Outlook to Google
1. Manually delete all the duplicates from Outlook
1. Press and hold `Shift` while clicking `Sync` to perform a full sync *
   1. You may need to do this several times until you get a clear sync with no changes.
1. Set OGCS to 2-way sync to see if duplicates get produced again.

\* Note you could also try creating a new empty Google calendar and start syncing with OGCS to that instead of cleaning up the current one? This might be simpler and more sure of solving the problem.

Let me know how you progress.
