### ISSUE TITLE
Deleting recurring entries older than the range specified.

### ISSUE THREAD

**Issue by HeavyG603** [phw198/OutlookGoogleCalendarSync#502]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.2.0 
**Installed or Portable**: Installed

**Problem Description**  
\Randomly being prompted to delete older recurring entries.  No idea why since I didn't initiate a delete on either platform.  I figured maybe it located an old straggler (these were from 2016 <) but no they pegged my current recurring meetings as I found out after telling it to do it.  Of course I've disabled deletes all together 

**Steps to Reproduce the Issue**  
1. \Start with a google calendar with older recurring issues
2. No idea what its using to selecting them. Logs attached
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1848835/OGcalsync.log)
   

**Any other information**  
\<Update here>

**Comment by HeavyG603** [comment]
Still trying to delete more entries it shouldn't even been trying to.

**Comment by HeavyG603** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1853912/OGcalsync.log)

**Comment by phw198** [comment]
So is your concern that the items it is deleting are old (but the items are no longer in Outlook), or that the recurring items have not been deleted in Outlook so it should not be deleting them in Google at all?

If the former, then this is expected. Just because they do not start within the sync range, does not mean that the recurrence does not _span_ the sync range - which if they have no end date, then they will and therefore be subject to sync.

If the latter, then clearly this is an issue. OGCS is showing it has found `Outlook 64, Google 78` items, so there is clearly a disparity. It's possible that your [Outlook date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) is not capturing everything it should? Try experimenting with different formats and seeing if the number of items returned changes at all.

**Comment by HeavyG603** [comment]
For instance, I'm making no changes in Outlook, but I keep getting this message.
![image](https://user-images.githubusercontent.com/37811026/38749240-e9b0a4b0-3f1e-11e8-9a02-1e98b8069851.png)

**Comment by HeavyG603** [comment]
Its still at it even after upgrading to 2.7.3:

![image](https://user-images.githubusercontent.com/37811026/39475978-5b504438-4d28-11e8-8b06-e77edfc7c827.png)

**Comment by HeavyG603** [comment]
Its also resetting my free / busy indicator to free on my appointments but not sure if that relevant

**Comment by phw198** [comment]
> Its also resetting my free / busy indicator to free on my appointments but not sure if that relevant

Your settings show that you have opted to force all items synced to Google as available/free, so that would be the expected behaviour.

Your settings also show the you have two-way sync and Merge items turned on. This means that any recurring items eg in Google that started in 2016 and repeat up to today, would be synced into Outlook. If for some reason you then deleted that appointment, OGCS would want to sync the deletion back to Google - but because you have that disabled it's not doing the deletes. However, it will warn you with every sync, because you are preventing it from keeping both calendars in sync.

Have you confirmed which appointments it wants to delete? If you turn off the `Disable Delete` but turn on `Confirm on Delete` then you will see and be able to confirm if you want that to happen.

If you don't think the deletes are correct, then you could turn on one-way sync temporarily. So for example, if it wants to delete items in Outlook, sync from Outlook -> Google to recreate the items in Google. Repeat in the other direction too if necessary, and then re-instate two-way sync.

**Comment by HeavyG603** [comment]
The problem with deleting seems to be one one instance of a recurring entry is deleted, it seems to want to take out the whole set.

**Comment by phw198** [comment]
> If you don't think the deletes are correct, then you could turn on one-way sync temporarily. So for example, if it wants to delete items in Outlook, sync from Outlook -> Google to recreate the items in Google. Repeat in the other direction too if necessary, and then re-instate two-way sync.

Have you tried this yet, then? If you still get problems after that, then it would really help me if you can identify the exact steps to replicate the problem on a simple test recurring series.

**Comment by HeavyG603** [comment]
Yes I tried both your suggestions, much appreciated.  So turning the Free / Busy sync off fixed it flipping my indicator on me.  Still not sure why that worked though, shouldn't it by synchronizing it not just flipping it one way or the other ?  My setting on Google was always set to Busy prior to this.

I also reset the sync to one way Google to Outlook, and turned deletions (with confirmations back on).  This seem to keep both my appointments in Google from getting deleted but also picked up some appointments that stubbornly would not sync to outlook.

I will attempt to create a new recurring entry in Google and see what that brings, will record the steps and send the log.  I am very hesitant to turn two way sync back on at the moment though.

**Comment by phw198** [comment]
> So turning the Free / Busy sync off fixed it flipping my indicator on me. Still not sure why that worked though, shouldn't it by synchronizing it not just flipping it one way or the other ? My setting on Google was always set to Busy prior to this.

The setting isn't a sync, it's an override. If you want it to _sync_ free/busy status, then don't check the "For all items in x calendar, set to free".

Have you returned to two way sync yet?
