### ISSUE TITLE
uid not unique with recurring events

### ISSUE THREAD

**Issue by daniu-de** [phw198/OutlookGoogleCalendarSync#516]
**OGCS Version**: v2.7.3.0  
**Installed or Portable**: Installed

**Problem Description**  
recurring events do not get unique ids. Is there a reason why it is like that? I got another software that relies on unique ids and that would require to be rewritten - so I would appreciate unique ids for all events even recurring ones.
Honestly I would love a "dump-mode" - just erase everything in the existing google/caldav calendar and overwrite it with everything in the outlook calendar. I do not need anything but that and it seems to me that this is much easier than everything this software does. I believe that lots of people require exactly that. The only point I would add would be that the same event must get the same id next time it gets "dumped".

**Comment by phw198** [comment]
So "dump mode" would equate to:
1. Delete everything in Google
1. Export everything in Outlook
1. Import everything to Google

That would be one sure-fire way of wasting the limited API quota and pissing Google off :open_mouth: 

So recurring _series_ should have a unique ID, but the recurring instances within them won't - is that what you're referring to? This is because I sync them as a series and not individual standalone occurrences. I think another user has forked my project to add this as a feature - I could consider pulling that in to my project if it fits what you need?

**Comment by daniu-de** [comment]
Hi Brozono,

thanks for the offer. However I am not sure how to get a running program from your source

**Comment by brozono** [comment]
My repo would require you to build it yourself. I don't set it up to have installs or even zips of compiled stuff.

**Comment by daniu-de** [comment]
hmmm - would it be possible to point me to some document which helps me to compile the sourcecode myself?

**Comment by brozono** [comment]
Not to be mean, but neither myself nor @phw198  are likely going to provide a bunch of support. Google is your best ally here.

Here is what I think you might need to do, but I didn't document myself getting this up and running so...

1. Install Visual Studio
2. Install .NET4.5
3. Pull my repo
4. Open solution
5. Project -> OutlooGoogleCalendarSync Properties -> Signing
5.a. Create Test Certificate and use that
6. Build -> Build OutlookGoogleCalendarSync
Assuming that just works...
7. Build -> Publish -> Finish
8. Go to output folder and copy where you want to run from
9. Likely delete your entire Google Calendar from Google I/F
10. Launch App
11. Configure per instruction of mainline
12. Settings -> Sync Options -> Direction : Outlook to Google
13. Settings -> Developer Options -> Make sure Enable Use Recurrence is NOT checked
