### ISSUE TITLE
Sync attempts to delete Google entries

### ISSUE THREAD

**Issue by kentba** [phw198/OutlookGoogleCalendarSync#518]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.3  
**Installed or Portable**: Installed

**Problem Description**  
Sync attempts to delete 67 Google items.  I have delete disabled thankfully.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1942840/OGcalsync.2.log)

**Comment by phw198** [comment]
HI @kentba 

So what's the background to this? Had you been using OGCS before installing v2.7.3? It looks like you have because the logfile is showing only 11 of the 53 Google events are ones that have _not_ been synced previously by OGCS.

Also, in the first sync, it is not detecting any Outlook appointments - is this correct? If not, [see the wiki article about date formats](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items).

Also, why is the number of Google items growing so quickly? Do you have some other mechanism adding events to Google, because the logfile isn't showing OGCS adding anything to Google. Unless you have more than one instance of OGCS syncing to the same Google calendar, which isn't supported...

**Comment by phw198** [comment]
Good news indeed - thanks for letting me know 😊
