### ISSUE TITLE
Items failing to sync

### ISSUE THREAD

**Issue by HeavyG603** [phw198/OutlookGoogleCalendarSync#522]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v7.2.3 
**Installed or Portable**: Installed

**Problem Description**  
Now in addition to problems with older recurring issues, it seems it have issues with any recurring entry from Google.  I've attached the log file, there is an "Event failed" message in it.

**Steps to Reproduce the Issue**  
1. Create a new recurring item in Google
2.  Sync

**Any other information**  
\<Update here>
![image](https://user-images.githubusercontent.com/37811026/39766948-89784b04-52b3-11e8-9cf8-514098260c74.png)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1984601/OGcalsync.log)

**Comment by HeavyG603** [comment]
Update, now most of the syncs are failing and its still going wayyyyy beyond the date range I specify.  New log attached.  I'm going to turn it off at this point until some resolution is offered
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1989514/OGcalsync.log)
, its just wreaking havoc on my Calendar.

**Comment by phw198** [comment]
"Failed to retrieve Google event" is covered under #510 and you have already reported the deletions warning on #502.

As explained before, if a recurring series **spans** the date range being synced, it will sync. Its start date is irrelevant.

All your Google items being set to Free/Available is because that's what you've set it to do:
![image](https://user-images.githubusercontent.com/11843015/39972256-5e7d08c8-5703-11e8-885a-9e4a09dd482c.png)
