### ISSUE TITLE
Exclude filters not working

### ISSUE THREAD

**Issue by urbunuk** [phw198/OutlookGoogleCalendarSync#541]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog

-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed  

**Problem Description**  
I'm getting a number of errors in Outlook 2016 when Send/Receive. I also cannot set Filters on events in the Outlook Calendar (This Computer Only) Is it possible to exclude PRIVATE events from Sync to Google?

**Steps to Reproduce the Issue**  
1. I press send/receive in Outlook 2016 and I get a bunch of errors starting with the words Task "Internet Calendar Subscription" reported error 0x0004002(A,B,C,D)

**Any other information**  
If I sync via the Program it seems to work oK.

https://gist.github.com/urbunuk/0d6642872ee960d99fc5798dd23439ec

**Comment by phw198** [comment]
Hi, ~the gist link seems to be broken, so I can't check that.~ However, OGCS doesn't have anything to do with send and receive in Outlook. If you've configure an internet calendar in Outlook, that won't update via send and receive that's not OGCS but native Outlook functionality and not something I can help with...

For excluding private appointments from sync, that's not currently possible, but I could add to the list of enhancement requests. Is it really necessary though? If it's private in Outlook, OGCS will sync it as private in Google.

Filtering Outlook appointments would be done by including/excluding categories - looks like you finished excluding category "Personal" so that should not be found in Google? Note, if you _already_ synced some of those items, then do a full sync by holding `Shift`+`Sync`.

Would also recommend you upgrade OGCS to the latest alpha - due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).
