### ISSUE TITLE
Alt Mailbox Does Not Stay Set Due to Non-Outlook Access

### ISSUE THREAD

**Issue by AOWilson** [phw198/OutlookGoogleCalendarSync#549]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----
**OS / Office:**
Desktop PC using Windows 10, 64-bit with Office 2010 Outlook

**Outlook Mailbox:**  _(Address hidden)_
![msomail](https://user-images.githubusercontent.com/40968592/42426445-e4fea406-82dc-11e8-93da-47cdab0f6292.jpg)

**Calendar:**  
Local file on PC, NOT on Outlook Website

**OGCS Version**: v2.6.5
**Installed or Portable**: Installed

**SYNC:**
Only Outlook to Google

**Problem Description**  
SETTINGS TAB > Outlook
**-- Default Mailbox:**
     Does Not read the calendar in the local personal folder

-- **Using Setting:  Alternative Mailbox > Personal Folders**
     This option accesses the local PC resident calendar file
![calendarfolder](https://user-images.githubusercontent.com/40968592/42426509-5e2294b4-82dd-11e8-8c68-1bd64de217e9.jpg)

-- When OGCS starts, new Outlook warning window is displayed:
    A Program is trying to access eMail address information stored in Outlook _(see jpg)_
![programallowaccess](https://user-images.githubusercontent.com/40968592/42426282-a2b4a308-82db-11e8-8235-960b69a6d302.jpg)

_**A manual mouse-click response is necessary to grant OGCS access for specified amount of time
Is there a way to make this a permanent allow access setting?**_

**Steps to Reproduce the Issue**  
1. Every time OGCS attempts to run, manual access via the pop-up Outlook window must be granted
2. If I'm not at the PC to grant access, OGCS is unable to sync
3.  After failure, OGCS returns message:
  Calendar Not Found reverting to Default Calendar _(see JPG)_
![calendarnotfound](https://user-images.githubusercontent.com/40968592/42426304-c7f157b0-82db-11e8-94ce-5fd01cc0cef2.jpg)
  This action wipes out my Google calendar which I access via mobile/laptop travel computing

**Any other information**  
Logfile attached for review:
[OGcalsynclog.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2174321/OGcalsynclog.txt)

Thanks for the help!!
AOWilson

**Comment by phw198** [comment]
Hi - have you had a look through https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security ?

**Comment by kwagner115** [comment]
I too have had the same problem for the past month. Running v2.7.4.2.

I never sync attendees. 

I only use MS Defender. Definitions updated daily. 

Windows 10, OS Name	Microsoft Windows 10 Home, Version	10.0.17134 Build 17134

**Comment by phw198** [comment]
@AOWilson First thing first, you're on a pretty old version of OGCS, so please upgrade to the latest alpha. Note, if you are on an version v2.7.3 or earlier, due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

I also suspect that you are clicking `Deny` on the Outlook security popup? It's happened 3 times in the log file you provided, each with varying times between the popup and the `Access Denied` message - one about 30 minutes later. But this would be expected, you need to click `Allow`.

@kwagner115 As you're already on the latest release, are you able to provide your logfile of when it happens? I assume your `Programmatic Access` setting is `Warn me when my antivirus is inactive/out of date`?

**Comment by phw198** [comment]
Cool - [wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) updated with startup delay advice.

**Comment by kwagner115** [comment]
Nice work. Great support!! Nice tool..

Kevin

319-382-4461

________________________________
