### ISSUE TITLE
No Internet - giving debugging error - not able to close

### ISSUE THREAD

**Issue by jmathis0517** [phw198/OutlookGoogleCalendarSync#555]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5.0  
**Installed or Portable**: Portable
**Problem Description**  

**Steps to Reproduce the Issue**  
1. With no internet connection - get "OGCS Error Encountered"
```
2018-07-23 07:41:34,289 DEBUG  11 OutlookGoogleCalendarSync.Updater [0] -  Checking for ZIP update...
2018-07-23 07:41:34,289 ERROR  11 OutlookGoogleCalendarSync.Updater [0] -  Failed to retrieve data: The remote name could not be resolved: 'github.com'
2018-07-23 07:41:34,320 DEBUG  11 OutlookGoogleCalendarSync.Forms.ErrorReporting [0] -  Asking user if they want to automatically report errors.
```
**Any other information**  
Tried v2.7.4.0 and no errors. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2220090/OGcalsync.log)

**Comment by phw198** [comment]
This is pretty much expected behaviour. 

Every time you started v2.7.4 you had an internet connection, so it was able to check for an update and just silently logged the error. New in v2.7.5 is the ability to report back errors when they occur, so now you are aware of the issue. Just click `No`, `OK`, or close the window and carry on?

I will however, drop the log level from `ERROR` to `WARN` if there's no network available, as this is no surprise and nothing can be done until network is restored.
