### ISSUE TITLE
colours of categories

### ISSUE THREAD

**Issue by HDanacor** [phw198/OutlookGoogleCalendarSync#561]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\no colours of categories in google

THX!

**Steps to Reproduce the Issue**  
1. \created calender in outlook with different categories/colours
2. \included categories in the settings
3.\synchronisation started and successful
4.\ all entries correct, but all in the same colour in google

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
No idea which version you're referring to... I'm assuming not the latest alpha?

**Comment by HDanacor** [comment]
Hi!
Sorry, V 2.7.0.0

**Comment by phw198** [comment]
Yep, so what you're looking for is in the later alphas.

:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

If you are on an version v2.7.3 or earlier, due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

**Comment by HDanacor** [comment]
Great! It worked! Thanks a lot!
