### ISSUE TITLE
syncing repeats evry 5 m,inutes although setting is for every 24 hours.

### ISSUE THREAD

**Issue by kennym8** [phw198/OutlookGoogleCalendarSync#593]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
setting is to sync every 24 hours. Now it tries every 5 or so minutes and I get an error asking to allow or deny every five minutes. If I deny, it repeats and will not go away until I allow. See error attached..... impossible tyo attach file, have tried .pdf, .png, .doc

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by kennym8** [comment]
Thank you for your reply.

Unfortunately, I cannot find any instructions anywhere for attaching a file.

The version I have is 2.7.6, I do not see where I might find an update. Your instructions do not reflect what is visible. Your link to upgrade leads nowhere.

I am getting fed up with this and am almost ready to uninstall it!

Ken

**Comment by phw198** [comment]
That's because you're reading and replying to an email notification, not the actual GutHub issue you raised. 

Link to instructions is here: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file

**Comment by kennym8** [comment]
Also: once I pick the right log file and rename it .txt, where do I post it? as a new "gist", whatever that means? I am not a programmer, just a user of your sync program, so do not understand most of what I read in github, so need detailed clear instructions!

Ken

**Comment by kennym8** [comment]
Yesterday the error appeared repeatedly on my wife's computer. I attach the txt file here. We only stopped it when all attempts were denied.

Ken

Logfile: https://gist.github.com/phw198/5a315ff80843e5c03be7f65e7bff1af0

**Comment by kennym8** [comment]
Could I have a response to my three emails please?

Ken

**Comment by kennym8** [comment]
Can I get a response, please?

Ken

**Comment by kennym8** [comment]
Why can't  I get some help with my probems with your program? Not a very good reference for you!

**Comment by phw198** [comment]
Because it's a project I run in my spare time of which I have had very little of late. You can go and buy a different product if this isn't meeting your needs.

If you deny OGCS access to Outlook then of course it won't work properly. Take a [look here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security#why-am-i-getting-outlook-security-pop-ups) for options on how to stop the security pop ups from happening. 

Pretty sure when you're starting OGCS, a notification bubble is showing alerting you your security settings aren't optimal - and if you clicked the bubble it would take you to the same information page anyway...

**Comment by kennym8** [comment]
Thank you!

Ken
