### ISSUE TITLE
Google calendar has exceeded quota

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#603]
V 2.7.6.0

Have received a message 3-4 times in the past month - google calendar has exceeded quota

https://support.google.com/a/answer/2905486?hl=en

**Comment by kwagner115** [comment]
Google's daily free calendar quota is exhausted!
     Either wait for new quota at 08:00GMT or     
  get yourself guaranteed quota for just £1/month.



Sync version: 2.7.6.0

Sync started at 09/25/18 12:17:51 AM

Syncing from 09/15/18 to 09/26/19

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

75 Outlook calendar entries found.

Scanning Google calendar...


The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Operation aborted after 1 failed attempts!
Another sync has been scheduled to automatically run in 120 minutes time.

**Comment by ronisaacson** [comment]
I've been digging into this a bit. By default, OGCS has an API key that's shared among all users. The quota is a million requests per day, but when we collectively exceed it, everyone will start getting this error. If you are a paid OGCS subscriber, you get separate credentials with guaranteed quota. Either it's a smaller pool of users, or the developer pays for increased limits on those credentials.

You can get around this yourself by creating your own credentials.

1. Go to https://console.developers.google.com/apis/credentials and create a Project.
1. Click on Library and enable the Google Calendar API and Google+ API. (Yes, you need Google+ enabled, not sure why.)
1. Click on Credentials. You want an OAuth Client ID, but first you'll need to fill in the details on the OAuth consent screen:
   1. Enter an application name. It can be whatever you want.
   1. Under Scopes, click Add Scope and click the select-all box. Add them all.
   1. Hit Save at the bottom of the screen. You don't need to enter anything else. Since this is for your private use, you don't need any kind of verification.
1. Now go back to the Credentials screen and create your OAuth Client ID. Copy down the ID and Secret.
1. In OGCS, make sure you run a sync first so everything is up to date.
1. In the Settings pane, on the Google tab, click Disconnect Account.
1. Check the Show Advanced box and enter your Client ID and Secret.
1. Click on Retrieve Calendars. The consent screen will pop up in your browser. Click Allow, then return to OGCS and pick your calendar from the drop-down.

That should be it! Now you won't have to worry about losing your ability to sync.

**Comment by kwagner115** [comment]
Ron,
 
Thanks for the information. A couple of questions: 
 
1.	You do not have a “production” product yet, do you?
2.	As your user base grows, the quota problem will happen every day for every user. Is that your intention? 
3.	How do you get a “paid OGSC Subscription”?
4.	Is your product road map to have a limited feature version of the product that is “free”? 
 
Kevin

**Comment by ronisaacson** [comment]
Those are all good questions, but not for me. I don't have anything to do with OGCS development. I'm just an end-user like you, and this is based on my own observations.

**Comment by phw198** [comment]
@kwagner115 As @ronisaacson says, he's not the developer but a helpful member of the user community - welcome @ronisaacson!

To your questions:
1. If you mean there isn't a non-beta release of OGCS, then no, but Google also have the habit of running stuff in beta for years too... 🙂 
1. The quota limits are imposed by Google so it's not my intention, no. So far they have been accommodating in increasing the shared quota limits upon request, but as the user base continues to grow beyond what I ever anticipated, the last time I requested Google showed signs of being much less willing to do so. However, I have expected this for some time now and as such built in a API quota "pooling" framework which is ready to kick in if necessary.
1. You click on the little yellow "post-it" note that appears when the quota is exhausted that says "get yourself guaranteed quota for just £1/month"
1. OGCS is already free and **not** feature limited - I've made a point of doing that.

**Comment by phw198** [comment]
Let's be clear, you do not have to pay for using OGCS. You can choose to **donate** if you appreciate the countless hours I have put in to developing it and want to encourage me to put more in. And if £10 or more is donated, as a thank you, the splash screen can be suppressed. This does not change the functionality of the sync, which is fully featured regardless of donations.

For quotas, your options are a) wait for OGCS to automatically sync again when new quota is available (8 UTC); b) buy dedicated quota (Google controls quotas, not me); c) set up your own API keys

Regarding not paying for products under development, does this mean you don't use Windows, Office, iOS, Android or any other product that has continual updates issued? If you find a product no longer being developed, you've found a dead product that no-one cares about any longer...and why would you pay for that?

**Comment by jurjenarnold** [comment]
> 
> 
> I've been digging into this a bit. By default, OGCS has an API key that's shared among all users. The quota is a million requests per day, but when we collectively exceed it, everyone will start getting this error. If you are a paid OGCS subscriber, you get separate credentials with guaranteed quota. Either it's a smaller pool of users, or the developer pays for increased limits on those credentials.
> 
> You can get around this yourself by creating your own credentials.
> 
>     1. Go to https://console.developers.google.com/apis/credentials and create a Project.
> 
>     2. Click on Library and enable the Google Calendar API and Google+ API. (Yes, you need Google+ enabled, not sure why.)
> 
>     3. Click on Credentials. You want an OAuth Client ID, but first you'll need to fill in the details on the OAuth consent screen:
>        
>        1. Enter an application name. It can be whatever you want.
>        2. Under Scopes, click Add Scope and click the select-all box. Add them all.
>        3. Hit Save at the bottom of the screen. You don't need to enter anything else. Since this is for your private use, you don't need any kind of verification.
> 
>     4. Now go back to the Credentials screen and create your OAuth Client ID. Copy down the ID and Secret.
> 
>     5. In OGCS, make sure you run a sync first so everything is up to date.
> 
>     6. In the Settings pane, on the Google tab, click Disconnect Account.
> 
>     7. Check the Show Advanced box and enter your Client ID and Secret.
> 
>     8. Click on Retrieve Calendars. The consent screen will pop up in your browser. Click Allow, then return to OGCS and pick your calendar from the drop-down.
> 
> 
> That should be it! Now you won't have to worry about losing your ability to sync.

Thanks for the easy guide, solved my problems.

**Comment by jobisoft** [comment]
@phw198 : I know this is closed but I run into the same issue as a developer of a sync app (TbSync for Thunderbird). Could you help me get around the limit for my users? How did you do the "pooling"? How did you implement the guaranteed quota? I am hit by surprise that I exceed the 1.000.000 request limit per day already. I did not find any information on what google will charge me, they only tell me I have to add a billing account to my project if I want to raise the limit. If you could share your experience, that would help me a lot. Thanks!

**Comment by MatthieuPERIN** [comment]
Hello,

Problem reached this very morning: might be  a good idea to rise a "how to update you quota" screen when this error is catch by the program ?

**Comment by jobisoft** [comment]
What? Quota is reached again? You cannot change the quota. It is a limit for the app, counting ALL users. Google doubled it a few month ago. Crazy...

**Comment by guyheyns** [comment]
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer ...

**Comment by guyheyns** [comment]
One important comment! You have to make sure you also create at least one user in the OAuth Client ID. Then it works!

**Comment by SingingOwl** [comment]
To add on to the guide from ronisaacson, guyheyns and my experience (points 3.1,3.2,3.3) :

> I've been digging into this a bit. By default, OGCS has an API key that's shared among all users. The quota is a million requests per day, but when we collectively exceed it, everyone will start getting this error. If you are a paid OGCS subscriber, you get separate credentials with guaranteed quota. Either it's a smaller pool of users, or the developer pays for increased limits on those credentials.
> 
> You can get around this yourself by creating your own credentials.
> 
> 1. Go to https://console.developers.google.com/apis/credentials and create a Project.
> 2. Click on Library and enable the Google Calendar API and Google+ API. (Yes, you need Google+ enabled, not sure why.)
> 3. Click on Credentials. You want an OAuth Client ID, but first you'll need to fill in the details on the OAuth consent screen:
>    
>    1. Enter an application name. It can be whatever you want.
>    2. Under Scopes, click Add Scope and click the select-all box. Add them all.
>    3. Hit Save at the bottom of the screen. You don't need to enter anything else. Since this is for your private use, you don't need any kind of verification.
>
>        3.1 Publishing status = Testing 
>        3.2 User type = External (unless you have an organization)
>        3.3 Test users = Add the Google Calendar account you wish to sync as a test user
>
> 4. Now go back to the Credentials screen and create your OAuth Client ID. Copy down the ID and Secret.
> 5. In OGCS, make sure you run a sync first so everything is up to date.
> 6. In the Settings pane, on the Google tab, click Disconnect Account.
> 7. Check the Show Advanced box and enter your Client ID and Secret.
> 8. Click on Retrieve Calendars. The consent screen will pop up in your browser. Click Allow, then return to OGCS and pick your calendar from the drop-down.
> 
> That should be it! Now you won't have to worry about losing your ability to sync.


I also had some error in the final step (you could call it step 8.1), when your default browser is opened and an authorization url is sent to a port on the local host 127.0.0.1. The error was "This site can’t be reached". But that was taken care of after I checked the sync tab and found that I didn't clear a proxy setting. Cleared the proxy setting (because I didn't need it), the error was still there, but I could pick my calendar from the drop-down.
#
