### ISSUE TITLE
google reclaiming entries

### ISSUE THREAD

**Issue by angd2005** [phw198/OutlookGoogleCalendarSync#619]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6.0
**Installed or desktop computer
**Problem Description**  
\not sure what i did but entries from outlook that are recurring after further syncing seem to change in the process saying that google is reclaiming the event.  i then end up with two versions of the same entry . one showing the same information with recurring time period as outlook. the other identical one shows as do not repeat and is individually listed every day.  I fixed the issue resetting my google calendar to zero entries, re synced and all entries form outlook to google match up.  My concern now is after a few more syncs the same problem will arise.  I havent syncedfrom the inital new one yet.
**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\sorry first time i have used github, apologies if i did something wrong.  modified a log file that shows hopefully what happens
[OGcalsync16.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2485609/OGcalsync16.log)

**Comment by phw198** [comment]
The event reclaim process is designed to prevent duplicates. In essence, items that have **not** been synced by OGCS but already exist in the destination calendar, along with a matching Subject, Location and start+end date will be "reclaimed". This means OGCS would then sync against that pre-existing event, rather than create its own instantiation of the event as defined in the source calendar.

OGCS does not create individual instances of each recurring event - so if you are seeing this, they were not created by OGCS, but some other user / thing (for example Amazon Alexa). These items would be deleted by OGCS if you did not have deletions disabled - that's the reason you're seeing duplicates. It's your call if you want to enable deletions; my advice is always to sync to a dedicated calendar in Google to avoid this type of this anyway 🙂
