### ISSUE TITLE
Notifications continue to be downloaded from Google even w/ them turned off in Google

### ISSUE THREAD

**Issue by dfiord** [phw198/OutlookGoogleCalendarSync#620]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Even though issue #377 has been closed this issue seems to still exist.

I have all notifications turned off in google yet when one way syncing from Google a notification is set for 15 minutes when the event reaches Outlook.  

Can you please look into this.
ver. 2.7.6.0
installed from .zip file
one way sync Google to Outlook
No OC*.log file available

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
This will be due to the default reminder as set in Outlook:
![image](https://user-images.githubusercontent.com/11843015/48974310-c9493900-f04c-11e8-99dd-41cc0b1dc55d.png)

However, I should probably add an option in OGCS to not use this default (the equivalent option is provided to not use the Google default)...

**Comment by phw198** [comment]
![image](https://user-images.githubusercontent.com/11843015/48980146-28df2d00-f0bd-11e8-8629-4663242ec5ed.png)
