### ISSUE TITLE
Format from Google to Outlook does not come through

### ISSUE THREAD

**Issue by dadlugie** [phw198/OutlookGoogleCalendarSync#635]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: 2.7.7.0
-- | --

**Installed or Portable**: Installed

**Problem Description**  
Format is different on copy from google to outlook.  Part of the out look calendar entry is below in other.  This is part of the entry in google
FUG Bi-Weekly Meeting -- Updated till end of 2019

Ticket information will be added to FUG JIRA.  Agenda will be sent before each meeting  

──────────────────────────────────────────
Please join my meeting from your computer, tablet or smartphone. 

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
FUG Bi-Weekly Meeting -- Updated till end of 2019<br><br>Ticket information will be added to FUG JIRA.&nbsp; Agenda will be sent before each meeting&nbsp;&nbsp;<br><br><br>──────────────────────────────────────────            <meta charset="utf-8">        <style>            @import url('https://weblibrary.cdn.getgo.com/fonts/togo-fonts/2.4.1/togofonts.css');            a{ text-decoration: none; }            span{ margin: 0px; }            .s1{ font-family: "Helvetica" }            .s2{ font-weight: bold; }            .s3{ font-size: 16pt; }            .s4{ font-size: 12pt; }        </style>                <div class="body">            <span class="s1 s2 s4">                                Please join my meeting from your computer, tablet or smartphone.            </span><br><font face="Helvetica"><span style="font-size: 16px;">

**Comment by phw198** [comment]
I don't believe this is within my control to fix - we're at the mercy of the Google APIs and how they surface the description field. And there's [plenty of people complaining](https://www.google.com/search?q=google+calendar+event+description+html&rlz=1C1CHBF_enGB805GB805&oq=google+calendar+event+description+html&aqs=chrome..69i57j0l2j69i64.5309j0j9&sourceid=chrome&ie=UTF-8) about how a the description field, which is meant to be plain text, can contain HTML tags. Seems since the upgrade of Google Calendar to the Material Theme, this has got worse, as the web UI now allows various formatting and HTML can be saved _to_ the Event.

🔗 See also this [Google Forums thread](https://productforums.google.com/forum/?nomobile=true#!topic/calendar/r3OC4cL53NQ).

I don't want to manually start stripping certain tags that are still shown when the Event description is retrieved again (eg the `<style>` ones I think you gave as an example) as this'll cause knock-on problems with two-way syncs...
