### ISSUE TITLE
Synced entries appear private in Google although only set for Outlook 

### ISSUE THREAD

**Issue by MHofmann75** [phw198/OutlookGoogleCalendarSync#663]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.7.0  
**Installed or Portable**: Installed

**Problem Description**  
When setting "For all items synced to Outlook calendar set entries as private" the calendar entries synced to Google calendar are set to private as well. I just want to have the google entries set to private in the Outlook calendar, but not the Outlook items set to private in Google calendar.

**Steps to Reproduce the Issue**  
1. Go to Setting/Sync Options/How/More
2. Set "For items created by sync in Outlook calendar"
3. Check "Set entries as private" and save
4. Sync calendars (two way sync)
5. Result: Items created in Outlook AND in Google are set as private.
 
**Any other information**  
Regardless whether you set "all items" or "items created" the result is the same. There should be two option fields under "show more", one for Google-->Outlook and one for Outlook-->Google

**Comment by phw198** [comment]
I cannot replicate this, not on v2.7.8 at least and there haven't been any changes in this area since v2.7.7.

Config: 2-way sync, for items created by sync in Outlook calendar, set entries as private

Test 1
1. Create public event in Google calendar.
2. Sync and it appears in Outlook as private
3. Edit the item in Outlook (altered description slightly) and save.
4. Sync and the privacy in Google does not change, only the description.

Test 2
1. Create a public event in Outlook calendar
2. Sync and it appears in Google as public
3. Edit the item in Outlook (changed description) and save
4. Sync and the privacy in Outlook remains public, description changes.

Or are you saying you want to be able to create a private item in Outlook yourself and have OGCS sync it to Google as public?
