### ISSUE TITLE
Repeated ask to delete

### ISSUE THREAD

**Issue by jlrose13** [phw198/OutlookGoogleCalendarSync#693]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
OGCS asks to delete the same appointments over and over.  Deletions are set to confirm.  Once user confirms that an appointment is not to be deleted, can OCGS remember that selection?  Occurs on every sync.

**Steps to Reproduce the Issue**  
1. none.  
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Take a look here: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-calendar-sync-with-full-sync

**Comment by jlrose13** [comment]
Tried that.  still occurs.  Anything else I should look at?

**Comment by auburnham** [comment]
I am also having this problem, and the suggested link did not resolve the problem.

**Comment by phw198** [comment]
Guys, it's impossible to assist you if you don't provide any background to what happened before the prompts to delete started happening, don't provide your logfiles or even the version of OGCS you're running!

**Comment by jlrose13** [comment]
Sorry Paul.  Im on 2.7.1.  last two lo files attached .

I don’t recall any unique behavior prior to.  I’ll keep watch and notes.

**Comment by auburnham** [comment]
I recently started using OGCS, but things seemed to be stable before I started having this recurring message to delete valid calendar entries.  I've scanned my log, and I think this captures when OGCS thinks 3 Outlook calendar entries should be deleted:
```
2019-04-09 10:00:29,336 DEBUG  15 OutlookGoogleCalendarSync.MainForm [0] -  Synchronising from Google to Outlook.
2019-04-09 10:00:29,337 DEBUG  15 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Scanning 401 Outlook appointments for orphans to reclaim...
2019-04-09 10:00:32,326 DEBUG  15 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  3 unclaimed.
2019-04-09 10:00:32,326 INFO  15 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  3 unclaimed orphan appointments found.
2019-04-09 10:00:32,326 INFO  15 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  These will be kept due to configuration settings.
2019-04-09 10:00:32,328 DEBUG  15 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Comparing Google events to Outlook items...
2019-04-09 10:00:36,275 INFO  15 OutlookGoogleCalendarSync.Console [0] -  3 Outlook calendar entries to be deleted.
2019-04-09 10:00:36,275 INFO  15 OutlookGoogleCalendarSync.Console [0] -  0 Outlook calendar entries to be created.
2019-04-09 10:00:36,275 INFO  15 OutlookGoogleCalendarSync.Console [0] -  395 calendar entries to be compared.
2019-04-09 10:00:36,893 INFO  15 OutlookGoogleCalendarSync.Console [0] -  Deleting 3 Outlook calendar entries
```
I did try forcing a full sync in Outlook -> Google mode, and then switched back to Outlook <-> Google mode, but this problem persists.  Is there any clue in "3 unclaimed orphan appointments"?  Also, if it is any help, these 3 appointments have the exact same name & content as another appointment that OGCS doesn't try to delete, just different dates/times.  Therefore, do you think OGCS thinks these are duplicates?

**Comment by phw198** [comment]
@jlrose13 That's an old release. Please upgrade to the latest release, [v2.7.8.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.8-alpha/Setup.exe) and confirm if you can still replicate the issue. If you can, please re-upload your logfile (note, you can't attach files to GitHub via email replies either).

@auburnham I don't _think_ the 3 unclaimed orphans is relevant, just that they weren't created in the destination calendar by OGCS. `These will be kept due to configuration settings.` also indicates that it won't be deleting them.

The fact that the 3 deletions are all the same name may be significant, more so if you created them by copy and paste in Outlook? But I don't even know the version of OGCS you're running, so again, can't really help further...

**Comment by auburnham** [comment]
I am using v2.7.0-beta.  Also, the Outlook appointments were created by copying & pasting.  I have since renamed the appointments with unique names, and OGCS still tries to delete them.  I have changed the direction to Outlook > Google and performed a full sync, but this did not resolve the problem.

**Comment by phw198** [comment]
@auburnham OK, so you're running a release even older than @jlrose13....and  neither of you followed the guidance to upgrade to the latest alpha release before reporting an issue.

Copy and paste problems were fixed around v2.7.3 or v2.7.4

**Comment by BiornR** [comment]
Hi! I'm running version 2.8.0.0 and am also having the same issue.
My sync configuration is Google <-> Outlook set for push-synchronization.

Some items get frequent requests to be deleted, some only once. New deletion requests occur even when no changes to either calendar have been done.

Attached you find both a screenshot from the sync-screen + the corresponding log-lines.
In this case no changes had been done to either calendar since at least 2 synchronizations. The 3 items for deletion had not been altered since before the installation of OGCS.

Hope for a solution for this! (I had exactly the same issue with a previous version and had hoped it would go away…) Thanks!

<img width="244" alt="2019-08-08 18_01_46-Outlook Google Calendar Sync" src="https://user-images.githubusercontent.com/32297375/62719265-eae62700-ba07-11e9-88be-2505498873d9.png">
[OGcalsync_20190808.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3482677/OGcalsync_20190808.txt)

**Comment by jlrose13** [comment]
I’m getting this error again as well.  If an even is selected for Do No Delete, that ought to hold for subsequent syncs.
