### ISSUE TITLE
Issues with Syncing

### ISSUE THREAD

**Issue by emg72** [phw198/OutlookGoogleCalendarSync#764]
I have installed OGCS 2.8.0.0 on Win 10. It seems great and installs quick and easy.
I think its set up proper. However it does not sync anything. 
I set up a bunch of dummy calendar entries in outlook (pc) and in Google calendar (phone) and ran the sync. 
OGCS says it runs proper and finds calendar items. And then it does not create any in eithe google or outlook.

I would appreciate any help to get this up and running.

Thank you.

Erick
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3303120/OGcalsync.log)
![sync](https://user-images.githubusercontent.com/51970642/59714213-19e9d480-91df-11e9-8841-5b3ad8b1021d.jpg)

**Comment by phw198** [comment]
All looks in order to me - seems the test entries you created in both Outlook and Google, so OGCS matched them up and determined nothing needed changing.

**Comment by emg72** [comment]
Hi Paul,

Yes it seems to be syncing now – perhaps I did not give it enough time? The items in Outlook showed up in my phone later (after I posted the message). I think after they did an auto sync.

Thanks for investigating
Best regards, 

Erick M. Gow, A.Sc.T.

**Comment by JustBecasue** [comment]
Hi Paul,

I just installed it, did the settings, ran the sync and it did not find anything in my google calendar; there are plenty of entries in the google calendar.

![image](https://user-images.githubusercontent.com/38185173/60360219-3ccb7400-99a9-11e9-88f7-92e427de061e.png)

I am working off a fresh install of Outlook so there are no entries in Outlook at all.

Suggestions?

Wade

**Comment by phw198** [comment]
@JustBecasue That's pretty odd, I've never heard of it not detecting Google items (only sometimez Outlook due to date formats). Are you absolutely sure you've selected the right Google calendar in OGCS for syncing with?

:spiral_notepad: If you can provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) it might shed some light...

**Comment by JustBecasue** [comment]
Hi Paul,



Don't worry about it. Thanks for the response but I already deleted it and added another that is working fine.



Best,



Wade









---- On Thu, 11 Jul 2019 18:46:53 -0400 Paul Woolcock <notifications@github.com> wrote ----


https://github.com/JustBecasue That's pretty odd, I've never heard of it not detecting Google items (only sometimez Outlook due to date formats). Are you absolutely sure you've selected the right Google calendar in OGCS for syncing with?

🗒 If you can provide your OGcalsync.log file (https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file) it might shed some light...
