### ISSUE TITLE
I am a recipient of an invitation in Outlook, but Google makes me the owner of the appt.... and emails guests... HELP!

### ISSUE THREAD

**Issue by michaeltm2** [phw198/OutlookGoogleCalendarSync#809]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version 2.8.1.0
**Installed or Portable**: Installed

**Problem Description**  
I have a two-way sync with google and Outlook. I am invited to a meeting in Outlook and Google then somehow makes me the owner and sends updates to the other attendees in outlook  - of course they don't get it because OGCS changes the email address to add .ogcs but then i get these bounce backs.  Recently it was a very long list of attendees on the outlook invite so i got about 30 bounceback emails. Any way to fix this? Thanks!
[Gmail - Delivery Status Notification (Failure).pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/3521185/Gmail.-.Delivery.Status.Notification.Failure.pdf)

[Gmail - Delivery Status Notification (Failure).pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/3521203/Gmail.-.Delivery.Status.Notification.Failure.pdf)

[Gmail - Delivery Status Notification (Failure).pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/3521208/Gmail.-.Delivery.Status.Notification.Failure.pdf)

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Simple answer is "no", there's no way to fix this. Not that's been identified yet anyway (beyond not syncing attendees), and as this seems to be a Google bug that's been around for years and only affects certain people I'm not holding my breath. That's why I clock the email addresses with a `.ogcs` postfix so at least all those attendees aren't spammed and confused!

See [wiki for details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google).

As per #801, you could [check if you have notifications set](https://github.com/phw198/OutlookGoogleCalendarSync/issues/801#issuecomment-521825112) on the Google calendar you are syncing to and/or have shared the calendar.
