### ISSUE TITLE
Outlook starts automatically on Windows start

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#814]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1.0
**Installed or Portable**: Installed

**Problem Description**  
Since I have installed version 2.8.1.0 whenever I book my laptop, Outlook now automatically starts up. Outlook is not in the list of start up items, however it always starts. I do not seem to be able to stop it from happening. Can you assist and explain how I stop this from happening.

Thanks

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Since you've not provided you logfile, I'll have to guess at your configuration settings... Sounds like you'd have OGCS to start on system startup and have it scheduled to sync every x hours - so as soon as you start your computer it wants to sync and therefore has to open Outlook.

Outlook would close again after the sync unless you also have Push Sync turned on.

**Comment by Veggie352** [comment]
Hi Paul

Apologies for not sending the logfile, I am a techie person so had not realised I needed to do this. I can send if you require, however your assumption is totally right and OGCS is set to start on system start up and the scheduled sync is every 2 hours. So your assumption is spot on. I guess there is no way around this from happening?

Is there a way that OGCS can fire up once you open Outlook – then it can make an initial sync and then sync as per the configuration settings?

Thanks
Brian

**Comment by phw198** [comment]
If you don't have Push Sync turned on though, Outlook should close after OGCS has synced. Also, I don't think you would particularly notice Outlook has started because it would only show by an icon in the system tray next to the clock - ie not the main Outlook window opening. It's possible the Outlook reminders popup might show I suppose...

To you point about starting OGCS after Outlook - yes, that is possible but [requires a little bit of VB script](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#delayed-startup-of-ogcs) within Outlook.

**Comment by Veggie352** [comment]
Hi Paul

Outlook fully opens ie full and maximised main window and not just as an icon in the system tray. This happens every time I boot the computer. I will see if I can make the VB script work but otherwise would be great if you can see what could be the cause of the outlook window opening.

Thanks
Brian

**Comment by phw198** [comment]
I'd need to see your logfile after start-up to see how OGCS is starting Outlook - see if that sheds any light...

**Comment by Veggie352** [comment]
Can you explain the steps I need to follow to provide the log file you want?

**Comment by phw198** [comment]
They are already linked to in your opening post.

**Comment by Veggie352** [comment]
I am sorry Paul, I do not understand your message below. Can you explain please?

**Comment by Veggie352** [comment]
Hi Paul

Sorry for troubling but do I need to provide some log file to you. I can confirm that each time my computer starts, then Outlook fully launches and my inbox is displayed. It does not display only as an icon in the system tray. Also outlook reminders popup as well.

Any idea how I can address this please?

Many thanks
Brian

**Comment by phw198** [comment]
Hi,

Yes, you need to provide your `OGcalsync.log` file as per the instructions at the top of your post when you created this issue. You'll get a lot further if you don't try and manage your interaction with GitHub entirely by email - your emails have a "view it on GitHub" link, click that. Provide the log file after you have booted and seen Outlook start by itself.

You also asked "Is there a way that OGCS can fire up once you open Outlook" and I answered that with a link in an [earlier comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/814#issuecomment-528555085) too.
