### ISSUE TITLE
Multiple duplicates being created for the same events

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#856]
**Are you already using OGCS?**
Provide the version number: 2.8.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

Multiple events are being created for appointment invitations from someone else.  Often times 6 times.

Please let me know how I can prevent the duplications.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3679283/OGcalsync.log)

**Comment by phw198** [comment]
You have two way sync configured - which calendar are the appointments in original? Outlook? And the duplicates appear in Google? Are these then also duplicated back into Outlook?

Are these appointments affect _all_ for recurring series, where either you may have declined an occurrence, or the organiser has altered the series since it was originally sent? If so, this may be the same as #823

**Comment by j-lillard** [comment]
I am having a similar issue if I create a new event in Outlook. When it pushes the change, it'll create 50+ of the same event.

**Comment by phw198** [comment]
@j-lillard Where is your Outlook calendar account sourced? I'm guessing _not_ Exchange?

**Comment by hibaa9** [comment]
This happened to me. I was doing bidirectional sync of room calendars that I had full access to in Outlook, however, I didn't have access to 'Private Events'. OGCS would sync private events from Google to Outlook but on the next sync OGCS wasn't able to see that the private event already exists due to the access restriction of the outlook account and would keep recreating the private event on outlook.  Delegating myself access to the calendar with read access to private events fixed my issue.
![image](https://user-images.githubusercontent.com/44959061/98305172-629a5d00-1f8f-11eb-9328-31e95f97228b.png)
