### ISSUE TITLE
sync faild when both modify

### ISSUE THREAD

**Issue by valgit** [phw198/OutlookGoogleCalendarSync#872]
**OGCS Version**: v2.8.0 beta
**Installed or Portable**: Installed

**Bug Description**  
sync failed when the appointement from Outlok s been modify in Google Calendar after

**Steps to Reproduce the Issue**  
1. create an appointement in Outlook
2. sync
3. got to Google Calendar, modify 'notification' setting
4. resync
5. +> failure to sync

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
