### ISSUE TITLE
Asking about deleting an item that is in both Outlook & Google Calendars

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#877]
**OGCS Version**: v2.8.2.0
**Installed or Portable**: Installed

**Bug Description**  
When program is syncing calendars - I get prompted (yes I have confirm deletions on) about deleting a certain item.  Said item is present in both Outlook & Google so I do not understand why it is asking?!?!

**Steps to Reproduce the Issue**  
1. Run program - 2 issues come up to confirm,  Both are in both calendars
[OGcalsync 1029.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3785814/OGcalsync.1029.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by TRIALtri** [comment]
Similar issue here. I had this a while back and it seemed to resolve itself but today ogsync suddenly asked me about deleting 166 Outlook entries (ranging back to January this year), all that I have are checked are in both GCal and Outlook. ogsync has been running twice a day for weeks without asking about deletions (I have delete-prompt ON).  Log file attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5546587/OGcalsync.log)

ogsync version 2.8.4.0., paid for, running on Windows 10.

**Comment by phw198** [comment]
@TRIALtri I'm not sure what's caused this, but the situation as per now is that Google is only reporting 51 items whilst Outlook has 217 - and those 166 extra up for deletion are all in the past _before_ the sync window and should be out of scope. 

Are these items all recurring items? I can't tell as there's a slight bug in the logging. If they are **not** recurring then I would run [this test](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items).

**Comment by phw198** [comment]
@michgal2k Not sure if you still have this issue, but if you do [try this](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync). Also upgrade to latest alpha.

**Comment by TRIALtri** [comment]
Thank you for the helpful response.

Since I posted my log file the number of historic items being suggested for deletion was dropping every day until last week it suggested none (I always answered “no” to the deletion question so there was no change in the calendar). Then yesterday it started suggesting *future* events for deletion.

I just tried your suggestion to change the date format and found that every format except the ‘generic’ format returned a correct (matching) number of entries and I saved the setting and reran Sync which made *no* suggestions for deletion. I’ll monitor this for a few days but it looks hopeful.

BTW before these deletions started to come up the tool used to create many multiple entries of entries in my Google calendar, a new instance on every Sync. That stopped a while back happily.

FYI I access my Google calendar from my iPhone (ios 14.2) and I use UK date formats. Using Outlook 2016 on Windows 10.

Regards
Alan
