### ISSUE TITLE
Impossible to uninstall

### ISSUE THREAD

**Issue by dbrn1874** [phw198/OutlookGoogleCalendarSync#878]
-->

**OGCS Version**: v2.7.4.0
**Installed or Portable**: Installed

**Bug Description**  
Probably just me, but here goes: Every update after 2.7.4 failed. Install would work, then after full restart the app always returned to 2.7.4. Finally tried to fully uninstall and start fresh using Windows Control Panel Uninstall. Program uninstalled, then reappeared fully functioning after full restart. Tried following the uninstall guidelines in the wiki, including RegEdit and Command Line - no effect. Manually deleted folders in Users - no effect. Achieved partial deletion with GlarySoft or CC Cleaner - now program won't load, but Automatic Update always appears on startup and program is listed in Windows Uninstall list. Now I can't install a fresh version and can't remove the old version. Looks like I'm going to have to reset my PC (Windows 10 desktop).

**Comment by dbrn1874** [comment]
UPDATE: By un/reinstalling Office, I've gotten OGCS working again - log should be attached. Still stuck on v2.7.4 - updates don't stick past full shut down. Still cannot uninstall. Also, OGCS always loads at startup, even if that option is unchecked. Also, even though 'Check for updates' is unchecked, I always get the Update window on startup. So, I would still love to get this wiped off and start fresh so as to stop seeing that message!

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3786083/OGcalsync.log)

**Comment by phw198** [comment]
Do you use Business Contacts Manager by any chance?

**Comment by dbrn1874** [comment]
I looked around Outlook and didn't find that anywhere, so I don't think so.
But I'm in a university with a central IT department, so I don't know what
might be running in the background.

**Comment by phw198** [comment]
Your logfile shows v2.7.4 installed as expected to `C:\Users\braund5\AppData\Local\OutlookGoogleCalendarSync\app-2.7.4-alpha\OutlookGoogleCalendarSync.exe`.

It also shows it detecting later release v2.8.2 and you declining the upgrade. What happens if you accept the upgrade? Is it successful? Does the install path change to `C:\Users\braund5\AppData\Local\OutlookGoogleCalendarSync\app-2.8.2-alpha\OutlookGoogleCalendarSync.exe`? If it does, then perhaps your university is doing something really odd and controlling your %APPDATA% folder. Almost feels like a snapshot keeps reverting to the point where v2.7.4 is installed.

What happens to your `OGcalsync.log` file after every reboot? Does it still exist? Has it lost all the log lines recorded before you reboot?

If I were you, I'd try using the portable ZIP version running from a USB drive or something...
