### ISSUE TITLE
time zone reset moved all my calendar events ahead 6 hours -  how to fix?

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#884]
**Are you already using OGCS?**
Provide the version number.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

Using OGCS 2.8.1.0

On a trip to France,   I set my laptop time zone to local time.    I am using Outlook on my laptop,  syncing with my wifes Google Calendar in the cloud.      OGCS moved all of the events to 5 hours later in Outlook  (Google didn't change them)      I changed the time zone back to EST,   buth OGCS did not move them back.     There are over 200 events,  I do not want to fix them manually.     Any suggestion on how to fix
Thanks

**Comment by phw198** [comment]
Did you see OGCS update all the events? I'm highly sceptical it did, not least because none of them would have changed at source (your wife's calendar) and OGCS only syncs items that are newer than the destination (your Outlook).

Have a [read through this for your delight](https://support.microsoft.com/en-gb/help/2642044/how-time-zone-normalization-works-in-microsoft-outlook) - Outlook calculates the meeting times on creation/receipt of invites and converts to UTC. What timezone are the meetings in Google and what timezone do they show in Outlook? Is there a mismatch?

You could always try a full sync in OGCS (`Shift`+`Start Sync`) to see if that forces anything back....?

And if you haven't already, fully reboot your Outlook machine first.

**Comment by phw198** [comment]
[This page might also help](https://support.office.com/en-us/article/add-remove-or-change-time-zones-5ab3e10e-5a6c-46af-ab48-156fedf70c04) you work out the solution - I'm pretty sure it's a setting in Outlook you need to find/reverse.

**Comment by phw198** [comment]
Closing this as dormant, but would be nice if you could update it if you found the fix so others may be able to benefit.
