### ISSUE TITLE
Android App?

### ISSUE THREAD

**Issue by nrcarnevali** [phw198/OutlookGoogleCalendarSync#913]
**Is your feature request related to a problem? Please describe.**
Do you have any plans on developing an Android app for this app? A lot of times people will change meeting details overnight. As a workaround, I could keep my computer running/app running but I feel that is a less than ideal solution. I'm open any other solutions you may have,

Thanks for the amazing app!

**Describe the solution you'd like**
Android App

**Describe alternatives you've considered**
Leave work computer on (personal computer is a mac)

**Additional context**
I am rebuilding my home Win10 Server where I will be able to run this app 100% so please don't consider this a high priority - I just wanted to point out  a possible feature that could help a lot of folks

**Comment by daniu-de** [comment]
Hi,
Maybe I do not get what you want but ... in my opinion your Problem needs a solution in another place. This software syncs Outlook with Google. The calendar data that you refer to "people will change meeting details" is definitely not kept in Outlook but on some Server. So to sync this data you do not need a solution to sync something with Outlook but directly with the server.
Your solution "keep my computer running/app running" is the only way I could think that this app could get involved because if the data of your colleagues are not in Outlook how could a software called Outlook Google Sync sync it to anywhere?

For Android I recommend to have a look at Davx5 FKA Davdroid - https://www.davx5.com/ - which is btw free from F-Droid store. Maybe your server allows this software to sync your data to your Android phone. However this will only work if you got direct access to your server via caldav (I don't)

regards

**Comment by nrcarnevali** [comment]
wow - bingo you are 100% correct. I wasn't thinking down stream far enough during the process.. Now sadly I doubt my corp email serv will allow calldav either which is too bad. Thanks for the great response.

**Comment by nrcarnevali** [comment]
I'm assuming there is no similar free/ or paid solutionas for exchange mail servers?

**Comment by phw198** [comment]
@nrcarnevali See [my comment about EWS over here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/910#issuecomment-562940901). This would still require OGCS to be running somewhere though, and given you're building a VM that sounds like it'll have access to Exchange via Outlook, then that's the best solution.

But no, no plans for EWS (it would be almost a complete rewrite of OGCS to support it) and definitely no plans for an Android app - OGCS already consumes far too much time :wink:
