### ISSUE TITLE
Exceptions created by another user to repeating Outlook series events (also created by that same user) do not sync to Google

### ISSUE THREAD

**Issue by SamuelStevenson** [phw198/OutlookGoogleCalendarSync#914]
**OGCS Version**: v2.8.2.0  
**Edition**: Installed  
**Sync Direction**:  O<->G (but then O->G when attempting to fix the problem)

**Bug Description**  
Exceptions created by another user to repeating Outlook series events (also created by that same user) do not sync to Google.

**Steps to Reproduce the Issue**  

1. Have a different user create a weekly Outlook event and add you as an attendee.
2. Have that same user change the time of one event in the series in Outlook.
3. Event with changed time disappears from Google. New event with adjusted time is not created.

**Any other information**  

Error is noted in log stating that an exception exists in Outlook that does not exist in Google. Log notes suggest changing sync pattern to O->G, deleting series in Google, and then re-syncing. This does not solve the problem.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3917882/OGcalsync.log)

**Comment by phw198** [comment]
I believe this is actually fixed in #844, but I've broken part of that change out to this ticket to make sure.

:package: Please try [v2.8.2.18.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3936168/v2.8.2.18.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.

**Comment by phw198** [comment]
:spiral_notepad: Rolling this in to the next release anyway.
