### ISSUE TITLE
When notes are updated in an existing appointment the changes do not sync to other devices

### ISSUE THREAD

**Issue by Rtbrittjr** [phw198/OutlookGoogleCalendarSync#916]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
When notes are updated in an existing appointment the changes do not sync to other devices

**Steps to Reproduce the Issue**  
None

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
1. Actually provide the information requested in the OP - what is a "note", added where, to a single appointment or recurring etc etc.
