### ISSUE TITLE
OGCS crashes (Windows 20-04 v. 19035.1)

### ISSUE THREAD

**Issue by gatucker2** [phw198/OutlookGoogleCalendarSync#917]
----

**OGCS Version**: v2.8.0
**Installed or Portable**: Installed

**Problem Description**  
Application unexpectedly terminated!

Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80070003 The system cannot find the path specified. (Exception from HRESULT: 0x80070003)

**Steps to Reproduce the Issue**  
1. Start the app

**Any other information**

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
