### ISSUE TITLE
Request to be able to associate OGCS Subscription with different email address from the email address being synced

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#943]
**Is your feature request related to a problem? Please describe.**
I have a personal email address that is used with an exchange account. I have used OGCS more than once when I have a temporary need for a company I am working with, sometimes more than one at a time. Currently a paid subscription is only available by registering with the Google email address, which in my case, is temporary.

**Describe the solution you'd like**
Allow another email address (in my case, my permenant one) to be used to register OGCS>

**Describe alternatives you've considered**

**Additional context**

**Comment by phw198** [comment]
I don't know whether it's me today or what, but none of these tickets make much sense to me! :confused: 

* What your sync pattern is: G -> O, O -> G or O<->G?
* Which is the account that is "temporary"? Google? Outlook? Both?

OGCS is associated to a user by the Google account with which they are syncing. It's the only 100% reliable and **secure** way to tell users apart. If you have to keep switching between Google accounts as provided by different companies you have to work with, then I don't think there's much that can be done about that. 

I can't and don't want to provide a mechanism for someone to register any old email address that can't be programmatically validated (which automatically happens when you authorise OGCS to manage your Google calendars) and stop people from sharing round and abusing.
