### ISSUE TITLE
Outlook->Google Sync Failure

### ISSUE THREAD

**Issue by cooper-atx** [phw198/OutlookGoogleCalendarSync#954]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
Installed

**Problem Description**  
I'm syncing strictly from Outlook -> Google Calendar (one way).  A non-recurring invite originally scheduled (and synced) on a Thursday was moved to the next day (Friday) however OGCS never synced the meeting day change.  I tried re-accepting the Friday meeting still no luck.  My Google calendar never reflected the day change.  I've noticed the same behavior on multiple meetings both recurring and non-recurring.

**Comment by phw198** [comment]
Try forcing a full sync by pressing `Shift` and clicking `Sync`.

**Comment by 1lomeno3** [comment]
Does not help. As also stated in my issue [#952](https://github.com/phw198/OutlookGoogleCalendarSync/issues/952), even after full sync no update on G side, in case of O<>G sync, OGCS then tries to delete this event  in Outlook :(

**Comment by cooper-atx** [comment]
Thank you.  The full sync did correct one entry (sync’d correctly to Google Cal), but there were other recurring invites that did not sync.  The full sync is nice however still does not address the cause for the event to not sync correctly in the first place.  Thanks again.

**Comment by phw198** [comment]
Can't really troubleshoot with such limited information. As per guidance, in order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
1. Explain exactly which items are being problematic.
