### ISSUE TITLE
0x80004002 - E_NOINTERFACE

### ISSUE THREAD

**Issue by lebaguette900** [phw198/OutlookGoogleCalendarSync#961]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
When starting OGCS I get the 0x80004002 - E_NOINTERFACE error. An office repair does not help.

**Steps to Reproduce the Issue**  
1. Start OGCS :)

**Any other information**  
\<Update here>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4232349/OGcalsync.log)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

FYI, the real underlying error properly reported in later versions is `0x80040155`.

**Comment by lebaguette900** [comment]
Hi,

Thanks for your time. I tried updating to latest alpha. It then gave me the other error code you referred to, and I followed the instructions on how to fix it, which worked.

Issue solved. Thanks and wish you a great weekend.
