### ISSUE TITLE
Items lose connection to other participants

### ISSUE THREAD

**Issue by HikerBoricua** [phw198/OutlookGoogleCalendarSync#965]
**OGCS Version**: v2.8.0.0 
**Edition**: Installed 
**Sync Direction**: G->O followed by O->G

**Bug Description**  
Issue 2 - an invitation received into Google taken over to Outlook by OG Cal Sync and later updated by the organizer doesn't show the change in Outlook, looks like a new invitation. Results in duplicate events.
Issue 1 - an invitation originally sent from Google taken over to Outlook by OG Cal Sync behaves as if the invitation was never sent.

Context - we're a non-profit currently using Google for calendar and Outlook for email. Looking to migrate to Outlook for calendar. We have many calendar invitations, both incoming and outgoing. The steps below were meant to test whether OG Cal Sync could accomplish this while preserving the relationships between guests and hosts.

**Steps to Reproduce the Issue**  
1. In Outlook delete all calendar entries after today
2. Use OG Cal Sync to sync Google -> Outlook ("take over to Outlook")
3. After the takeover, switch sync direction Outlook -> Google
4. Find in Outlook and invitation that you had sent from Google prior to takeover
5. Open that invite and note that it doesn't show invitees
6. Click Invite Attendees, note that the invitees are remembered but the invite hasn't been sent
7. Ask someone who invited you to a meeting to change that meeting and send you updated invite
8. Note that in Outlook the original of the invite remains unchanged
9. Note that the updated invite results in a new (duplicate) calendar item

**Any other information**  
The two screen snippets are from my Outlook and from my Google, the latter shows the intent of the meeting change. There are likely additional steps captured in the log, please disregard.
![View in Outlook](https://user-images.githubusercontent.com/38139762/76427874-4a802880-6383-11ea-8ced-7b76d9631f84.png)
![View in Google](https://user-images.githubusercontent.com/38139762/76427896-51a73680-6383-11ea-849e-2ca3b781149f.png)

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4318763/OGcalsync.log)

**Comment by phw198** [comment]
I don't think I see a bug in any of that?

> Open that invite and note that it doesn't show invitees  

Not sure what you mean, but given you next point, OGCS must have synced atttendees...

> Click Invite Attendees, note that the invitees are remembered but the invite hasn't been sent  

Are you expecting the invite to have been sent? I certainly wouldn't - they already have the invite from Google where it originated, they don't want or need another from Outlook because you happen to have synced it there with OGCS.

> Ask someone who invited you to a meeting to change that meeting and send you updated invite
Note that in Outlook the original of the invite remains unchanged  

Why would it magically change in Outlook? The organiser would have updated the Google invitation and it would have updated in your Google. And because you changed OGCS to sync from Outlook to Google, there's no way Outlook would get updated.

> Note that the updated invite results in a new (duplicate) calendar item  

A duplicate in Google? Not completely surprised - the updated invite probably has a new internal ID number which no longer matches with the one you synced to Outlook. Now you have switched sync from Outlook to Google and have "merge items" on, you'll get a duplicate.

So OGCS is working as designed....I just think your intended use case doesn't fit, and won't ever. Your main problem, as I see it, is how will the original organiser know that their invited attendee now has the calendar item in Outlook instead of Google. OGCS isn't intended as an account migration tool.

**Comment by HikerBoricua** [comment]
Fair enough, thanks for getting back to me.
