### ISSUE TITLE
System.Runtime.InteropServices.COMException: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

### ISSUE THREAD

**Issue by WarningU2** [phw198/OutlookGoogleCalendarSync#966]
I appear to be getting several of these errors when trying to sync. 
System.Runtime.InteropServices.COMException: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
It resolves itself - eventually.  

OGCS Version: 2.8.3.0 - version is the "installed" version not portable

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4324416/OGcalsync.log)

**Comment by pitaki** [comment]
Possibly the same origin of trouble. Including log-file and screenshot of the message
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4425387/OGcalsync.log)
![OGcalsync](https://user-images.githubusercontent.com/4083033/78331054-f2a59d80-758d-11ea-8ab4-632f86fdd960.png)

**Comment by phw198** [comment]
@WarningU2 Does this happen quite frequently? Looks to be related to Push Sync and the connection to Outlook dropping.

:package: I've added an automatic reconnection in (instead of waiting for the next scheduled sync) - could you try [v2.8.3.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4587123/v2.8.3.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and see if that helps?

Let me know how it goes.

**Comment by phw198** [comment]
@pitaki Your issue is different and looks to be due to Outlook being slow to start after you've run OGCS. Try the latest alpha release and raise a separate issue if still a problem.

**Comment by WarningU2** [comment]
Hi Paul ... thanks for responding.   Yes it happens all the time.  Most recent log attached.   
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4588179/OGcalsync.log)

**Comment by WarningU2** [comment]
Fix applied as instructed.   Initial Sync performed without issue.   Testing with new entry now

**Comment by WarningU2** [comment]
Placed entry into google calendar and one in to outlook calendar.  Sync successful for both entries.   Crossing fingers.   If it generates the error again within the next week I'll report here.   Otherwise you may consider this closed if I don't respond by that time,   :)

**Comment by WarningU2** [comment]
Looks like you have fixed the issue.   I would have had errors by now and there is not one.   Thank you Paul.
