### ISSUE TITLE
Can't load the programme

### ISSUE THREAD

**Issue by jamesmc-s** [phw198/OutlookGoogleCalendarSync#967]
I keeping getting this error & the solution doesn't work

0x80004002 - E_NOINTERFACE
No such interface supported

This should be fixed with a simple Office Repair.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
