### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ronhoo** [phw198/OutlookGoogleCalendarSync#980]
This tuesday I got a update of office 2019, and now I have the failure  as in the attach

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.
![sync](https://user-images.githubusercontent.com/33182395/79505508-c4679980-8034-11ea-87f7-efbeccb84573.JPG)
![sync](https://user-images.githubusercontent.com/33182395/79505546-d34e4c00-8034-11ea-930e-34ddc111beb9.JPG)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4489678/OGcalsync.log)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
