### ISSUE TITLE
OGCS Throws Telemetry error if google-analytics is blacklisted on the network

### ISSUE THREAD

**Issue by jmfranz** [phw198/OutlookGoogleCalendarSync#981]
**OGCS Version**: v2.8.0.0
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
Error window pops up when opening OGCS informing that google-analytics could not be resolved. Telemetry should not be mandatory (specially through google) and the inability to connect should not result in a user level error.

**Steps to Reproduce the Issue**  
1. Block google-analytics on your DNS server
1. Open OGCS

**Any other information**  
I am using pi-hole as a DNS server

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

And I'm fairly sure this is fixed...

**Comment by jmfranz** [comment]
Indeed is fixed in the alpha. I forgot to check the update alpha checkbox when uptading.
