### ISSUE TITLE
Out of order?

### ISSUE THREAD

**Issue by JuergenLuenser** [phw198/OutlookGoogleCalendarSync#989]
(https://github.com/phw198/OutlookGoogleCalendarSync/files/4608209/OGcalsync.log)

[CalSync.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/4608213/CalSync.pdf)

----

**OGCS Version**: v2.7.0.0
Installed

**Problem Description**  
OGCS is not working any more. All entrys in Google have been deleted and cannot be restored although existent in Outlook.

**Steps to Reproduce the Issue**  
1. \<Update> Not working
2. Disconnected and retrieved, without effect

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by JuergenLuenser** [comment]
As requested

Mit besten Grüssen/Met vriendelijke Groeten/Best regards/Meilleures salutations

Jürgen Lünser

**Comment by phw198** [comment]
:paperclips: If you tried attaching files to the ticket when replying by email, unfortunately that doesn't work - please log in to GitHub to upload files.

**Comment by JuergenLuenser** [comment]
Hi,

I found the cause and fixed it myself.

Mit besten Grüssen/Met vriendelijke Groeten/Best regards/Meilleures salutations

Jürgen Lünser
