### ISSUE TITLE
Added events to outlook, no longer appearing in google 

### ISSUE THREAD

**Issue by nz123ash** [phw198/OutlookGoogleCalendarSync#995]
Using OGCS 2.8.0
Had been working fine. Added some new events to outlook today and clicked sync, and they are not appearing in google. 
Have tried disconnecting from google account and starting again but to no avail. 

Sorry i'm not very techy, so have probably used all the wrong lingo, but would appreciate any help or guidance. 
thanks

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
